import type { EndpointRiskLevel } from 'corsair/core';

export type AgentyMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type AgentyHostType = 'main' | 'browser';

export type AgentyRoute = {
	key: string;
	group: string;
	name: string;
	method: AgentyMethod;
	path: string;
	hostType: AgentyHostType;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const agentyRoutes = [
	{
		key: 'addListRows',
		group: 'lists',
		name: 'addListRows',
		method: 'POST',
		path: '/lists/{list_id}/rows',
		hostType: 'main',
		description:
			"Tool to add new rows to a list. Use when you need to insert one or more data rows into an existing list. Column names in row objects must match the list's schema.",
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'agentsControllerCreateAgent',
		group: 'agents',
		name: 'agentsControllerCreateAgent',
		method: 'POST',
		path: '/agents',
		hostType: 'main',
		description:
			"Creates a new Agenty agent for web scraping, change detection, crawling, map monitoring, or brand monitoring. Use this tool to set up automated data extraction agents. Requires: - name: A descriptive name for the agent - type: One of 'scraping', 'changedetection', 'crawling', 'mapmonitoring', 'brandmonitoring' - config: Configuration object with url, browser, and collections defining what data to extract The config.collections array contains field definitions with CSS selectors or other extraction methods. Each field specifies what data to extract and how (TEXT content, ATTR for attributes, etc.). Optional: Set start=true to immediately run the agent after creation, or configure a scheduler for recurring runs. Returns the created agent with its unique agent_id for future reference.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'agentsControllerGetTemplates',
		group: 'agents',
		name: 'agentsControllerGetTemplates',
		method: 'GET',
		path: '/agents/templates',
		hostType: 'main',
		description:
			'Tool to fetch all public agent templates and sample agents. Use when listing available templates for users to select.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'agentsDeleteById',
		group: 'agents',
		name: 'agentsDeleteById',
		method: 'DELETE',
		path: '/agents/{agent_id}',
		hostType: 'main',
		description:
			'Tool to delete a single agent by its ID. Use when you need to permanently remove an agent after confirming it exists.',
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'agentsGetAll',
		group: 'agents',
		name: 'agentsGetAll',
		method: 'GET',
		path: '/agents',
		hostType: 'main',
		description:
			'Tool to fetch all active agents under an account. Use after authenticating when you need to list agents with pagination and sorting.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'agentsGetById',
		group: 'agents',
		name: 'agentsGetById',
		method: 'GET',
		path: '/agents/{agent_id}',
		hostType: 'main',
		description:
			'Retrieves complete details of a specific agent including its configuration, input settings, scheduler, and metadata. Use this tool when you need to: - View full agent configuration and settings - Check agent type and current version - Access scheduler and script configurations - Verify agent status before executing jobs - Retrieve agent metadata for updates or cloning',
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'agentsUpdateById',
		group: 'agents',
		name: 'agentsUpdateById',
		method: 'PUT',
		path: '/agents/{agent_id}',
		hostType: 'main',
		description:
			"Updates an existing agent's configuration, settings, and metadata. Use this tool to modify an agent's properties such as name, type, config, tags, scheduler, scripts, or visibility settings. The API only returns the fields that were updated in the response, not the complete agent object. To get the full updated agent details, use the 'Get Agent by ID' action after updating. Example uses: - \"Update agent abc123 to change its name to 'Production Scraper'\" - \"Enable scheduling for agent xyz789 with a cron expression '0 */6 * * *'\" - \"Update agent def456 config to scrape a different URL\"",
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'apiKeysControllerCreateApiKeys',
		group: 'apiKeys',
		name: 'apiKeysControllerCreateApiKeys',
		method: 'POST',
		path: '/apikeys',
		hostType: 'main',
		description:
			'Creates a new API key for programmatic access to the Agenty API. The generated API key can be used to authenticate API requests with different permission levels (Owner, Admin, or Manager). The key is returned in the response and should be securely stored as it provides access to your Agenty account.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'apiKeysDeleteById',
		group: 'apiKeys',
		name: 'apiKeysDeleteById',
		method: 'DELETE',
		path: '/apikeys/{key_id}',
		hostType: 'main',
		description:
			'Delete an API key by its unique identifier. Use this tool to permanently revoke access for a specific API key. The key_id can be obtained from the "Get all API keys" or "Create API key" actions. This action cannot be undone.',
		pathParams: ['key_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'apiKeysDownload',
		group: 'apiKeys',
		name: 'apiKeysDownload',
		method: 'GET',
		path: '/apikeys/download',
		hostType: 'main',
		description:
			'Tool to download all API keys under an account in CSV format. Use when you need a complete list of API keys for export or backup.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'apiKeysGetAll',
		group: 'apiKeys',
		name: 'apiKeysGetAll',
		method: 'GET',
		path: '/apikeys',
		hostType: 'main',
		description:
			'Tool to retrieve all API keys under an account. Use after authentication when you need to list API keys with pagination and sorting.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'apiKeysGetById',
		group: 'apiKeys',
		name: 'apiKeysGetById',
		method: 'GET',
		path: '/apikeys/{key_id}',
		hostType: 'main',
		description:
			"Retrieves detailed information about a specific API key by its ID. Use this action when you need to: - Get the full details of an API key including its value, role, and status - Verify the existence and properties of a specific API key - Check if an API key is enabled or disabled The key_id can be obtained from the 'Get all API keys' action or when creating a new API key.",
		pathParams: ['key_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'apiKeysResetById',
		group: 'apiKeys',
		name: 'apiKeysResetById',
		method: 'GET',
		path: '/apikeys/{key_id}/reset',
		hostType: 'main',
		description:
			"Resets (regenerates) the secret value of an existing API key. The old secret becomes invalid immediately. Important: This action only confirms the reset was successful but does NOT return the new secret. After resetting, use the 'Get API Key By ID' action to retrieve the new secret value. Use this when you need to: - Rotate API key secrets for security - Invalidate a compromised API key and generate a new secret - Update credentials as part of security maintenance",
		pathParams: ['key_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'apiKeysUpdateById',
		group: 'apiKeys',
		name: 'apiKeysUpdateById',
		method: 'PUT',
		path: '/apikeys/{key_id}',
		hostType: 'main',
		description:
			"Updates an existing API key's name and role by its unique identifier. This action allows you to modify the display name and permission level of an API key. Only the name and role fields can be updated; other properties are read-only. After updating, the action automatically fetches and returns the complete updated API key details. Use this when you need to: - Rename an API key for better identification - Change the permission level (Owner, Admin, or Manager) of an API key - Update multiple properties of an API key at once",
		pathParams: ['key_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'captureScreenshot',
		group: 'browser',
		name: 'captureScreenshot',
		method: 'GET',
		path: '/screenshot',
		hostType: 'browser',
		description:
			'Tool to capture a full-page or visible screenshot of any webpage URL. Use when you need to capture visual representation of a webpage as an image file. The screenshot is captured using browser automation with default settings.',
		pathParams: [],
		queryParams: ['url'],
		riskLevel: 'read' as const,
	},
	{
		key: 'captureScreenshotWithOptions',
		group: 'browser',
		name: 'captureScreenshotWithOptions',
		method: 'POST',
		path: '/screenshot',
		hostType: 'browser',
		description:
			'Tool to capture webpage screenshots with extensive customization options including full-page capture, image format, quality settings, viewport configuration, and post-processing. Use when you need to take screenshots of web pages with specific requirements for size, format, or rendering behavior.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'changeApiKeyStatusById',
		group: 'apiKeys',
		name: 'changeApiKeyStatusById',
		method: 'GET',
		path: '/apikeys/{key_id}/status',
		hostType: 'main',
		description:
			'Toggles the enabled/disabled status of an API key. This endpoint switches the key between enabled and disabled states - if the key is currently enabled, it will be disabled, and vice versa. Returns a confirmation message upon successful status change. Use this after retrieving the key_id from the list or get API key endpoints.',
		pathParams: ['key_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'connectionsGetAll',
		group: 'connections',
		name: 'connectionsGetAll',
		method: 'GET',
		path: '/connections',
		hostType: 'main',
		description:
			'Retrieves all connections from your Agenty account. Supports pagination via limit/offset and sorting by field name. Returns an empty list if no connections exist.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'convertUrlToPdf',
		group: 'browser',
		name: 'convertUrlToPdf',
		method: 'GET',
		path: '/pdf',
		hostType: 'browser',
		description:
			'Tool to convert a webpage URL to a PDF document. Use when you need to generate a PDF file from a web page for archival, reporting, or offline viewing purposes.',
		pathParams: [],
		queryParams: ['url'],
		riskLevel: 'read' as const,
	},
	{
		key: 'convertUrlToPdfWithOptions',
		group: 'browser',
		name: 'convertUrlToPdfWithOptions',
		method: 'POST',
		path: '/pdf',
		hostType: 'browser',
		description:
			'Tool to convert a URL or raw HTML to PDF with customizable options. Use when you need to generate PDFs with specific formatting requirements like custom page sizes, margins, headers/footers, or orientation. Supports both URL-based and HTML content conversion.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'copyAgent',
		group: 'agents',
		name: 'copyAgent',
		// Live Agenty API: POST /v2/agents/{agent_id}/copy with body { name }.
		// OpenAPI "GET .../clone" is stale and 404s.
		method: 'POST',
		path: '/agents/{agent_id}/copy',
		hostType: 'main',
		description:
			"Tool to copy an existing agent by its ID, creating a duplicate with optionally a new name. Use when you need to duplicate an agent's configuration to create a similar agent without starting from scratch.",
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createWorkflow',
		group: 'workflows',
		name: 'createWorkflow',
		method: 'POST',
		path: '/workflows',
		hostType: 'main',
		description:
			'Creates a new workflow in Agenty to automate actions based on agent events. Use this to set up automated responses like sending emails, triggering webhooks, or notifications when specific agent events occur (e.g., job completed, job failed).',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'dashboardGetReportsUsage',
		group: 'dashboard',
		name: 'dashboardGetReportsUsage',
		method: 'GET',
		path: '/dashboard',
		hostType: 'main',
		description:
			'Tool to fetch account reports like pages used by agent, date, and product. Use when analyzing usage over a date range.',
		pathParams: [],
		queryParams: ['end', 'start'],
		riskLevel: 'read' as const,
	},
	{
		key: 'deleteListRow',
		group: 'lists',
		name: 'deleteListRow',
		method: 'DELETE',
		path: '/lists/{list_id}/rows/{id}',
		hostType: 'main',
		description:
			'Tool to delete a specific row from a list by its unique identifier. Use when you need to permanently remove a single row from a list.',
		pathParams: ['list_id', 'id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteListRows',
		group: 'lists',
		name: 'deleteListRows',
		method: 'DELETE',
		path: '/lists/{list_id}/rows',
		hostType: 'main',
		description:
			'Tool to delete specific rows from a list by their IDs. Use when you need to remove one or more rows from a list by providing their unique identifiers.',
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteProject',
		group: 'projects',
		name: 'deleteProject',
		// Live Agenty API: DELETE /v2/projects?project_id={n}
		// Path /projects/{id} 404s; query name is project_id (not id).
		method: 'DELETE',
		path: '/projects',
		hostType: 'main',
		description:
			'Tool to delete a project by its ID. Use when you need to permanently remove a project. This action cannot be undone, so ensure the project ID is correct before deletion.',
		pathParams: [],
		queryParams: ['project_id'],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteSchedule',
		group: 'scheduler',
		name: 'deleteSchedule',
		method: 'DELETE',
		path: '/scheduler/{agent_id}',
		hostType: 'main',
		description:
			'Tool to delete a schedule for an agent by its agent ID. Use when you need to remove scheduled automation for a specific agent.',
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteWorkflow',
		group: 'workflows',
		name: 'deleteWorkflow',
		method: 'DELETE',
		path: '/workflows/{workflow_id}',
		hostType: 'main',
		description:
			'Tool to delete a workflow by its ID. Use when you need to permanently remove a workflow after confirming it exists.',
		pathParams: ['workflow_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'downloadAgentResult',
		group: 'jobs',
		name: 'downloadAgentResult',
		method: 'GET',
		path: '/results/{agent_id}/download',
		hostType: 'main',
		description:
			'Tool to download agent results by agent ID in CSV, TSV or JSON format. Use when you need to export or analyze agent execution results as a file.',
		pathParams: ['agent_id'],
		queryParams: [
			'sort',
			'limit',
			'order',
			'format',
			'offset',
			'search',
			'collection',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'downloadListRows',
		group: 'lists',
		name: 'downloadListRows',
		method: 'GET',
		path: '/lists/{list_id}/rows/download',
		hostType: 'main',
		description:
			'Tool to download list rows as CSV file. Use when you need to export or backup all rows from a specific list.',
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'downloadUsers',
		group: 'users',
		name: 'downloadUsers',
		method: 'GET',
		path: '/users/download',
		hostType: 'main',
		description:
			'Tool to download users list in CSV format. Use when you need to export or backup the complete list of team members and users.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'downloadWorkflows',
		group: 'workflows',
		name: 'downloadWorkflows',
		method: 'GET',
		path: '/workflows/download',
		hostType: 'main',
		description:
			'Tool to download all workflows in CSV format. Use when you need to export or backup all workflows from your account. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'extractBrowserStructuredData',
		group: 'browser',
		name: 'extractBrowserStructuredData',
		method: 'POST',
		path: '/extract',
		hostType: 'browser',
		description:
			'Tool to auto-extract structured data from a webpage including schema.org, RDFa, Microdata, and JSON-LD formats. Use when you need to automatically extract semantic markup from web pages without writing custom scraping rules. The API returns organized structured data in four categories: metatags, microdata, rdfa, and jsonld.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'extractStructuredData',
		group: 'browser',
		name: 'extractStructuredData',
		method: 'GET',
		path: '/extract',
		hostType: 'browser',
		description:
			'Tool to auto-extract structured data from a webpage URL. Use when you need to extract schema.org, RDFa, Microdata, or JSON-LD structured data from web pages.',
		pathParams: [],
		queryParams: ['url'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAgentResult',
		group: 'jobs',
		name: 'getAgentResult',
		method: 'GET',
		path: '/results/{agent_id}',
		hostType: 'main',
		description:
			"Tool to get the most recent result data for an agent. Use when you need to retrieve and view the scraped/collected data from an agent's latest execution. Returns result data with pagination support.",
		pathParams: ['agent_id'],
		queryParams: ['sort', 'limit', 'order', 'offset', 'search', 'collection'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllTeamMembers',
		group: 'users',
		name: 'getAllTeamMembers',
		method: 'GET',
		path: '/users',
		hostType: 'main',
		description:
			'Tool to retrieve all team members (users) under an account. Use after authentication when you need to list team members with pagination, sorting, and search filtering.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset', 'search'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getBrowserRedirects',
		group: 'browser',
		name: 'getBrowserRedirects',
		method: 'GET',
		path: '/redirects',
		hostType: 'browser',
		description:
			'Tool to get the complete redirect chain for a URL. Use when you need to trace how a URL redirects, including both server-side (HTTP 3xx redirects) and client-side redirects (JavaScript, meta tags). Returns an ordered list of all redirect steps from the original URL to the final destination.',
		pathParams: [],
		queryParams: ['url'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobResult',
		group: 'jobs',
		name: 'getJobResult',
		method: 'GET',
		path: '/jobs/{job_id}/result',
		hostType: 'main',
		description:
			'Tool to get the result data from a completed job. Use when you need to retrieve and view the scraped/collected data from a finished job. Returns result data with pagination support.',
		pathParams: ['job_id'],
		queryParams: [
			'sort',
			'limit',
			'order',
			'format',
			'offset',
			'search',
			'collection',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getListById',
		group: 'lists',
		name: 'getListById',
		method: 'GET',
		path: '/lists/{list_id}',
		hostType: 'main',
		description:
			"Retrieves detailed information about a specific list by its ID. Use this action when you need to: - Get the full details of a list including its name, description, and metadata - Verify the existence of a specific list - Check when a list was created or last updated - Access additional data associated with a list The list_id can be obtained from the 'Get all lists' action or when creating a new list.",
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getListRowById',
		group: 'lists',
		name: 'getListRowById',
		method: 'GET',
		path: '/lists/{list_id}/rows/{id}',
		hostType: 'main',
		description:
			'Tool to fetch a specific row by its ID from a list. Use when you need to retrieve a single data entry from a list using its unique identifier.',
		pathParams: ['list_id', 'id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPageContent',
		group: 'browser',
		name: 'getPageContent',
		method: 'GET',
		path: '/content',
		hostType: 'browser',
		description:
			"Tool to fetch the complete HTML content of any webpage URL. Use this when you need to retrieve the full HTML source code of a page, including content rendered after JavaScript execution. The API navigates to the URL using proxies and captures the page's source content.",
		pathParams: [],
		queryParams: ['url'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPageContentWithOptions',
		group: 'browser',
		name: 'getPageContentWithOptions',
		method: 'POST',
		path: '/content',
		hostType: 'browser',
		description:
			'Tool to fetch HTML content of a webpage with custom options including ad blocking. Use this when you need to retrieve the full HTML source of a webpage, particularly for web scraping or content analysis tasks. The tool supports ad blocking to speed up page loads and reduce unnecessary content.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'getProjectById',
		group: 'projects',
		name: 'getProjectById',
		method: 'GET',
		path: '/projects/{id}',
		hostType: 'main',
		description:
			'Retrieves complete details of a specific project by its ID, including name, description, creator information, and timestamps. Use this to get project metadata before adding agents, checking project existence, or verifying project details for updates.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getRedirectsWithOptions',
		group: 'browser',
		name: 'getRedirectsWithOptions',
		method: 'POST',
		path: '/redirects',
		hostType: 'browser',
		description:
			'Tool to get the complete redirect chain of a URL with custom navigation options. Use when you need to trace URL redirects including both server-side (3xx) and client-side redirects (JavaScript, meta tags). Supports custom timeout and navigation wait conditions to ensure all redirects are captured.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'getSchedule',
		group: 'scheduler',
		name: 'getSchedule',
		method: 'GET',
		path: '/scheduler/{agent_id}',
		hostType: 'main',
		description:
			'Tool to retrieve the schedule configuration for a specific agent. Use when you need to check the current scheduling settings for an agent.',
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUserById',
		group: 'users',
		name: 'getUserById',
		method: 'GET',
		path: '/users/{user_id}',
		hostType: 'main',
		description:
			'Tool to retrieve detailed information about a user by their ID. Use this to fetch user profile data including email, role, status, and activity timestamps.',
		pathParams: ['user_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkflowById',
		group: 'workflows',
		name: 'getWorkflowById',
		method: 'GET',
		path: '/workflows/{workflow_id}',
		hostType: 'main',
		description:
			'Retrieves complete details of a specific workflow by its ID. Use this to view workflow configuration including agents, triggers, and actions before updating or deleting.',
		pathParams: ['workflow_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'inputsGetByAgentId',
		group: 'inputs',
		name: 'inputsGetByAgentId',
		method: 'GET',
		path: '/inputs/{agent_id}',
		hostType: 'main',
		description:
			"Retrieves the input configuration for a specific agent by its ID. Returns the input source type (URL, manual list, saved list reference, or another agent's output) and associated configuration details. Use this to inspect an agent's current input setup before modifying it or starting a job, or to verify what data sources an agent will process.",
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'inputsUpdateByAgentId',
		group: 'inputs',
		name: 'inputsUpdateByAgentId',
		method: 'PUT',
		path: '/inputs/{agent_id}',
		hostType: 'main',
		description:
			"Updates the input configuration for a specific agent in Agenty. This tool modifies where an agent gets its input data from. You can configure the agent to: - Pull from a URL feed (type='url') - Use a manually specified list of URLs (type='manual') - Reference data from an Agenty list (type='list') - Use output from another agent (type='agent') Use this after creating or identifying an agent to set up its data source before running jobs.",
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'jobsDownload',
		group: 'jobs',
		name: 'jobsDownload',
		method: 'GET',
		path: '/jobs/download',
		hostType: 'main',
		description:
			'Tool to download all jobs in CSV format. Use when you need a complete list of jobs for export or analysis.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset', 'agent_id'],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsDownloadFilesById',
		group: 'jobs',
		name: 'jobsDownloadFilesById',
		method: 'GET',
		path: '/jobs/{job_id}/files/download',
		hostType: 'main',
		description:
			'Tool to download output files by job ID. Use when you need to fetch a specific output file after a job completes.',
		pathParams: ['job_id'],
		queryParams: ['name'],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsDownloadResultById',
		group: 'jobs',
		name: 'jobsDownloadResultById',
		method: 'GET',
		path: '/jobs/{job_id}/result/download',
		hostType: 'main',
		description:
			'Tool to download the agent output result by job ID. Use when you need to fetch the final output of a completed job in CSV, TSV, or JSON format.',
		pathParams: ['job_id'],
		queryParams: ['sort', 'limit', 'order', 'format', 'offset', 'collection'],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsGetAll',
		group: 'jobs',
		name: 'jobsGetAll',
		method: 'GET',
		path: '/jobs',
		hostType: 'main',
		description:
			'Tool to fetch all jobs under an account. Use when you need to view and filter the list of jobs with pagination and sorting.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset', 'agent_id'],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsGetById',
		group: 'jobs',
		name: 'jobsGetById',
		method: 'GET',
		path: '/jobs/{job_id}',
		hostType: 'main',
		description:
			'Retrieves comprehensive details about a specific job including its status, progress metrics (pages processed/succeeded/failed), timing information (created/started/completed times), resource consumption (page credits), and any error messages. Use this action to check job status, monitor execution progress, or diagnose job failures. Returns complete job metadata needed before downloading results.',
		pathParams: ['job_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsGetLogsById',
		group: 'jobs',
		name: 'jobsGetLogsById',
		method: 'GET',
		path: '/jobs/{job_id}/logs',
		hostType: 'main',
		description:
			'Tool to fetch logs for a given job by its ID. Use when you need to review or debug job execution logs with pagination support.',
		pathParams: ['job_id'],
		queryParams: ['limit', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsListFilesById',
		group: 'jobs',
		name: 'jobsListFilesById',
		method: 'GET',
		path: '/jobs/{job_id}/files',
		hostType: 'main',
		description:
			'Lists all output files generated by a specific job. Returns file names and sizes for available downloads including CSV/JSON/TSV data exports and compressed logs. Use this after a job completes to discover what output files are available before downloading them.',
		pathParams: ['job_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'jobsStart',
		group: 'jobs',
		name: 'jobsStart',
		method: 'POST',
		path: '/jobs/start',
		hostType: 'main',
		description:
			'Tool to start a new agent job. Use when you need to trigger execution of an existing agent.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'jobsStopById',
		group: 'jobs',
		name: 'jobsStopById',
		method: 'GET',
		path: '/jobs/{job_id}/stop',
		hostType: 'main',
		description:
			'Tool to stop a running job by job ID. Use when you need to halt an in-progress job before it completes. Confirm the job ID beforehand to avoid unintended stops.',
		pathParams: ['job_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'listsClearRows',
		group: 'lists',
		name: 'listsClearRows',
		method: 'DELETE',
		path: '/lists/{list_id}/rows/clear',
		hostType: 'main',
		description:
			'Tool to clear all rows in a list by its ID. Use when you need to wipe out all data in a list before re-populating (e.g., "Clear all rows in list 123").',
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'listsControllerCreateList',
		group: 'lists',
		name: 'listsControllerCreateList',
		method: 'POST',
		path: '/lists',
		hostType: 'main',
		description:
			"Tool to create a new list. Use after preparing the list name and optional description. Example: \"Create a list named 'Contacts' with description 'Potential leads'.\"",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'listsDeleteById',
		group: 'lists',
		name: 'listsDeleteById',
		method: 'DELETE',
		path: '/lists/{list_id}',
		hostType: 'main',
		description:
			'Tool to delete a specific list by its ID. Use when you need to permanently remove a list after confirming it exists.',
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'listsDownload',
		group: 'lists',
		name: 'listsDownload',
		method: 'GET',
		path: '/lists/download',
		hostType: 'main',
		description:
			'Tool to download all lists in CSV format. Use when you need a complete set of lists for export or backup.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listsGetAll',
		group: 'lists',
		name: 'listsGetAll',
		method: 'GET',
		path: '/lists',
		hostType: 'main',
		description:
			'Tool to retrieve all lists under an account. Use after authentication when you need to list lists with pagination and sorting.',
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listsGetRowsById',
		group: 'lists',
		name: 'listsGetRowsById',
		method: 'GET',
		path: '/lists/{list_id}/rows',
		hostType: 'main',
		description:
			'Tool to fetch all rows in a specified list. Use when you need to retrieve all data entries from a list with optional pagination and sorting. Example: "Fetch rows from list \'61db...\' with limit=50".',
		pathParams: ['list_id'],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listsUpdateById',
		group: 'lists',
		name: 'listsUpdateById',
		method: 'PUT',
		path: '/lists/{list_id}',
		hostType: 'main',
		description:
			"Tool to update a list's name and optionally description by list ID. The name field is always required. Use when you need to modify list metadata after confirming its ID. Example: \"Update list 123 with name 'My Updated List' and description 'New description'\".",
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'listsUploadCsv',
		group: 'lists',
		name: 'listsUploadCsv',
		method: 'POST',
		path: '/lists/{list_id}/upload',
		hostType: 'main',
		description:
			"Tool to upload a CSV file to an Agenty list for bulk import of data rows. Use this action when you need to: - Import multiple rows of data into an existing list from a CSV file - Bulk update list data - Add structured tabular data to a list Prerequisites: The target list must already exist. Use the 'Create List' action first if needed.",
		pathParams: ['list_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'patchWorkflow',
		group: 'workflows',
		name: 'patchWorkflow',
		method: 'PATCH',
		path: '/workflows/{workflow_id}',
		hostType: 'main',
		description:
			'Tool to partially update a workflow by ID. Use when you need to update specific fields of a workflow without replacing the entire workflow object. This action performs a PATCH operation, allowing you to update only the fields you specify (e.g., just the name) without affecting other workflow properties. Currently supports updating the workflow name.',
		pathParams: ['workflow_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'projectsAddAgents',
		group: 'projects',
		name: 'projectsAddAgents',
		method: 'POST',
		path: '/projects/{project_id}/add',
		hostType: 'main',
		description:
			"Add one or more agents to an Agenty project to organize and group related agents together. This action associates agents with a project, allowing better organization and management of your automation workflows. The response includes the complete updated project information with all associated agents. Prerequisites: - Project must exist (use projects_get_all to find valid project IDs) - Agent(s) must exist (use agents_get_all to find valid agent IDs) Example usage: \"Add agents ['tx8lubfbun', 'o3xuc2n8es'] to project 7\"",
		pathParams: ['project_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'projectsControllerCreateProject',
		group: 'projects',
		name: 'projectsControllerCreateProject',
		method: 'POST',
		path: '/projects',
		hostType: 'main',
		description:
			'Creates a new project in Agenty. Use this to initialize a project with a name and optional description.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'projectsGetAll',
		group: 'projects',
		name: 'projectsGetAll',
		method: 'GET',
		path: '/projects',
		hostType: 'main',
		description:
			"Retrieve all projects in the authenticated user's account. Returns a paginated list of projects with metadata (total count, pagination info). Use this to discover available projects, check project existence, or get project IDs for other operations. Supports sorting by fields like 'name' or 'created_at'.",
		pathParams: [],
		queryParams: ['sort', 'limit', 'order', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'removeAgentFromProject',
		group: 'projects',
		name: 'removeAgentFromProject',
		method: 'DELETE',
		path: '/projects/{project_id}/delete',
		hostType: 'main',
		description:
			"Remove an agent from an Agenty project. Use when you need to disassociate an agent from a project while keeping both the agent and project intact. The agent will no longer be part of the project's organization structure.",
		pathParams: ['project_id'],
		queryParams: ['agent_id'],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'scrapeWebpageData',
		group: 'browser',
		name: 'scrapeWebpageData',
		method: 'POST',
		path: '/scrape',
		hostType: 'browser',
		description:
			'Tool to scrape data from any webpage using jQuery/CSS selectors. Use when you need to extract specific data from web pages by defining jQuery selector expressions. Each query field maps a name to a jQuery expression (e.g., "$(\'h1\').text()" extracts the h1 text). The browser will load the page, execute JavaScript, and run your jQuery queries to extract the data.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'toggleSchedule',
		group: 'scheduler',
		name: 'toggleSchedule',
		method: 'PATCH',
		path: '/scheduler/{agent_id}',
		hostType: 'main',
		description:
			"Tool to toggle schedule on/off for an agent. Use when you need to enable or disable an agent's scheduled execution without modifying other agent settings.",
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'transferAgentOwnership',
		group: 'agents',
		name: 'transferAgentOwnership',
		method: 'PUT',
		path: '/agents/{agent_id}/transfer',
		hostType: 'main',
		description:
			"Tool to transfer agent ownership to another Agenty account. Use when you need to move an agent to a different user's account by specifying their email address.",
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateListRow',
		group: 'lists',
		name: 'updateListRow',
		method: 'PUT',
		path: '/lists/{list_id}/rows/{id}',
		hostType: 'main',
		description:
			"Tool to update a specific row in a list by list ID and row ID. Use when you need to modify existing data in a list row. The row_data must include the '_id' field and any column fields (col1, col2, etc.) you want to update.",
		pathParams: ['list_id', 'id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateProject',
		group: 'projects',
		name: 'updateProject',
		method: 'PUT',
		path: '/projects/{id}',
		hostType: 'main',
		description:
			"Update an existing project's name and description in Agenty. Use this to modify project details such as changing the project name or updating its description.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateSchedule',
		group: 'scheduler',
		name: 'updateSchedule',
		method: 'POST',
		path: '/scheduler/{agent_id}',
		hostType: 'main',
		description:
			'Updates the schedule configuration for a specific agent. Use when you need to modify how often an agent runs automatically.',
		pathParams: ['agent_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateUserById',
		group: 'users',
		name: 'updateUserById',
		method: 'PUT',
		path: '/users/{user_id}',
		hostType: 'main',
		description:
			"Tool to update a user's information by user ID. Use this to modify user properties including email, role, status, name, and subscription settings. Email, role, and status are required fields.",
		pathParams: ['user_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateWorkflow',
		group: 'workflows',
		name: 'updateWorkflow',
		method: 'PUT',
		path: '/workflows/{workflow_id}',
		hostType: 'main',
		description:
			"Tool to update an existing workflow's configuration by workflow ID. Use this to modify workflow properties including name, agent selection, trigger conditions, and actions to execute. Workflows automate responses to agent events such as job completion, errors, or change detection. Common use cases include sending notifications, triggering webhooks, or updating external systems.",
		pathParams: ['workflow_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
] as const;

export type AgentyRoutes = typeof agentyRoutes;
