export type SnapchatRiskLevel = 'read' | 'write' | 'destructive';
export type SnapchatOperation = {
	readonly id: string;
	readonly name: string;
	readonly title: string;
	readonly riskLevel: SnapchatRiskLevel;
};

export const SNAPCHAT_TOOLKIT_VERSION = '20260721_00' as const;

export const SNAPCHAT_OPERATIONS = [
	{
		id: 'SNAPCHAT_ADD_SEGMENT_USERS',
		name: 'addSegmentUsers',
		title: 'Add Segment Users',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_COPY_MEDIA',
		name: 'copyMedia',
		title: 'Copy Media',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ACCOUNT_ROLE',
		name: 'createAccountRole',
		title: 'Create Account Role',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_AUDIENCE_SIZE_V2',
		name: 'createAdaccountsAudienceSizeV2',
		title: 'Create Adaccounts Audience Size V2',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_CREATIVE_ELEMENTS',
		name: 'createAdaccountsCreativeElements',
		title: 'Create Adaccounts Creative Elements',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_DYNAMIC_TEMPLATES',
		name: 'createAdaccountsDynamicTemplates',
		title: 'Create Adaccounts Dynamic Templates',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_EVENT_DETAILS',
		name: 'createAdaccountsEventDetails',
		title: 'Create Adaccounts Event Details',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_INTERACTION_ZONES',
		name: 'createAdaccountsInteractionZones',
		title: 'Create Adaccounts Interaction Zones',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_OFFER_DISCLAIMERS',
		name: 'createAdaccountsOfferDisclaimers',
		title: 'Create Adaccounts Offer Disclaimers',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_RESERVED_FORECASTING',
		name: 'createAdaccountsReservedForecasting',
		title: 'Create Adaccounts Reserved Forecasting',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ADACCOUNTS_TARGETING_INSIGHTS',
		name: 'createAdaccountsTargetingInsights',
		title: 'Create Adaccounts Targeting Insights',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_AD_ACCOUNT',
		name: 'createAdAccount',
		title: 'Create Ad Account',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_AD_SQUAD',
		name: 'createAdSquad',
		title: 'Create Ad Squad',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_BILLING_CENTER',
		name: 'createBillingCenter',
		title: 'Create Billing Center',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_CAMPAIGN',
		name: 'createCampaign',
		title: 'Create Campaign',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_CATALOGS_FACETS',
		name: 'createCatalogsFacets',
		title: 'Create Catalogs Facets',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_CATALOGS_FLIGHTS_SEARCH',
		name: 'createCatalogsFlightsSearch',
		title: 'Create Catalogs Flights Search',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_CATALOGS_PRODUCT_FEEDS',
		name: 'createCatalogsProductFeeds',
		title: 'Create Catalogs Product Feeds',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_CATALOGS_PRODUCT_SETS',
		name: 'createCatalogsProductSets',
		title: 'Create Catalogs Product Sets',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_CATALOG_ROLE',
		name: 'createCatalogRole',
		title: 'Create Catalog Role',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_MEDIA',
		name: 'createMedia',
		title: 'Create Media',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ORGANIZATIONS_CATALOGS',
		name: 'createOrganizationsCatalogs',
		title: 'Create Organizations Catalogs',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_ORG_ROLE',
		name: 'createOrgRole',
		title: 'Create Org Role',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_CREATE_SEGMENT',
		name: 'createSegment',
		title: 'Create Segment',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_DELETE_ADACCOUNTS_OFFER_DISCLAIMERS',
		name: 'deleteAdaccountsOfferDisclaimers',
		title: 'Delete Adaccounts Offer Disclaimers',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_ADSQUADS',
		name: 'deleteAdsquads',
		title: 'Delete Adsquads',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_ALL_SEGMENT_USERS',
		name: 'deleteAllSegmentUsers',
		title: 'Delete All Segment Users',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_CAMPAIGN',
		name: 'deleteCampaign',
		title: 'Delete Campaign',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_CATALOGS',
		name: 'deleteCatalogs',
		title: 'Delete Catalogs',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_EVENT_DETAILS',
		name: 'deleteEventDetails',
		title: 'Delete Event Details',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_MEMBER',
		name: 'deleteMember',
		title: 'Delete Member',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_PRODUCT_FEEDS',
		name: 'deleteProductFeeds',
		title: 'Delete Product Feeds',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_ROLE',
		name: 'deleteRole',
		title: 'Delete Role',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_SEGMENT',
		name: 'deleteSegment',
		title: 'Delete Segment',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_DELETE_SEGMENT_USERS',
		name: 'deleteSegmentUsers',
		title: 'Delete Segment Users',
		riskLevel: 'destructive',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_ADSQUADS',
		name: 'getAdaccountsAdsquads',
		title: 'Get Adaccounts Adsquads',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_AD_SQUAD_UI_RENDER_DATA',
		name: 'getAdaccountsAdSquadUiRenderData',
		title: 'Get Adaccounts Ad Squad Ui Render Data',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_DYNAMIC_TEMPLATES',
		name: 'getAdaccountsDynamicTemplates',
		title: 'Get Adaccounts Dynamic Templates',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_EVENT_DETAILS',
		name: 'getAdaccountsEventDetails',
		title: 'Get Adaccounts Event Details',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_INTERACTION_ZONES',
		name: 'getAdaccountsInteractionZones',
		title: 'Get Adaccounts Interaction Zones',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_LEADS_REPORT',
		name: 'getAdaccountsLeadsReport',
		title: 'Get Adaccounts Leads Report',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_MOBILE_APPS',
		name: 'getAdaccountsMobileApps',
		title: 'Get Adaccounts Mobile Apps',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_OFFER_DISCLAIMERS',
		name: 'getAdaccountsOfferDisclaimers',
		title: 'Get Adaccounts Offer Disclaimers',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_SPEND_GUIDANCE',
		name: 'getAdaccountsSpendGuidance',
		title: 'Get Adaccounts Spend Guidance',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADACCOUNTS_STATS_REPORT',
		name: 'getAdaccountsStatsReport',
		title: 'Get Adaccounts Stats Report',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADSQUADS_AUDIENCE_SIZE_V2',
		name: 'getAdsquadsAudienceSizeV2',
		title: 'Get Adsquads Audience Size V2',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ADSQUADS_STATS_REPORT',
		name: 'getAdsquadsStatsReport',
		title: 'Get Adsquads Stats Report',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_ACCOUNT',
		name: 'getAdAccount',
		title: 'Get Ad Account',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_ACCOUNTS_LEAD_GENERATION_FORMS',
		name: 'getAdAccountsLeadGenerationForms',
		title: 'Get Ad Accounts Lead Generation Forms',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_ACCOUNTS_STATS',
		name: 'getAdAccountsStats',
		title: 'Get Ad Accounts Stats',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_SQUAD',
		name: 'getAdSquad',
		title: 'Get Ad Squad',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_SQUAD_RESTRICTIONS',
		name: 'getAdSquadRestrictions',
		title: 'Get Ad Squad Restrictions',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_SQUAD_STATS',
		name: 'getAdSquadStats',
		title: 'Get Ad Squad Stats',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_SQUAD_TARGETING',
		name: 'getAdSquadTargeting',
		title: 'Get Ad Squad Targeting',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AD_STATS',
		name: 'getAdStats',
		title: 'Get Ad Stats',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_AUTHENTICATED_USER',
		name: 'getAuthenticatedUser',
		title: 'Get Authenticated User',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_BILLING_CENTER',
		name: 'getBillingCenter',
		title: 'Get Billing Center',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_CAMPAIGN',
		name: 'getCampaign',
		title: 'Get Campaign',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_CAMPAIGNS_BY_IDS',
		name: 'getCampaignsByIds',
		title: 'Get Campaigns By Ids',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_CAMPAIGN_CHANGELOG',
		name: 'getCampaignChangelog',
		title: 'Get Campaign Changelog',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_CAMPAIGN_STATS',
		name: 'getCampaignStats',
		title: 'Get Campaign Stats',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_CATALOGS',
		name: 'getCatalogs',
		title: 'Get Catalogs',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_CATALOGS_PRODUCT_SETS',
		name: 'getCatalogsProductSets',
		title: 'Get Catalogs Product Sets',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_DYNAMIC_TEMPLATE',
		name: 'getDynamicTemplate',
		title: 'Get Dynamic Template',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_DYNAMIC_TEMPLATES_EXTERNAL_CHANGELOGS',
		name: 'getDynamicTemplatesExternalChangelogs',
		title: 'Get Dynamic Templates External Changelogs',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_EVENT_DETAILS',
		name: 'getEventDetails',
		title: 'Get Event Details',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_FUNDING_SOURCE',
		name: 'getFundingSource',
		title: 'Get Funding Source',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_INTERACTION_ZONE',
		name: 'getInteractionZone',
		title: 'Get Interaction Zone',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_INVOICE',
		name: 'getInvoice',
		title: 'Get Invoice',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_MEDIA',
		name: 'getMedia',
		title: 'Get Media',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_MEDIA_BY_IDS',
		name: 'getMediaByIds',
		title: 'Get Media By Ids',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_MEDIA_STATS',
		name: 'getMediaStats',
		title: 'Get Media Stats',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_MEMBER',
		name: 'getMember',
		title: 'Get Member',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ORGANIZATION',
		name: 'getOrganization',
		title: 'Get Organization',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ORGANIZATIONS_CATALOGS',
		name: 'getOrganizationsCatalogs',
		title: 'Get Organizations Catalogs',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ORGANIZATIONS_MOBILE_APPS',
		name: 'getOrganizationsMobileApps',
		title: 'Get Organizations Mobile Apps',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_ORGANIZATIONS_PUBLIC_PROFILES',
		name: 'getOrganizationsPublicProfiles',
		title: 'Get Organizations Public Profiles',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_PIXELS',
		name: 'getPixels',
		title: 'Get Pixels',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_PRODUCT_FEEDS',
		name: 'getProductFeeds',
		title: 'Get Product Feeds',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_PRODUCT_FEEDS_FEED_UPLOADS',
		name: 'getProductFeedsFeedUploads',
		title: 'Get Product Feeds Feed Uploads',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_PRODUCT_SETS',
		name: 'getProductSets',
		title: 'Get Product Sets',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_SEGMENT',
		name: 'getSegment',
		title: 'Get Segment',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_CARRIERS',
		name: 'getTargetingCarriers',
		title: 'Get Targeting Carriers',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_CONNECTION_TYPES',
		name: 'getTargetingConnectionTypes',
		title: 'Get Targeting Connection Types',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_DEMOGRAPHICS_ADVANCED_DEMOGRAPHICS',
		name: 'getTargetingDemographicsAdvancedDemographics',
		title: 'Get Targeting Demographics Advanced Demographics',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_DEMOGRAPHICS_AGE_GROUP',
		name: 'getTargetingDemographicsAgeGroup',
		title: 'Get Targeting Demographics Age Group',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_DEMOGRAPHICS_GENDER',
		name: 'getTargetingDemographicsGender',
		title: 'Get Targeting Demographics Gender',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_DEMOGRAPHICS_LANGUAGES',
		name: 'getTargetingDemographicsLanguages',
		title: 'Get Targeting Demographics Languages',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_DEVICE_IOS_OS_VERSION',
		name: 'getTargetingDeviceIosOsVersion',
		title: 'Get Targeting Device Ios Os Version',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_DEVICE_MARKETING_NAMES',
		name: 'getTargetingDeviceMarketingNames',
		title: 'Get Targeting Device Marketing Names',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_GEO_POSTAL_CODE',
		name: 'getTargetingGeoPostalCode',
		title: 'Get Targeting Geo Postal Code',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_GEO_REGION',
		name: 'getTargetingGeoRegion',
		title: 'Get Targeting Geo Region',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_GEO_US_POSTAL_CODE',
		name: 'getTargetingGeoUsPostalCode',
		title: 'Get Targeting Geo Us Postal Code',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_GEO_US_REGION',
		name: 'getTargetingGeoUsRegion',
		title: 'Get Targeting Geo Us Region',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_INTERESTS_DLXC',
		name: 'getTargetingInterestsDlxc',
		title: 'Get Targeting Interests Dlxc',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_INTERESTS_DLXP',
		name: 'getTargetingInterestsDlxp',
		title: 'Get Targeting Interests Dlxp',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_INTERESTS_DLXS',
		name: 'getTargetingInterestsDlxs',
		title: 'Get Targeting Interests Dlxs',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_INTERESTS_NLN',
		name: 'getTargetingInterestsNln',
		title: 'Get Targeting Interests Nln',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_INTERESTS_PLC',
		name: 'getTargetingInterestsPlc',
		title: 'Get Targeting Interests Plc',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_LOCATION_CATEGORIES_LOI',
		name: 'getTargetingLocationCategoriesLoi',
		title: 'Get Targeting Location Categories Loi',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_METROS',
		name: 'getTargetingMetros',
		title: 'Get Targeting Metros',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_OS_TYPES',
		name: 'getTargetingOsTypes',
		title: 'Get Targeting Os Types',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_OS_VERSIONS',
		name: 'getTargetingOsVersions',
		title: 'Get Targeting Os Versions',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_V1_INTERESTS_SC_LS',
		name: 'getTargetingV1InterestsScLs',
		title: 'Get Targeting V1 Interests Sc Ls',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_V1_INTERESTS_SHP',
		name: 'getTargetingV1InterestsShp',
		title: 'Get Targeting V1 Interests Shp',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_V1_INTERESTS_VAC',
		name: 'getTargetingV1InterestsVac',
		title: 'Get Targeting V1 Interests Vac',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_GET_TARGETING_V1_OPTIONS',
		name: 'getTargetingV1Options',
		title: 'Get Targeting V1 Options',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ACCOUNT_ROLES',
		name: 'listAccountRoles',
		title: 'List Account Roles',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ADS_BY_ACCOUNT',
		name: 'listAdsByAccount',
		title: 'List Ads By Account',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ADS_BY_AD_SQUAD',
		name: 'listAdsByAdSquad',
		title: 'List Ads By Ad Squad',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ADS_BY_CAMPAIGN',
		name: 'listAdsByCampaign',
		title: 'List Ads By Campaign',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_AD_ACCOUNTS',
		name: 'listAdAccounts',
		title: 'List Ad Accounts',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_AD_SQUADS',
		name: 'listAdSquads',
		title: 'List Ad Squads',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_BILLING_CENTERS',
		name: 'listBillingCenters',
		title: 'List Billing Centers',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_CAMPAIGNS',
		name: 'listCampaigns',
		title: 'List Campaigns',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_CATALOG_ROLES',
		name: 'listCatalogRoles',
		title: 'List Catalog Roles',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_CREATIVES',
		name: 'listCreatives',
		title: 'List Creatives',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_FUNDING_SOURCES',
		name: 'listFundingSources',
		title: 'List Funding Sources',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_INVOICES',
		name: 'listInvoices',
		title: 'List Invoices',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_MEDIA',
		name: 'listMedia',
		title: 'List Media',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_MEMBERS',
		name: 'listMembers',
		title: 'List Members',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_MEMBER_ROLES',
		name: 'listMemberRoles',
		title: 'List Member Roles',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ORGANIZATIONS',
		name: 'listOrganizations',
		title: 'List Organizations',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ORG_PIXELS',
		name: 'listOrgPixels',
		title: 'List Org Pixels',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_ORG_ROLES',
		name: 'listOrgRoles',
		title: 'List Org Roles',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_PHONE_NUMBERS',
		name: 'listPhoneNumbers',
		title: 'List Phone Numbers',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_SEGMENTS',
		name: 'listSegments',
		title: 'List Segments',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_SPONSORED_CONTENT',
		name: 'listSponsoredContent',
		title: 'List Sponsored Content',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_LIST_TRANSACTIONS',
		name: 'listTransactions',
		title: 'List Transactions',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_SEARCH_ADS_LIBRARY_SPONSORED_CONTENT',
		name: 'searchAdsLibrarySponsoredContent',
		title: 'Search Ads Library Sponsored Content',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_SEARCH_CATALOGS_HOTELS',
		name: 'searchCatalogsHotels',
		title: 'Search Catalogs Hotels',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_SEARCH_CATALOG_PRODUCTS',
		name: 'searchCatalogProducts',
		title: 'Search Catalog Products',
		riskLevel: 'read',
	},
	{
		id: 'SNAPCHAT_UPDATE_AD_ACCOUNT',
		name: 'updateAdAccount',
		title: 'Update Ad Account',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_UPDATE_AD_SQUAD',
		name: 'updateAdSquad',
		title: 'Update Ad Squad',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_UPDATE_BILLING_CENTER',
		name: 'updateBillingCenter',
		title: 'Update Billing Center',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_UPDATE_CAMPAIGN',
		name: 'updateCampaign',
		title: 'Update Campaign',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_UPDATE_SEGMENT',
		name: 'updateSegment',
		title: 'Update Segment',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_UPLOAD_MEDIA_MULTIPART',
		name: 'uploadMediaMultipart',
		title: 'Upload Media Multipart',
		riskLevel: 'write',
	},
	{
		id: 'SNAPCHAT_VALIDATE_CONVERSION_EVENT',
		name: 'validateConversionEvent',
		title: 'Validate Conversion Event',
		riskLevel: 'write',
	},
] as const satisfies readonly SnapchatOperation[];

export type SnapchatOperationId = (typeof SNAPCHAT_OPERATIONS)[number]['id'];
export type SnapchatOperationName =
	(typeof SNAPCHAT_OPERATIONS)[number]['name'];
