import type { CorsairEndpoint, EndpointRiskLevel } from 'corsair/core';
import { logEventFromContext } from 'corsair/core';
import type { BlazemeterApi, BlazemeterMethod } from './client';
import { makeBlazemeterRequest } from './client';
import { persistBlazemeterResult } from './endpoints/persist';
import type { BlazemeterContext } from './index';

export type BlazemeterOperationDefinition = {
	key: string;
	slug: string;
	api: BlazemeterApi;
	method: BlazemeterMethod;
	path: string;
	params: readonly string[];
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	multipart?: boolean;
	riskLevel: EndpointRiskLevel;
	description: string;
	irreversible?: boolean;
};

/**
 * Route and input inventory for catalog version 20260702_00. Parameter tokens
 * use `name:type` for required values and `name?:type` for optional values.
 */
export const BLAZEMETER_OPERATIONS = [
	{
		key: 'transactions.convert',
		slug: 'BLAZEMETER_CONVERT_TRANSACTIONS',
		api: 'mock',
		method: 'POST',
		path: '/transactions/convert',
		params: ['file?:object', 'verbose?:boolean', 'fileContent?:object'],
		queryParams: ['verbose'],
		multipart: true,
		riskLevel: 'write',
		description:
			'Convert Swagger, HAR, YAML, or other transaction input to BlazeMeter DSL',
	},
	{
		key: 'schedules.create',
		slug: 'BLAZEMETER_CREATE_API_MONITORING_SCHEDULE',
		api: 'core',
		method: 'POST',
		path: '/schedules',
		params: ['cron:string', 'testId?:integer', 'testCollectionId?:integer'],
		riskLevel: 'write',
		description: 'Create a cron schedule for a test or multi-test',
	},
	{
		key: 'assetDependencies.create',
		slug: 'BLAZEMETER_CREATE_WORKSPACES_ASSETS_DEPENDENCIES2',
		api: 'asset',
		method: 'POST',
		path: '/workspaces/{wsId}/assets/{aId}/dependencies/{targetDepId}',
		params: [
			'aId:string',
			'wsId:integer',
			'targetDepId:string',
			'dependencyType?:string',
		],
		pathParams: ['wsId', 'aId', 'targetDepId'],
		riskLevel: 'write',
		description: 'Create a dependency from one workspace asset to another',
	},
	{
		key: 'multiTests.create',
		slug: 'BLAZEMETER_CREATE_MULTI_TEST',
		api: 'core',
		method: 'POST',
		path: '/multi-tests',
		params: ['name:string', 'projectId:integer', 'collectionType?:string'],
		riskLevel: 'write',
		description: 'Create a multi-test in a project',
	},
	{
		key: 'privateLocations.create',
		slug: 'BLAZEMETER_CREATE_PRIVATE_LOCATION',
		api: 'core',
		method: 'POST',
		path: '/private-locations',
		params: [
			'name:string',
			'type:string',
			'slots?:integer',
			'funcIds:array',
			'accountId:integer',
			'engineXms?:integer',
			'engineXmx?:integer',
			'consoleXms?:integer',
			'consoleXmx?:integer',
			'overrideCPU?:integer',
			'workspacesId:array',
			'overrideMemory?:integer',
			'threadsPerEngine:integer',
		],
		riskLevel: 'write',
		description: 'Create a private execution location',
	},
	{
		key: 'privateLocations.createAgent',
		slug: 'BLAZEMETER_CREATE_PRIVATE_LOCATIONS_SERVERS',
		api: 'core',
		method: 'POST',
		path: '/private-locations/{id}/servers',
		params: ['id:string', 'name:string', 'address?:string'],
		pathParams: ['id'],
		riskLevel: 'write',
		description: 'Create an agent in a private location',
	},
	{
		key: 'projects.create',
		slug: 'BLAZEMETER_CREATE_PROJECT',
		api: 'core',
		method: 'POST',
		path: '/projects',
		params: ['name:string', 'description?:string', 'workspaceId:integer'],
		riskLevel: 'write',
		description: 'Create a project in a workspace',
	},
	{
		key: 'search.execute',
		slug: 'BLAZEMETER_CREATE_SEARCH',
		api: 'core',
		method: 'POST',
		path: '/search',
		params: [
			'skip?:integer',
			'limit?:integer',
			'entity:string',
			'fields?:array',
			'filters?:object',
			'ordering?:array',
			'accountId?:unknown',
			'workspaceId?:unknown',
		],
		riskLevel: 'read',
		description:
			'Search BlazeMeter entities using filters, selected fields, and ordering',
	},
	{
		key: 'tags.create',
		slug: 'BLAZEMETER_CREATE_TAGS',
		api: 'core',
		method: 'POST',
		path: '/workspaces/{workspaceId}/tags',
		params: ['label:string', 'workspaceId:integer'],
		pathParams: ['workspaceId'],
		riskLevel: 'write',
		description: 'Create a workspace tag',
	},
	{
		key: 'tests.create',
		slug: 'BLAZEMETER_CREATE_TEST',
		api: 'core',
		method: 'POST',
		path: '/tests',
		params: ['name:string', 'projectId:integer', 'configuration:object'],
		riskLevel: 'write',
		description: 'Create a performance or functional test',
	},
	{
		key: 'assets.create',
		slug: 'BLAZEMETER_CREATE_WORKSPACES_ASSETS',
		api: 'asset',
		method: 'POST',
		path: '/workspaces/{wsId}/assets',
		params: [
			'data?:object',
			'name:string',
			'type:string',
			'wsId:integer',
			'metadata?:object',
			'packageId?:string',
			'displayName:string',
		],
		pathParams: ['wsId'],
		riskLevel: 'write',
		description: 'Create an Asset Repository asset',
	},
	{
		key: 'packages.create',
		slug: 'BLAZEMETER_CREATE_WORKSPACES_PACKAGES',
		api: 'asset',
		method: 'POST',
		path: '/workspaces/{wsId}/packages',
		params: [
			'name?:string',
			'wsId:integer',
			'version?:string',
			'displayName?:string',
			'dependencies?:object',
		],
		pathParams: ['wsId'],
		riskLevel: 'write',
		description: 'Create an Asset Repository package',
	},
	{
		key: 'transactions.create',
		slug: 'BLAZEMETER_CREATE_WORKSPACES_TRANSACTIONS',
		api: 'mock',
		method: 'POST',
		path: '/workspaces/{workspaceId}/transactions',
		params: ['serviceId:integer', 'workspaceId:integer', 'transactions:array'],
		pathParams: ['workspaceId'],
		queryParams: ['serviceId'],
		riskLevel: 'write',
		description: 'Create service-virtualization transactions in a workspace',
	},
	{
		key: 'schedules.remove',
		slug: 'BLAZEMETER_DELETE_API_MONITORING_SCHEDULE',
		api: 'core',
		method: 'DELETE',
		path: '/schedules/{schedule_id}',
		params: ['schedule_id:string'],
		pathParams: ['schedule_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a test schedule',
	},
	{
		key: 'privateLocations.removeWorkspace',
		slug: 'BLAZEMETER_DELETE_PRIVATE_LOCATION_WORKSPACE',
		api: 'core',
		method: 'DELETE',
		path: '/private-locations/{harborId}/workspaces/{workspaceId}',
		params: ['harborId:string', 'workspaceId:integer'],
		pathParams: ['harborId', 'workspaceId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Remove a workspace from a private location',
	},
	{
		key: 'projects.remove',
		slug: 'BLAZEMETER_DELETE_PROJECT',
		api: 'core',
		method: 'DELETE',
		path: '/projects/{id}',
		params: ['id:integer', 'force?:boolean'],
		pathParams: ['id'],
		queryParams: ['force'],
		riskLevel: 'destructive',
		irreversible: true,
		description:
			'Delete a project, optionally forcing removal of contained data',
	},
	{
		key: 'tests.removeFile',
		slug: 'BLAZEMETER_DELETE_TEST_FILE',
		api: 'core',
		method: 'POST',
		path: '/tests/{testId}/delete-file',
		params: ['testId:integer', 'fileName:string'],
		pathParams: ['testId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete an uploaded test asset file',
	},
	{
		key: 'tests.remove',
		slug: 'BLAZEMETER_DELETE_TESTS',
		api: 'core',
		method: 'DELETE',
		path: '/tests/{testId}',
		params: ['testId:integer'],
		pathParams: ['testId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a test',
	},
	{
		key: 'assets.remove',
		slug: 'BLAZEMETER_DELETE_WORKSPACES_ASSETS',
		api: 'asset',
		method: 'DELETE',
		path: '/workspaces/{wsId}/assets/{aId}',
		params: ['aId:string', 'wsId:integer'],
		pathParams: ['wsId', 'aId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a workspace asset',
	},
	{
		key: 'assetDependencies.remove',
		slug: 'BLAZEMETER_DELETE_WORKSPACE_ASSET_DEPENDENCY',
		api: 'asset',
		method: 'DELETE',
		path: '/workspaces/{wsId}/assets/dependencies/{dId}',
		params: ['dId:string', 'wsId:integer'],
		pathParams: ['wsId', 'dId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete an asset dependency by ID',
	},
	{
		key: 'assetDependencies.removeMatching',
		slug: 'BLAZEMETER_DELETE_WORKSPACES_ASSETS_DEPENDENCIES',
		api: 'asset',
		method: 'DELETE',
		path: '/workspaces/{wsId}/assets/dependencies',
		params: [
			'wsId:integer',
			'sourceDepId?:string',
			'targetDepId?:string',
			'sourceDepType?:string',
			'targetDepType?:string',
			'dependencyType?:string',
		],
		pathParams: ['wsId'],
		queryParams: [
			'sourceDepId',
			'targetDepId',
			'sourceDepType',
			'targetDepType',
			'dependencyType',
		],
		riskLevel: 'destructive',
		irreversible: true,
		description:
			'Delete asset dependencies matching source, target, and type filters',
	},
	{
		key: 'workspaces.removeLogs',
		slug: 'BLAZEMETER_DELETE_WORKSPACES_LOGS',
		api: 'core',
		method: 'POST',
		path: '/workspaces/{id}/delete-logs',
		params: ['id:integer', 'masterIds:array'],
		pathParams: ['id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete master execution logs from a workspace',
	},
	{
		key: 'workspaces.removeManagers',
		slug: 'BLAZEMETER_DELETE_WORKSPACES_MANAGERS',
		api: 'core',
		method: 'POST',
		path: '/workspaces/{id}/delete-managers',
		params: ['id:integer', 'managersIds:array'],
		pathParams: ['id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Remove managers from a workspace',
	},
	{
		key: 'packages.remove',
		slug: 'BLAZEMETER_DELETE_WORKSPACES_PACKAGES',
		api: 'asset',
		method: 'DELETE',
		path: '/workspaces/{wsId}/packages/{pId}',
		params: ['pId:string', 'wsId:integer'],
		pathParams: ['wsId', 'pId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a workspace package',
	},
	{
		key: 'tests.duplicate',
		slug: 'BLAZEMETER_DUPLICATE_TEST',
		api: 'core',
		method: 'POST',
		path: '/tests/{test_id}/duplicate',
		params: ['test_id:integer'],
		pathParams: ['test_id'],
		riskLevel: 'write',
		description: 'Duplicate a test and its configuration',
	},
	{
		key: 'packages.export',
		slug: 'BLAZEMETER_EXPORT_PACKAGE',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/packages/{pId}/export',
		params: ['pId:string', 'wsId:integer'],
		pathParams: ['wsId', 'pId'],
		riskLevel: 'read',
		description: 'Export one package as a zip archive',
	},
	{
		key: 'packages.exportMany',
		slug: 'BLAZEMETER_EXPORT_WORKSPACES_PACKAGES',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/packages/export',
		params: ['wsId:integer', 'packageIds:array'],
		pathParams: ['wsId'],
		riskLevel: 'read',
		description: 'Export multiple workspace packages as a zip archive',
	},
	{
		key: 'testData.generateFromModel',
		slug: 'BLAZEMETER_GENERATE_WORKSPACES_DATAMODELS',
		api: 'tdm',
		method: 'POST',
		path: '/workspaces/{workspaceId}/datamodels/{modelId}/generate',
		params: ['modelId:string', 'numRecords?:integer', 'workspaceId:integer'],
		pathParams: ['workspaceId', 'modelId'],
		riskLevel: 'write',
		description: 'Generate synthetic records from a stored data model',
	},
	{
		key: 'testData.generate',
		slug: 'BLAZEMETER_GENERATE_WORKSPACES_TESTDATA',
		api: 'tdm',
		method: 'POST',
		path: '/workspaces/{workspaceId}/testdata/generate',
		params: ['data:object', 'entityName:string', 'workspaceId:integer'],
		pathParams: ['workspaceId'],
		queryParams: ['entityName'],
		riskLevel: 'write',
		description: 'Generate test data from an inline model',
	},
	{
		key: 'schedules.get',
		slug: 'BLAZEMETER_GET_API_MONITORING_SCHEDULE',
		api: 'core',
		method: 'GET',
		path: '/schedules/{schedule_id}',
		params: ['schedule_id:string'],
		pathParams: ['schedule_id'],
		riskLevel: 'read',
		description: 'Get a schedule by ID',
	},
	{
		key: 'schedules.list',
		slug: 'BLAZEMETER_GET_API_MONITORING_SCHEDULES',
		api: 'core',
		method: 'GET',
		path: '/schedules',
		params: [
			'skip?:integer',
			'limit?:integer',
			'testId?:integer',
			'enabled?:boolean',
			'accountId?:integer',
			'projectId?:integer',
			'workspaceId?:integer',
			'collectionId?:integer',
		],
		riskLevel: 'read',
		description: 'List schedules with scope and pagination filters',
	},
	{
		key: 'accounts.list',
		slug: 'BLAZEMETER_GET_ACCOUNTS',
		api: 'core',
		method: 'GET',
		path: '/accounts',
		params: ['skip?:integer', 'sort?:array', 'limit?:integer'],
		riskLevel: 'read',
		description: 'List accounts available to the authenticated user',
	},
	{
		key: 'assetDependencies.forAsset',
		slug: 'BLAZEMETER_GET_WORKSPACES_ASSETS_DEPENDENCIES3',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/assets/{aId}/dependencies',
		params: ['aId:string', 'wsId:integer'],
		pathParams: ['wsId', 'aId'],
		riskLevel: 'read',
		description: 'List dependencies belonging to an asset',
	},
	{
		key: 'generator.functions',
		slug: 'BLAZEMETER_GET_GENERATOR_FUNCTIONS',
		api: 'tdm',
		method: 'GET',
		path: '/generator/functions',
		params: [],
		riskLevel: 'read',
		description: 'List available synthetic-data generator functions',
	},
	{
		key: 'generator.seedLists',
		slug: 'BLAZEMETER_GET_GENERATOR_SEEDLISTS',
		api: 'tdm',
		method: 'GET',
		path: '/generator/seedlists',
		params: [],
		riskLevel: 'read',
		description: 'List available generator seed lists',
	},
	{
		key: 'info.health',
		slug: 'BLAZEMETER_GET_INFO_HEALTH',
		api: 'asset',
		method: 'GET',
		path: '/info/health',
		params: [],
		riskLevel: 'read',
		description: 'Get Asset Repository service health',
	},
	{
		key: 'info.version',
		slug: 'BLAZEMETER_GET_INFO_VERSION',
		api: 'asset',
		method: 'GET',
		path: '/info/version',
		params: [],
		riskLevel: 'read',
		description: 'Get Asset Repository build information',
	},
	{
		key: 'masters.summary',
		slug: 'BLAZEMETER_GET_MASTERS_REPORTS_MAIN_SUMMARY',
		api: 'core',
		method: 'GET',
		path: '/masters/{master_id}/reports/default/summary',
		params: ['master_id:integer'],
		pathParams: ['master_id'],
		riskLevel: 'read',
		description: 'Get request statistics for a master test run',
	},
	{
		key: 'multiTests.get',
		slug: 'BLAZEMETER_GET_MULTI_TEST',
		api: 'core',
		method: 'GET',
		path: '/multi-tests/{collectionId}',
		params: ['collectionId:integer', 'populateTests?:boolean'],
		pathParams: ['collectionId'],
		riskLevel: 'read',
		description: 'Get a multi-test by ID',
	},
	{
		key: 'multiTests.list',
		slug: 'BLAZEMETER_GET_MULTI_TESTS',
		api: 'core',
		method: 'GET',
		path: '/multi-tests',
		params: [
			'skip?:integer',
			'sort?:array',
			'limit?:integer',
			'projectId?:integer',
			'workspaceId:integer',
		],
		riskLevel: 'read',
		description: 'List multi-tests in a workspace',
	},
	{
		key: 'privateLocations.list',
		slug: 'BLAZEMETER_GET_PRIVATE_LOCATIONS',
		api: 'core',
		method: 'GET',
		path: '/private-locations',
		params: [
			'skip?:integer',
			'limit?:integer',
			'types?:array',
			'accountId?:integer',
			'workspaceId?:integer',
		],
		riskLevel: 'read',
		description: 'List private execution locations',
	},
	{
		key: 'projects.get',
		slug: 'BLAZEMETER_GET_PROJECT_DETAILS',
		api: 'core',
		method: 'GET',
		path: '/projects/{id}',
		params: ['id:integer'],
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Get project details',
	},
	{
		key: 'projects.list',
		slug: 'BLAZEMETER_GET_PROJECTS',
		api: 'core',
		method: 'GET',
		path: '/projects',
		params: [
			'skip?:integer',
			'sort?:array',
			'name?:string',
			'limit?:integer',
			'accountId?:integer',
			'workspaceId?:integer',
		],
		riskLevel: 'read',
		description: 'List projects in a workspace',
	},
	{
		key: 'regions.list',
		slug: 'BLAZEMETER_GET_REGIONS',
		api: 'core',
		method: 'GET',
		path: '/locations',
		params: [],
		riskLevel: 'read',
		description: 'List execution regions and locations',
	},
	{
		key: 'search.metadata',
		slug: 'BLAZEMETER_GET_SEARCH_METADATA',
		api: 'core',
		method: 'GET',
		path: '/search/metadata',
		params: [],
		riskLevel: 'read',
		description: 'Get searchable entities, fields, relations, and operators',
	},
	{
		key: 'sharedFolders.list',
		slug: 'BLAZEMETER_GET_SHARED_FOLDERS',
		api: 'core',
		method: 'GET',
		path: '/folders',
		params: ['workspaceId:integer'],
		riskLevel: 'read',
		description: 'List shared folders in a workspace',
	},
	{
		key: 'tags.list',
		slug: 'BLAZEMETER_GET_TAGS',
		api: 'mock',
		method: 'GET',
		path: '/tags',
		params: ['skip?:integer', 'sort?:string', 'limit?:integer'],
		riskLevel: 'read',
		description: 'List Mock Services tags',
	},
	{
		key: 'tests.get',
		slug: 'BLAZEMETER_GET_TEST_DETAILS',
		api: 'core',
		method: 'GET',
		path: '/tests/{test_id}',
		params: ['test_id:integer'],
		pathParams: ['test_id'],
		riskLevel: 'read',
		description: 'Get test details',
	},
	{
		key: 'tests.validations',
		slug: 'BLAZEMETER_GET_TEST_VALIDATIONS',
		api: 'core',
		method: 'GET',
		path: '/tests/{testId}/validations',
		params: ['testId:integer'],
		pathParams: ['testId'],
		riskLevel: 'read',
		description: 'Get test-file validation results',
	},
	{
		key: 'tests.list',
		slug: 'BLAZEMETER_GET_TESTS',
		api: 'core',
		method: 'GET',
		path: '/tests',
		params: [
			'skip?:integer',
			'sort?:array',
			'name?:string',
			'type?:string',
			'limit?:integer',
			'platform?:string',
			'projectId?:integer',
			'workspaceId?:integer',
			'hasExecutions?:boolean',
		],
		riskLevel: 'read',
		description: 'List tests by workspace or project',
	},
	{
		key: 'tests.files',
		slug: 'BLAZEMETER_GET_TESTS_FILES',
		api: 'core',
		method: 'GET',
		path: '/tests/{testId}/files',
		params: ['name?:string', 'testId:integer'],
		pathParams: ['testId'],
		riskLevel: 'read',
		description: 'List files attached to a test',
	},
	{
		key: 'user.get',
		slug: 'BLAZEMETER_GET_USER',
		api: 'core',
		method: 'GET',
		path: '/user',
		params: [],
		riskLevel: 'read',
		description: 'Get the authenticated user profile',
	},
	{
		key: 'user.activeSessions',
		slug: 'BLAZEMETER_GET_USER_ACTIVE_SESSIONS',
		api: 'core',
		method: 'GET',
		path: '/user/active',
		params: [],
		riskLevel: 'read',
		description: 'List active test sessions for the authenticated user',
	},
	{
		key: 'user.invites',
		slug: 'BLAZEMETER_GET_USER_INVITES',
		api: 'core',
		method: 'GET',
		path: '/user/invites',
		params: [],
		riskLevel: 'read',
		description: 'List pending user invitations',
	},
	{
		key: 'user.projects',
		slug: 'BLAZEMETER_GET_USER_PROJECTS',
		api: 'core',
		method: 'GET',
		path: '/user/projects',
		params: [],
		riskLevel: 'read',
		description: 'List projects available to the authenticated user',
	},
	{
		key: 'serviceMockTemplates.get',
		slug: 'BLAZEMETER_GET_WORKSPACE_SERVICE_MOCK_TEMPLATE_BY_ID',
		api: 'mock',
		method: 'GET',
		path: '/workspaces/{workspaceId}/service-mock-templates/{serviceMockTemplateId}',
		params: ['workspaceId:integer', 'serviceMockTemplateId:integer'],
		pathParams: ['workspaceId', 'serviceMockTemplateId'],
		riskLevel: 'read',
		description: 'Get a virtual-service template by ID',
	},
	{
		key: 'assets.get',
		slug: 'BLAZEMETER_GET_WORKSPACES_ASSETS2',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{workspaceId}/assets/{assetId}',
		params: [
			'assetId:string',
			'withData?:boolean',
			'workspaceId:integer',
			'withDependencies?:boolean',
		],
		pathParams: ['workspaceId', 'assetId'],
		riskLevel: 'read',
		description: 'Get a workspace asset by ID',
	},
	{
		key: 'assets.data',
		slug: 'BLAZEMETER_GET_WORKSPACES_ASSETS_DATA',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/assets/{aId}/data',
		params: ['aId:string', 'wsId:integer'],
		pathParams: ['wsId', 'aId'],
		riskLevel: 'read',
		description: 'Get stored data for an asset',
	},
	{
		key: 'assetDependencies.get',
		slug: 'BLAZEMETER_GET_WORKSPACES_ASSETS_DEPENDENCIES2',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/assets/dependencies/{dId}',
		params: ['dId:string', 'wsId:integer'],
		pathParams: ['wsId', 'dId'],
		riskLevel: 'read',
		description: 'Get one asset dependency by ID',
	},
	{
		key: 'assets.list',
		slug: 'BLAZEMETER_GET_WORKSPACES_ASSETS',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{workspaceId}/assets',
		params: [
			'q?:array',
			'skip?:integer',
			'limit?:integer',
			'sortBy?:string',
			'sortDir?:string',
			'withData?:boolean',
			'withSystem?:boolean',
			'workspaceId:integer',
			'withAccShared?:boolean',
		],
		pathParams: ['workspaceId'],
		riskLevel: 'read',
		description: 'List Asset Repository assets in a workspace',
	},
	{
		key: 'assetDependencies.list',
		slug: 'BLAZEMETER_GET_WORKSPACES_ASSETS_DEPENDENCIES',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/assets/dependencies',
		params: [
			'skip?:integer',
			'wsId:integer',
			'limit?:integer',
			'sourceDepId?:string',
			'targetDepId?:string',
			'sourceDepType?:string',
			'targetDepType?:string',
			'dependencyType?:string',
		],
		pathParams: ['wsId'],
		riskLevel: 'read',
		description: 'List workspace asset dependencies',
	},
	{
		key: 'testData.getModel',
		slug: 'BLAZEMETER_GET_WORKSPACES_DATAMODELS2',
		api: 'tdm',
		method: 'GET',
		path: '/workspaces/{workspaceId}/datamodels/{dataModelId}',
		params: ['dataModelId:string', 'workspaceId:integer'],
		pathParams: ['workspaceId', 'dataModelId'],
		riskLevel: 'read',
		description: 'Get a data model by ID',
	},
	{
		key: 'workspaces.get',
		slug: 'BLAZEMETER_GET_WORKSPACE_DETAILS',
		api: 'core',
		method: 'GET',
		path: '/workspaces/{id}',
		params: ['id:integer'],
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Get workspace details',
	},
	{
		key: 'packages.get',
		slug: 'BLAZEMETER_GET_WORKSPACE_PACKAGE',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/packages/{pId}',
		params: ['pId:string', 'wsId:integer', 'withDependencies?:boolean'],
		pathParams: ['wsId', 'pId'],
		riskLevel: 'read',
		description: 'Get a workspace package',
	},
	{
		key: 'packages.dependencies',
		slug: 'BLAZEMETER_GET_WORKSPACES_PACKAGES_DEPENDENCIES',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/packages/{pId}/dependencies',
		params: ['pId:string', 'wsId:integer'],
		pathParams: ['wsId', 'pId'],
		riskLevel: 'read',
		description: 'List package dependencies',
	},
	{
		key: 'packages.list',
		slug: 'BLAZEMETER_GET_WORKSPACES_PACKAGES',
		api: 'asset',
		method: 'GET',
		path: '/workspaces/{wsId}/packages',
		params: [
			'q?:array',
			'skip?:integer',
			'wsId:integer',
			'limit?:integer',
			'sortBy?:string',
			'sortDir?:string',
		],
		pathParams: ['wsId'],
		riskLevel: 'read',
		description: 'List packages in a workspace',
	},
	{
		key: 'serviceMockTemplates.list',
		slug: 'BLAZEMETER_GET_WORKSPACES_SERVICE_MOCK_TEMPLATES',
		api: 'mock',
		method: 'GET',
		path: '/workspaces/{id}/service-mock-templates',
		params: ['id:integer'],
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'List virtual-service templates in a workspace',
	},
	{
		key: 'transactions.list',
		slug: 'BLAZEMETER_GET_WORKSPACES_TRANSACTIONS',
		api: 'mock',
		method: 'GET',
		path: '/workspaces/{id}/transactions',
		params: ['id:integer'],
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'List service-virtualization transactions in a workspace',
	},
	{
		key: 'workspaces.users',
		slug: 'BLAZEMETER_GET_WORKSPACES_USERS',
		api: 'core',
		method: 'GET',
		path: '/workspaces/{workspaceId}/users',
		params: [
			'roles?:array',
			'enabled?:boolean',
			'textFilter?:string',
			'workspaceId:integer',
			'excludeRoles?:array',
		],
		pathParams: ['workspaceId'],
		riskLevel: 'read',
		description: 'List users in a workspace',
	},
	{
		key: 'workspaces.list',
		slug: 'BLAZEMETER_GET_WORKSPACES',
		api: 'core',
		method: 'GET',
		path: '/workspaces',
		params: [
			'skip?:integer',
			'limit?:integer',
			'enabled?:boolean',
			'accountId:integer',
			'textFilter?:string',
		],
		riskLevel: 'read',
		description: 'List workspaces for an account',
	},
	{
		key: 'packages.import',
		slug: 'BLAZEMETER_IMPORT_WORKSPACE_PACKAGE',
		api: 'asset',
		method: 'POST',
		path: '/workspaces/{wsId}/packages/import',
		params: [
			'file:object',
			'wsId:integer',
			'force?:boolean',
			'overrides?:string',
		],
		pathParams: ['wsId'],
		multipart: true,
		riskLevel: 'write',
		description: 'Import a package zip into a workspace',
	},
	{
		key: 'generator.cardIssuers',
		slug: 'BLAZEMETER_LIST_GENERATOR_CARD_ISSUERS',
		api: 'tdm',
		method: 'GET',
		path: '/generator/cardIssuers',
		params: [],
		riskLevel: 'read',
		description: 'List available credit-card issuer generators',
	},
	{
		key: 'testData.publish',
		slug: 'BLAZEMETER_PUBLISH_API_DATA',
		api: 'tdm',
		method: 'POST',
		path: '/api-publish/publish',
		params: ['type?:string', 'attributes:object'],
		riskLevel: 'write',
		description:
			'Publish generated data through a Test Data orchestration target',
	},
	{
		key: 'user.register',
		slug: 'BLAZEMETER_REGISTER_USER',
		api: 'core',
		method: 'POST',
		path: '/user/register',
		params: [
			'email:string',
			'lastName:string',
			'password:string',
			'firstName:string',
		],
		riskLevel: 'write',
		description: 'Register a BlazeMeter user account',
	},
	{
		key: 'tests.start',
		slug: 'BLAZEMETER_START_TEST',
		api: 'core',
		method: 'POST',
		path: '/tests/{testId}/start',
		params: ['testId:integer', 'isDebugRun?:boolean', 'delayedStart?:boolean'],
		pathParams: ['testId'],
		queryParams: ['isDebugRun', 'delayedStart'],
		riskLevel: 'write',
		description: 'Start a configured test',
	},
	{
		key: 'masters.stop',
		slug: 'BLAZEMETER_STOP_MASTER',
		api: 'core',
		method: 'POST',
		path: '/masters/{master_id}/stop',
		params: ['master_id:integer'],
		pathParams: ['master_id'],
		riskLevel: 'destructive',
		description: 'Gracefully stop a running master execution',
	},
	{
		key: 'tests.stop',
		slug: 'BLAZEMETER_STOP_TEST',
		api: 'core',
		method: 'POST',
		path: '/tests/{test_id}/stop',
		params: ['test_id:integer'],
		pathParams: ['test_id'],
		riskLevel: 'destructive',
		description: 'Stop every active execution for a test',
	},
	{
		key: 'user.terminateSessions',
		slug: 'BLAZEMETER_TERMINATE_USER_ACTIVE_SESSIONS',
		api: 'core',
		method: 'POST',
		path: '/user/active/terminate',
		params: ['session_ids:array'],
		riskLevel: 'destructive',
		description: 'Immediately terminate selected active sessions',
	},
	{
		key: 'workspaces.terminateMasters',
		slug: 'BLAZEMETER_TERMINATE_WORKSPACES_MASTERS',
		api: 'core',
		method: 'POST',
		path: '/workspaces/{id}/terminate-masters',
		params: ['id:integer', 'dryRun?:boolean'],
		pathParams: ['id'],
		riskLevel: 'destructive',
		description: 'Terminate active master executions in a workspace',
	},
	{
		key: 'schedules.update',
		slug: 'BLAZEMETER_UPDATE_API_MONITORING_SCHEDULE',
		api: 'core',
		method: 'PATCH',
		path: '/schedules/{schedule_id}',
		params: ['enabled:boolean', 'schedule_id:string'],
		pathParams: ['schedule_id'],
		riskLevel: 'write',
		description: 'Enable or disable a schedule',
	},
	{
		key: 'projects.update',
		slug: 'BLAZEMETER_UPDATE_PROJECT',
		api: 'core',
		method: 'PATCH',
		path: '/projects/{projectId}',
		params: [
			'name?:string',
			'projectId:integer',
			'description?:string',
			'workspaceId?:integer',
		],
		pathParams: ['projectId'],
		riskLevel: 'write',
		description: 'Update a project',
	},
	{
		key: 'tests.update',
		slug: 'BLAZEMETER_UPDATE_TEST',
		api: 'core',
		method: 'PATCH',
		path: '/tests/{test_id}',
		params: ['name?:string', 'test_id:integer', 'configuration?:object'],
		pathParams: ['test_id'],
		riskLevel: 'write',
		description: 'Update a test configuration',
	},
	{
		key: 'assets.update',
		slug: 'BLAZEMETER_UPDATE_WORKSPACES_ASSETS',
		api: 'asset',
		method: 'PUT',
		path: '/workspaces/{workspaceId}/assets/{assetId}',
		params: [
			'data?:object',
			'name?:string',
			'type?:string',
			'assetId:string',
			'metadata?:object',
			'packageId?:string',
			'displayName?:string',
			'workspaceId:integer',
			'dependencies?:object',
		],
		pathParams: ['workspaceId', 'assetId'],
		riskLevel: 'write',
		description: 'Update a workspace asset',
	},
	{
		key: 'packages.update',
		slug: 'BLAZEMETER_UPDATE_WORKSPACES_PACKAGES',
		api: 'asset',
		method: 'PUT',
		path: '/workspaces/{wsId}/packages/{pId}',
		params: [
			'pId:string',
			'name:string',
			'wsId:integer',
			'version?:string',
			'displayName?:string',
			'dependencies?:object',
		],
		pathParams: ['wsId', 'pId'],
		riskLevel: 'write',
		description: 'Update a workspace package',
	},
	{
		key: 'packages.updateDependencies',
		slug: 'BLAZEMETER_UPDATE_WORKSPACES_PACKAGES_DEPENDENCIES',
		api: 'asset',
		method: 'PUT',
		path: '/workspaces/{wsId}/packages/{pId}/dependencies',
		params: ['pId:string', 'wsId:integer', 'dependencies:array'],
		pathParams: ['wsId', 'pId'],
		riskLevel: 'write',
		description: 'Replace package dependencies',
	},
	{
		key: 'serviceMockTemplates.update',
		slug: 'BLAZEMETER_UPDATE_WORKSPACES_SERVICE_MOCK_TEMPLATES',
		api: 'mock',
		method: 'PUT',
		path: '/workspaces/{workspaceId}/service-mock-templates/{templateId}',
		params: [
			'name?:string',
			'thinkTime?:integer',
			'templateId:integer',
			'description?:string',
			'workspaceId:integer',
			'liveSystemHost?:string',
			'liveSystemPort?:integer',
			'endpointPreference?:string',
			'noMatchingRequestPreference?:string',
		],
		pathParams: ['workspaceId', 'templateId'],
		riskLevel: 'write',
		description: 'Update a virtual-service template',
	},
	{
		key: 'workspaces.updateUser',
		slug: 'BLAZEMETER_UPDATE_WORKSPACE_USER',
		api: 'core',
		method: 'PATCH',
		path: '/workspaces/{workspaceId}/users/{userId}',
		params: [
			'roles:array',
			'userId:integer',
			'enabled:boolean',
			'workspaceId:integer',
		],
		pathParams: ['workspaceId', 'userId'],
		riskLevel: 'write',
		description: 'Update a workspace user role and enabled status',
	},
	{
		key: 'assetDependencies.updateForAsset',
		slug: 'BLAZEMETER_UPDATE_WORKSPACES_ASSETS_DEPENDENCIES',
		api: 'asset',
		method: 'PUT',
		path: '/workspaces/{wsId}/assets/{aId}/dependencies',
		params: ['aId:string', 'wsId:integer', 'dependencies:array'],
		pathParams: ['wsId', 'aId'],
		riskLevel: 'write',
		description: 'Replace dependencies for an asset',
	},
	{
		key: 'tests.uploadFile',
		slug: 'BLAZEMETER_UPLOAD_TEST_FILES',
		api: 'core',
		method: 'POST',
		path: '/tests/{testId}/files',
		params: ['file?:object', 'testId:integer', 'fileContent?:object'],
		pathParams: ['testId'],
		multipart: true,
		riskLevel: 'write',
		description: 'Upload a script, data file, or configuration to a test',
	},
	{
		key: 'assets.uploadData',
		slug: 'BLAZEMETER_UPLOAD_WORKSPACES_ASSETS_DATA',
		api: 'asset',
		method: 'POST',
		path: '/workspaces/{wsId}/assets/{assetId}/data',
		params: [
			'file?:object',
			'wsId:integer',
			'assetId:string',
			'fileContent?:object',
		],
		pathParams: ['wsId', 'assetId'],
		multipart: true,
		riskLevel: 'write',
		description: 'Upload data content to an asset',
	},
	{
		key: 'tests.validate',
		slug: 'BLAZEMETER_VALIDATE_TEST',
		api: 'core',
		method: 'POST',
		path: '/tests/{testId}/validate',
		params: ['testId:integer'],
		pathParams: ['testId'],
		riskLevel: 'write',
		description: 'Start validation for a test configuration',
	},
	{
		key: 'testData.validateModel',
		slug: 'BLAZEMETER_VALIDATE_WORKSPACES_ASSETS',
		api: 'tdm',
		method: 'POST',
		path: '/workspaces/{workspace_id}/datamodels/validate',
		params: ['workspace_id:integer', 'data_model_id:string'],
		pathParams: ['workspace_id'],
		riskLevel: 'write',
		description: 'Validate a workspace data model',
	},
] as const satisfies readonly BlazemeterOperationDefinition[];

export type BlazemeterOperation = (typeof BLAZEMETER_OPERATIONS)[number];
export type BlazemeterOperationKey = BlazemeterOperation['key'];
export type BlazemeterCatalogSlug = BlazemeterOperation['slug'];

export type BlazemeterEndpointInput = Record<string, unknown> & {
	body?: Record<string, unknown>;
	query?: Record<string, unknown>;
};

export type BlazemeterEndpoint = CorsairEndpoint<
	BlazemeterContext,
	BlazemeterEndpointInput,
	unknown
>;

const definitionByKey = new Map(
	BLAZEMETER_OPERATIONS.map((definition) => [definition.key, definition]),
);

export function getBlazemeterOperation(
	key: BlazemeterOperationKey,
): BlazemeterOperation {
	const definition = definitionByKey.get(key);
	if (!definition) throw new Error(`[blazemeter] missing operation: ${key}`);
	return definition as BlazemeterOperation;
}

function requiredPathPart(value: unknown, name: string): string {
	if (value === undefined || value === null || value === '') {
		throw new Error(`[blazemeter] missing required path parameter: ${name}`);
	}
	return encodeURIComponent(String(value));
}

export function resolveBlazemeterPath(
	definition: BlazemeterOperationDefinition,
	input: BlazemeterEndpointInput,
): string {
	const allowed = new Set(definition.pathParams ?? []);
	return definition.path.replace(/\{([^{}]+)\}/g, (_match, name: string) => {
		if (!allowed.has(name)) {
			throw new Error(
				`[blazemeter] unmapped path placeholder ${name} in ${definition.key}`,
			);
		}
		return requiredPathPart(input[name], name);
	});
}

const CONTROL_FIELDS = new Set(['body', 'query', 'file', 'fileContent']);

export function buildBlazemeterQuery(
	definition: BlazemeterOperationDefinition,
	input: BlazemeterEndpointInput,
): Record<string, unknown> | undefined {
	const query: Record<string, unknown> = { ...(input.query ?? {}) };
	const pathFields = new Set(definition.pathParams ?? []);
	const fields =
		definition.queryParams ??
		(definition.method === 'GET'
			? definition.params.map(
					(token) => token.split(':')[0]?.replace(/\?$/, '') ?? '',
				)
			: []);
	for (const field of fields) {
		if (!field || pathFields.has(field)) continue;
		if (input[field] !== undefined) query[field] = input[field];
	}
	return Object.keys(query).length > 0 ? query : undefined;
}

export function buildBlazemeterBody(
	definition: BlazemeterOperationDefinition,
	input: BlazemeterEndpointInput,
): Record<string, unknown> | undefined {
	if (input.body) return input.body;
	const excluded = new Set([
		...(definition.pathParams ?? []),
		...(definition.queryParams ?? []),
		...CONTROL_FIELDS,
	]);
	const body = Object.fromEntries(
		Object.entries(input).filter(
			([name, value]) => !excluded.has(name) && value !== undefined,
		),
	);
	return Object.keys(body).length > 0 ? body : undefined;
}

function fileFromInput(input: BlazemeterEndpointInput): unknown {
	const direct = input.file;
	if (direct instanceof Blob) return direct;
	const candidate = (
		input.fileContent && typeof input.fileContent === 'object'
			? input.fileContent
			: direct && typeof direct === 'object'
				? direct
				: undefined
	) as Record<string, unknown> | undefined;
	if (!candidate) return direct;
	if (typeof candidate.content !== 'string') return direct;
	const contentType =
		typeof candidate.contentType === 'string'
			? candidate.contentType
			: typeof candidate.mimetype === 'string'
				? candidate.mimetype
				: 'application/octet-stream';
	return new Blob([Buffer.from(candidate.content, 'base64')], {
		type: contentType,
	});
}

export function buildBlazemeterFormData(
	definition: BlazemeterOperationDefinition,
	input: BlazemeterEndpointInput,
): Record<string, unknown> | undefined {
	if (!definition.multipart) return undefined;
	const form = buildBlazemeterBody(definition, input) ?? {};
	const file = fileFromInput(input);
	if (file !== undefined) form.file = file;
	return Object.keys(form).length > 0 ? form : undefined;
}

export async function executeBlazemeterOperation(
	ctx: BlazemeterContext,
	input: BlazemeterEndpointInput,
	definition: BlazemeterOperationDefinition,
): Promise<unknown> {
	let status: 'completed' | 'failed' = 'completed';
	try {
		const response = await makeBlazemeterRequest(
			resolveBlazemeterPath(definition, input),
			ctx.key,
			{
				api: definition.api,
				method: definition.method,
				body: definition.multipart
					? undefined
					: buildBlazemeterBody(definition, input),
				formData: buildBlazemeterFormData(definition, input),
				query: buildBlazemeterQuery(definition, input),
				idempotent: definition.riskLevel === 'read',
			},
		);
		await persistBlazemeterResult(
			ctx.db as Parameters<typeof persistBlazemeterResult>[0],
			definition.key,
			input,
			response,
		);
		return response;
	} catch (error) {
		status = 'failed';
		throw error;
	} finally {
		await logEventFromContext(
			ctx,
			`blazemeter.${definition.key}`,
			{ method: definition.method, path: definition.path },
			status,
		).catch(() => undefined);
	}
}
