import type { WebflowOperation } from '../endpoints/operation-types';

export const collectionItemsOperations = [
	{
		key: 'listCollectionItems',
		group: 'collectionItems',
		name: 'listCollectionItems',
		method: 'GET',
		path: '/collections/{collection_id}/items',
		pathParams: ['collection_id'],
		riskLevel: 'read',
		description: 'List items in a collection with pagination and filtering',
	},
	{
		key: 'getCollectionItem',
		group: 'collectionItems',
		name: 'getCollectionItem',
		method: 'GET',
		path: '/collections/{collection_id}/items/{item_id}',
		pathParams: ['collection_id', 'item_id'],
		riskLevel: 'read',
		description: 'Get a single staged collection item by id',
	},
	{
		key: 'createCollectionItem',
		group: 'collectionItems',
		name: 'createCollectionItem',
		method: 'POST',
		path: '/collections/{collection_id}/items',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description:
			'Create a staged item in a collection. Field data keys must use the collection schema field slugs',
	},
	{
		key: 'createBulkCollectionItems',
		group: 'collectionItems',
		name: 'createBulkCollectionItems',
		method: 'POST',
		path: '/collections/{collection_id}/items/bulk',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description:
			'Create up to 100 collection items in a single request across multiple locales',
	},
	{
		key: 'updateCollectionItem',
		group: 'collectionItems',
		name: 'updateCollectionItem',
		method: 'PATCH',
		path: '/collections/{collection_id}/items/{item_id}',
		pathParams: ['collection_id', 'item_id'],
		riskLevel: 'write',
		description:
			"Update a staged collection item's field values, draft status, or archive status",
	},
	{
		key: 'updateCollectionItemLegacy',
		group: 'collectionItems',
		name: 'updateCollectionItemLegacy',
		method: 'PATCH',
		path: '/collections/{collection_id}/items',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description:
			'Deprecated: update staged collection items via the bulk items endpoint. Use updateCollectionItem instead',
	},
	{
		key: 'deleteCollectionItem',
		group: 'collectionItems',
		name: 'deleteCollectionItem',
		method: 'DELETE',
		path: '/collections/{collection_id}/items/{item_id}',
		pathParams: ['collection_id', 'item_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Permanently delete a single item from a collection',
	},
	{
		key: 'deleteCollectionItems',
		group: 'collectionItems',
		name: 'deleteCollectionItems',
		method: 'DELETE',
		path: '/collections/{collection_id}/items',
		pathParams: ['collection_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete multiple collection items in a single request',
	},
	{
		key: 'publishCollectionItems',
		group: 'collectionItems',
		name: 'publishCollectionItems',
		method: 'POST',
		path: '/collections/{collection_id}/items/publish',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description: 'Publish staged collection items to the live site',
	},
	{
		key: 'getLiveCollectionItem',
		group: 'collectionItems',
		name: 'getLiveCollectionItem',
		method: 'GET',
		path: '/collections/{collection_id}/items/{item_id}/live',
		pathParams: ['collection_id', 'item_id'],
		riskLevel: 'read',
		description: 'Get the published version of a collection item',
	},
	{
		key: 'createLiveCollectionItem',
		group: 'collectionItems',
		name: 'createLiveCollectionItem',
		method: 'POST',
		path: '/collections/{collection_id}/items/live',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description:
			'Create an item published immediately to the live site, bypassing the staged workflow',
	},
	{
		key: 'updateLiveCollectionItem',
		group: 'collectionItems',
		name: 'updateLiveCollectionItem',
		method: 'PATCH',
		path: '/collections/{collection_id}/items/{item_id}/live',
		pathParams: ['collection_id', 'item_id'],
		riskLevel: 'write',
		description:
			'Update a live collection item, publishing changes immediately to the production site',
	},
	{
		key: 'updateLiveCollectionItems',
		group: 'collectionItems',
		name: 'updateLiveCollectionItems',
		method: 'PATCH',
		path: '/collections/{collection_id}/items/live',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description: 'Update up to 100 published items in a collection',
	},
	{
		key: 'unpublishLiveCollectionItem',
		group: 'collectionItems',
		name: 'unpublishLiveCollectionItem',
		method: 'DELETE',
		path: '/collections/{collection_id}/items/{item_id}/live',
		pathParams: ['collection_id', 'item_id'],
		riskLevel: 'write',
		description:
			'Unpublish a live item and revert it to draft status. The item stays in the collection',
	},
	{
		key: 'unpublishLiveCollectionItems',
		group: 'collectionItems',
		name: 'unpublishLiveCollectionItems',
		method: 'DELETE',
		path: '/collections/{collection_id}/items/live',
		pathParams: ['collection_id'],
		riskLevel: 'write',
		description:
			'Unpublish up to 100 live items and set them to draft. Items stay in the collection',
	},
] as const satisfies readonly WebflowOperation[];
