import type {
	AuthTypes,
	BindEndpoints,
	CorsairEndpoint,
	CorsairErrorHandler,
	CorsairPlugin,
	CorsairPluginContext,
	KeyBuilderContext,
	PickAuth,
	PluginAuthConfig,
	PluginPermissionsConfig,
	RequiredPluginEndpointMeta,
	RequiredPluginEndpointSchemas,
} from 'corsair/core';
import { AuthMissingError } from 'corsair/core';
import { Detect, Text } from './endpoints';
import type {
	WinstonaiEndpointInputs,
	WinstonaiEndpointOutputs,
} from './endpoints/types';
import {
	WinstonaiEndpointInputSchemas,
	WinstonaiEndpointOutputSchemas,
} from './endpoints/types';
import { errorHandlers } from './error-handlers';
import { WinstonaiSchema } from './schema';

export type WinstonaiPluginOptions = {
	authType?: PickAuth<'api_key'>;
	key?: string;
	hooks?: InternalWinstonaiPlugin['hooks'];
	errorHandlers?: CorsairErrorHandler;
	permissions?: PluginPermissionsConfig<typeof winstonaiEndpointsNested>;
};

export type WinstonaiContext = CorsairPluginContext<
	typeof WinstonaiSchema,
	WinstonaiPluginOptions
>;

export type WinstonaiKeyBuilderContext =
	KeyBuilderContext<WinstonaiPluginOptions>;

export type WinstonaiBoundEndpoints = BindEndpoints<
	typeof winstonaiEndpointsNested
>;

type WinstonaiEndpoint<K extends keyof WinstonaiEndpointOutputs> =
	CorsairEndpoint<
		WinstonaiContext,
		WinstonaiEndpointInputs[K],
		WinstonaiEndpointOutputs[K]
	>;

export type WinstonaiEndpoints = {
	detectAiText: WinstonaiEndpoint<'detectAiText'>;
	detectPlagiarism: WinstonaiEndpoint<'detectPlagiarism'>;
	detectAiImage: WinstonaiEndpoint<'detectAiImage'>;
	textCompare: WinstonaiEndpoint<'textCompare'>;
};

const winstonaiEndpointsNested = {
	detect: {
		aiText: Detect.aiText,
		plagiarism: Detect.plagiarism,
		aiImage: Detect.aiImage,
	},
	text: {
		compare: Text.compare,
	},
} as const;

export const winstonaiEndpointSchemas = {
	'detect.aiText': {
		input: WinstonaiEndpointInputSchemas.detectAiText,
		output: WinstonaiEndpointOutputSchemas.detectAiText,
	},
	'detect.plagiarism': {
		input: WinstonaiEndpointInputSchemas.detectPlagiarism,
		output: WinstonaiEndpointOutputSchemas.detectPlagiarism,
	},
	'detect.aiImage': {
		input: WinstonaiEndpointInputSchemas.detectAiImage,
		output: WinstonaiEndpointOutputSchemas.detectAiImage,
	},
	'text.compare': {
		input: WinstonaiEndpointInputSchemas.textCompare,
		output: WinstonaiEndpointOutputSchemas.textCompare,
	},
} as const satisfies RequiredPluginEndpointSchemas<
	typeof winstonaiEndpointsNested
>;

const defaultAuthType: AuthTypes = 'api_key' as const;

const winstonaiEndpointMeta = {
	'detect.aiText': {
		riskLevel: 'read',
		description:
			'Score whether text, a public file, or a website was written by a human or generated by AI',
	},
	'detect.plagiarism': {
		riskLevel: 'read',
		description:
			'Scan text, a public file, or a website for matching sources on the web',
	},
	'detect.aiImage': {
		riskLevel: 'read',
		description:
			'Score whether a public image URL was created by a human or generated by AI',
	},
	'text.compare': {
		riskLevel: 'read',
		description: 'Compare two texts and return similarity scores',
	},
} as const satisfies RequiredPluginEndpointMeta<
	typeof winstonaiEndpointsNested
>;

export const winstonaiAuthConfig = {
	api_key: {},
} as const satisfies PluginAuthConfig;

export type BaseWinstonaiPlugin<T extends WinstonaiPluginOptions> =
	CorsairPlugin<
		'winstonai',
		typeof WinstonaiSchema,
		typeof winstonaiEndpointsNested,
		{},
		T,
		typeof defaultAuthType
	>;

export type InternalWinstonaiPlugin =
	BaseWinstonaiPlugin<WinstonaiPluginOptions>;

export type ExternalWinstonaiPlugin<T extends WinstonaiPluginOptions> =
	BaseWinstonaiPlugin<T>;

export function winstonai<const T extends WinstonaiPluginOptions>(
	incomingOptions: WinstonaiPluginOptions & T = {} as WinstonaiPluginOptions &
		T,
): ExternalWinstonaiPlugin<T> {
	const options = {
		...incomingOptions,
		authType: incomingOptions.authType ?? defaultAuthType,
	};
	return {
		id: 'winstonai',
		authConfig: winstonaiAuthConfig,
		schema: WinstonaiSchema,
		options,
		hooks: options.hooks,
		endpoints: winstonaiEndpointsNested,
		endpointMeta: winstonaiEndpointMeta,
		endpointSchemas: winstonaiEndpointSchemas,
		errorHandlers: (() => {
			const { DEFAULT: defaultHandler, ...specificDefaults } = errorHandlers;
			return {
				...specificDefaults,
				...(options.errorHandlers || {}),
				DEFAULT: options.errorHandlers?.DEFAULT || defaultHandler,
			};
		})(),
		keyBuilder: async (ctx: WinstonaiKeyBuilderContext, source) => {
			if (source === 'endpoint' && options.key) {
				if (!options.key.trim()) {
					throw new AuthMissingError('winstonai', 'api_key');
				}
				return options.key;
			}

			if (source === 'endpoint' && ctx.authType === 'api_key') {
				const res = await ctx.keys.get_api_key();
				if (!res?.trim()) {
					throw new AuthMissingError('winstonai', 'api_key');
				}
				return res;
			}

			throw new AuthMissingError('winstonai', 'api_key');
		},
	} satisfies InternalWinstonaiPlugin;
}

export type {
	DetectAiImageInput,
	DetectAiImageResponse,
	DetectAiTextInput,
	DetectAiTextResponse,
	DetectPlagiarismInput,
	DetectPlagiarismResponse,
	TextCompareInput,
	TextCompareResponse,
	WinstonaiEndpointInputs,
	WinstonaiEndpointOutputs,
} from './endpoints/types';
