/**
 * The documented contract for every operation, transcribed from
 * https://api-ninjas.com/api on 2026-08-15.
 *
 * This exists so `schema.test.ts` can check the zod schemas against the
 * provider's documentation instead of against themselves: every documented
 * parameter has to appear in the input schema, every documented response field
 * has to appear in the output schema, and the version prefix and method have to
 * match the ones the endpoints call.
 *
 * `combination: true` marks the endpoints the documentation describes as a
 * choice of parameter combinations (weather by coordinates or by city, for
 * example). Those parameters are all optional in the input schema, because only
 * the provider can validate which combination was supplied.
 *
 * Two endpoints have no documentation page - sp500 and airlines - and are absent from both the sitemap and the API directory. Their parameters were confirmed one at a time against live calls, and `documented` is null for them.
 */
export type DocumentedParameter = {
	name: string;
	/** What the documentation's parameter table says. */
	required: boolean;
	premium: boolean;
	/**
	 * Whether the provider actually rejects the call when this parameter is
	 * missing, probed one parameter at a time on 2026-08-15. `null` where the
	 * documentation does not call it required, so it was never probed.
	 *
	 * Three parameters are documented as required and are not enforced: the QR
	 * code `format` (which defaults to PNG), and the car endpoint's `make` and
	 * `trim` (any one filter is enough). The input schemas follow the provider
	 * rather than the table, because a schema that demanded them would reject
	 * calls the API answers.
	 */
	enforced: boolean | null;
};

export type DocumentedOperation = {
	catalogOperation: string;
	path: string;
	version: string;
	endpoint: string;
	method: string;
	combination: boolean;
	documented: string | null;
	params: DocumentedParameter[];
	responseFields: string[];
};

export const DOCUMENTED_OPERATIONS: Record<string, DocumentedOperation> = {
	locationGeocode: {
		catalogOperation: 'GET_GEOCODING',
		path: 'location.geocode',
		version: 'v1',
		endpoint: 'geocoding',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/geocoding',
		params: [
			{ name: 'city', required: true, premium: false, enforced: true },
			{ name: 'state', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
			{ name: 'zipcode', required: false, premium: false, enforced: null },
		],
		responseFields: ['name', 'latitude', 'longitude', 'country', 'state'],
	},
	locationReverseGeocode: {
		catalogOperation: 'GET_REVERSE_GEOCODING',
		path: 'location.reverseGeocode',
		version: 'v1',
		endpoint: 'reversegeocoding',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/reversegeocoding',
		params: [
			{ name: 'lat', required: true, premium: false, enforced: true },
			{ name: 'lon', required: true, premium: false, enforced: true },
		],
		responseFields: ['name', 'country', 'state'],
	},
	locationCities: {
		catalogOperation: 'GET_CITY',
		path: 'location.cities',
		version: 'v1',
		endpoint: 'city',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/city',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
			{ name: 'min_lat', required: false, premium: false, enforced: null },
			{ name: 'max_lat', required: false, premium: false, enforced: null },
			{ name: 'min_lon', required: false, premium: false, enforced: null },
			{ name: 'max_lon', required: false, premium: false, enforced: null },
			{
				name: 'min_population',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_population',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'name',
			'latitude',
			'longitude',
			'country',
			'population',
			'is_capital',
		],
	},
	locationCountry: {
		catalogOperation: 'GET_COUNTRY_INFO',
		path: 'location.country',
		version: 'v1',
		endpoint: 'country',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/country',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'currency', required: false, premium: false, enforced: null },
			{ name: 'min_gdp', required: false, premium: false, enforced: null },
			{ name: 'max_gdp', required: false, premium: false, enforced: null },
			{
				name: 'min_population',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_population',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'min_area', required: false, premium: false, enforced: null },
			{ name: 'max_area', required: false, premium: false, enforced: null },
			{
				name: 'min_unemployment',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_unemployment',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_gdp_growth',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_gdp_growth',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_infant_mortality',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_infant_mortality',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_fertility',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_fertility',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_urban_pop_rate',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_urban_pop_rate',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'limit', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'name',
			'iso2',
			'capital',
			'region',
			'currency',
			'gdp',
			'gdp_per_capita',
			'gdp_growth',
			'population',
			'pop_density',
			'pop_growth',
			'surface_area',
			'urban_population',
			'urban_population_growth',
			'unemployment',
			'fertility',
			'infant_mortality',
			'life_expectancy_male',
			'life_expectancy_female',
			'sex_ratio',
			'employment_services',
			'employment_industry',
			'employment_agriculture',
			'imports',
			'exports',
			'co2_emissions',
			'forested_area',
			'tourists',
			'homicide_rate',
			'threatened_species',
			'internet_users',
			'refugees',
			'primary_school_enrollment_female',
			'primary_school_enrollment_male',
			'secondary_school_enrollment_female',
			'secondary_school_enrollment_male',
			'post_secondary_enrollment_female',
			'post_secondary_enrollment_male',
			'telephone_country_codes',
		],
	},
	locationCounty: {
		catalogOperation: 'GET_COUNTY',
		path: 'location.county',
		version: 'v1',
		endpoint: 'county',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/county',
		params: [
			{ name: 'county', required: false, premium: false, enforced: null },
			{ name: 'zipcode', required: false, premium: false, enforced: null },
			{ name: 'state', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'county_name',
			'county_fips',
			'state_code',
			'state_name',
			'latitude',
			'longitude',
			'timezone',
			'zip_codes',
			'population',
			'median_age',
		],
	},
	locationZipCode: {
		catalogOperation: 'GET_ZIPCODE',
		path: 'location.zipCode',
		version: 'v1',
		endpoint: 'zipcode',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/zipcode',
		params: [
			{ name: 'zip', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'state', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'zip_code',
			'valid',
			'city',
			'state',
			'county',
			'timezone',
			'area_codes',
			'country',
			'lat',
			'lon',
		],
	},
	locationPostalCode: {
		catalogOperation: 'GET_POSTAL_CODE',
		path: 'location.postalCode',
		version: 'v1',
		endpoint: 'postalcode',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/postalcode',
		params: [
			{ name: 'postal_code', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'province', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'city',
			'province',
			'postal_code',
			'area_code',
			'timezone',
			'lat',
			'lon',
		],
	},
	locationUniversities: {
		catalogOperation: 'GET_UNIVERSITY',
		path: 'location.universities',
		version: 'v1',
		endpoint: 'university',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/university',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'state', required: false, premium: true, enforced: null },
			{
				name: 'min_faculty_ratio',
				required: false,
				premium: true,
				enforced: null,
			},
			{
				name: 'max_faculty_ratio',
				required: false,
				premium: true,
				enforced: null,
			},
			{ name: 'min_enrolled', required: false, premium: true, enforced: null },
			{ name: 'max_enrolled', required: false, premium: true, enforced: null },
			{ name: 'min_tuition', required: false, premium: true, enforced: null },
			{ name: 'max_tuition', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'name',
			'degree_types',
			'address',
			'city',
			'state',
			'postal_code',
			'country',
			'county',
			'timezone',
			'latitude',
			'longitude',
			'phone',
			'email',
			'website',
			'institution_type',
			'years',
			'enrollment',
			'student_faculty_ratio',
			'tuition',
		],
	},
	locationHospitals: {
		catalogOperation: 'GET_HOSPITALS',
		path: 'location.hospitals',
		version: 'v1',
		endpoint: 'hospitals',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/hospitals',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'state', required: false, premium: false, enforced: null },
			{ name: 'zipcode', required: false, premium: false, enforced: null },
			{ name: 'county', required: false, premium: false, enforced: null },
			{ name: 'min_latitude', required: false, premium: false, enforced: null },
			{ name: 'max_latitude', required: false, premium: false, enforced: null },
			{
				name: 'min_longitude',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_longitude',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'name',
			'care_type',
			'address, city, state, zipcode',
			'county',
			'location_area_code',
			'fips_code',
			'timezone',
			'latitude, longitude',
			'phone_number',
			'website',
			'ownership',
			'bedcount',
		],
	},
	locationEvChargers: {
		catalogOperation: 'FIND_EV_CHARGING_STATIONS',
		path: 'location.evChargers',
		version: 'v1',
		endpoint: 'evcharger',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/evcharger',
		params: [
			{ name: 'lat', required: true, premium: false, enforced: true },
			{ name: 'lon', required: true, premium: false, enforced: true },
			{ name: 'distance', required: false, premium: false, enforced: null },
			{ name: 'level', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'is_active',
			'name',
			'address',
			'city',
			'region',
			'country',
			'latitude, longitude',
			'connections',
			'type_official',
			'level',
			'num_connectors',
		],
	},
	locationWeather: {
		catalogOperation: 'GET_WEATHER',
		path: 'location.weather',
		version: 'v1',
		endpoint: 'weather',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: true,
		documented: 'https://api-ninjas.com/api/weather',
		params: [
			{ name: 'lat', required: false, premium: false, enforced: null },
			{ name: 'lon', required: false, premium: false, enforced: null },
			{ name: 'zip', required: false, premium: true, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'state', required: false, premium: true, enforced: null },
			{ name: 'country', required: false, premium: true, enforced: null },
		],
		responseFields: [],
	},
	locationWeatherForecast: {
		catalogOperation: 'GET_WEATHER_FORECAST',
		path: 'location.weatherForecast',
		version: 'v1',
		endpoint: 'weatherforecast',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: true,
		documented: 'https://api-ninjas.com/api/weather',
		params: [
			{ name: 'lat', required: true, premium: false, enforced: true },
			{ name: 'lon', required: true, premium: false, enforced: true },
			{ name: 'zip', required: true, premium: true, enforced: null },
			{ name: 'city', required: true, premium: true, enforced: null },
			{ name: 'state', required: false, premium: true, enforced: null },
			{ name: 'country', required: false, premium: true, enforced: null },
		],
		responseFields: [],
	},
	locationAirQuality: {
		catalogOperation: 'GET_AIR_QUALITY',
		path: 'location.airQuality',
		version: 'v1',
		endpoint: 'airquality',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/airquality',
		params: [
			{ name: 'lat', required: false, premium: false, enforced: null },
			{ name: 'lon', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'state', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
		],
		responseFields: ['overall_aqi', 'CO', 'NO2', 'O3', 'SO2', 'PM2.5', 'PM10'],
	},
	calendarTimezone: {
		catalogOperation: 'GET_TIMEZONE',
		path: 'calendar.timezone',
		version: 'v1',
		endpoint: 'timezone',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/timezone',
		params: [
			{ name: 'timezone', required: false, premium: false, enforced: null },
			{ name: 'lat', required: false, premium: true, enforced: null },
			{ name: 'lon', required: false, premium: true, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'state', required: false, premium: true, enforced: null },
			{ name: 'country', required: false, premium: true, enforced: null },
		],
		responseFields: ['timezone', 'utc_offset', 'local_time', 'city'],
	},
	calendarWorldTime: {
		catalogOperation: 'GET_WORLDTIME',
		path: 'calendar.worldTime',
		version: 'v1',
		endpoint: 'worldtime',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/worldtime',
		params: [
			{ name: 'timezone', required: false, premium: false, enforced: null },
			{ name: 'lat', required: false, premium: true, enforced: null },
			{ name: 'lon', required: false, premium: true, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'state', required: false, premium: true, enforced: null },
			{ name: 'country', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'timezone',
			'datetime',
			'date',
			'year',
			'month',
			'day',
			'hour',
			'minute',
			'second',
			'day_of_week',
		],
	},
	calendarHolidays: {
		catalogOperation: 'GET_HOLIDAYS',
		path: 'calendar.holidays',
		version: 'v2',
		endpoint: 'holidays',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/holidays',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'year', required: false, premium: false, enforced: null },
			{ name: 'type', required: false, premium: false, enforced: null },
		],
		responseFields: ['country', 'iso', 'year', 'date', 'day', 'name', 'type'],
	},
	calendarPublicHolidays: {
		catalogOperation: 'GET_PUBLIC_HOLIDAYS',
		path: 'calendar.publicHolidays',
		version: 'v1',
		endpoint: 'publicholidays',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/publicholidays',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'year', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'name',
			'local_name',
			'date',
			'country',
			'year',
			'regions',
			'federal',
		],
	},
	calendarIsPublicHoliday: {
		catalogOperation: 'CHECK_IS_PUBLIC_HOLIDAY',
		path: 'calendar.isPublicHoliday',
		version: 'v1',
		endpoint: 'ispublicholiday',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/publicholidays',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'date', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'is_public_holiday',
			'public_holiday_name',
			'date',
			'country',
		],
	},
	calendarIsWorkingDay: {
		catalogOperation: 'CHECK_IS_WORKING_DAY',
		path: 'calendar.isWorkingDay',
		version: 'v1',
		endpoint: 'isworkingday',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/workingdays',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'date', required: true, premium: false, enforced: true },
			{ name: 'weekend', required: false, premium: false, enforced: null },
			{
				name: 'public_holidays',
				required: false,
				premium: false,
				enforced: null,
			},
		],
		responseFields: [
			'date',
			'country',
			'day_of_week',
			'is_workday',
			'non_working_reason',
			'public_holiday_name',
		],
	},
	calendarWorkingDays: {
		catalogOperation: 'GET_WORKING_DAYS',
		path: 'calendar.workingDays',
		version: 'v1',
		endpoint: 'workingdays',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/workingdays',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'year', required: false, premium: true, enforced: null },
			{ name: 'month', required: false, premium: false, enforced: null },
			{ name: 'weekend', required: false, premium: false, enforced: null },
			{
				name: 'public_holidays',
				required: false,
				premium: false,
				enforced: null,
			},
		],
		responseFields: [
			'num_working_days',
			'num_non_working_days',
			'working_days',
			'non_working_days',
		],
	},
	internetDomain: {
		catalogOperation: 'CHECK_DOMAIN',
		path: 'internet.domain',
		version: 'v1',
		endpoint: 'domain',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/domain',
		params: [
			{ name: 'domain', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'domain',
			'available',
			'creation_date',
			'expiration_date',
			'age_days',
			'registrar',
			'updated_date',
			'domain_status',
			'has_mx',
			'is_free_email_provider',
			'risky_tld',
			'is_disposable_email_domain',
			'is_custom_domain',
			'mx_provider',
			'is_parked',
			'ip',
			'hosting_provider',
			'country',
		],
	},
	internetDnsRecords: {
		catalogOperation: 'DNS_LOOKUP',
		path: 'internet.dnsRecords',
		version: 'v1',
		endpoint: 'dnslookup',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/dnslookup',
		params: [
			{ name: 'domain', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'record_type',
			'AAAA',
			'CNAME',
			'MX',
			'NS',
			'PTR',
			'SRV',
			'SOA',
			'TXT',
			'CAA',
			'value',
			'priority',
			'mname, rname, serial, refresh, retry, expire, ttl',
		],
	},
	internetMxRecords: {
		catalogOperation: 'GET_MX_RECORDS',
		path: 'internet.mxRecords',
		version: 'v1',
		endpoint: 'mxlookup',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/mxlookup',
		params: [
			{ name: 'domain', required: true, premium: false, enforced: true },
		],
		responseFields: ['priority', 'value'],
	},
	internetWhois: {
		catalogOperation: 'GET_WHOIS',
		path: 'internet.whois',
		version: 'v1',
		endpoint: 'whois',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/whois',
		params: [
			{ name: 'domain', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'domain_name',
			'registrar',
			'registrar_url',
			'whois_server',
			'updated_date',
			'creation_date',
			'expiration_date',
			'name_servers',
			'dnssec',
			'emails',
		],
	},
	internetIpLookup: {
		catalogOperation: 'GET_IP_LOOKUP',
		path: 'internet.ipLookup',
		version: 'v1',
		endpoint: 'iplookup',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/iplookup',
		params: [
			{ name: 'address', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'address',
			'timezone',
			'lat',
			'lon',
			'zip',
			'city',
			'region',
			'region_code',
			'country',
			'country_code',
			'is_valid',
			'isp',
			'is_datacenter',
			'is_hosting',
			'is_tor',
			'is_vpn',
			'is_icloud_relay',
			'is_bogon',
			'is_abuser',
			'threat_level',
			'asn',
			'asn_name',
			'route',
			'abuse_email',
		],
	},
	internetUrlLookup: {
		catalogOperation: 'GET_URL_LOOKUP',
		path: 'internet.urlLookup',
		version: 'v1',
		endpoint: 'urllookup',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/urllookup',
		params: [{ name: 'url', required: true, premium: false, enforced: true }],
		responseFields: [
			'url',
			'country',
			'country_code',
			'region',
			'region_code',
			'city',
			'zip',
			'lat',
			'lon',
			'timezone',
			'isp',
		],
	},
	internetWebpage: {
		catalogOperation: 'EXTRACT_WEBPAGE_CONTENT',
		path: 'internet.webpage',
		version: 'v1',
		endpoint: 'webpage',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/webpage',
		params: [{ name: 'url', required: true, premium: false, enforced: true }],
		responseFields: [
			'url',
			'domain',
			'url_path',
			'url_parameters',
			'page_title',
			'page_description',
			'meta_tags',
			'favicon',
		],
	},
	internetScrape: {
		catalogOperation: 'SCRAPE_WEBSITE',
		path: 'internet.scrape',
		version: 'v1',
		endpoint: 'webscraper',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/webscraper',
		params: [
			{ name: 'url', required: true, premium: false, enforced: true },
			{ name: 'text_only', required: false, premium: false, enforced: null },
			{ name: 'user_agent', required: false, premium: false, enforced: null },
		],
		responseFields: ['data'],
	},
	internetUserAgent: {
		catalogOperation: 'GENERATE_USER_AGENT',
		path: 'internet.userAgent',
		version: 'v1',
		endpoint: 'useragentgenerate',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/useragent',
		params: [
			{ name: 'brand', required: false, premium: false, enforced: null },
			{ name: 'model', required: false, premium: false, enforced: null },
			{ name: 'os', required: false, premium: false, enforced: null },
			{ name: 'browser', required: false, premium: false, enforced: null },
		],
		responseFields: ['user_agent'],
	},
	validationEmail: {
		catalogOperation: 'VALIDATE_EMAIL',
		path: 'validation.email',
		version: 'v1',
		endpoint: 'validateemail',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/validateemail',
		params: [{ name: 'email', required: true, premium: false, enforced: true }],
		responseFields: [
			'is_valid',
			'domain',
			'email',
			'local_part',
			'is_disposable',
			'is_public',
			'main_category',
			'sub_category',
		],
	},
	validationDisposableEmail: {
		catalogOperation: 'DISPOSABLE_EMAIL_CHECKER',
		path: 'validation.disposableEmail',
		version: 'v1',
		endpoint: 'disposableemailchecker',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/disposableemailchecker',
		params: [{ name: 'email', required: true, premium: false, enforced: true }],
		responseFields: ['domain', 'email', 'is_disposable'],
	},
	validationPhone: {
		catalogOperation: 'VALIDATE_PHONE',
		path: 'validation.phone',
		version: 'v1',
		endpoint: 'validatephone',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/validatephone',
		params: [
			{ name: 'number', required: true, premium: false, enforced: true },
			{ name: 'country', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'is_valid',
			'is_formatted_properly',
			'country',
			'location',
			'timezones',
			'format_national',
			'format_international',
			'format_e164',
			'country_code',
			'line_type',
			'is_mobile',
			'format_rfc3966',
			'is_possible',
		],
	},
	validationRoutingNumber: {
		catalogOperation: 'VALIDATE_ROUTING_NUMBER',
		path: 'validation.routingNumber',
		version: 'v1',
		endpoint: 'routingnumber',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/routingnumber',
		params: [
			{
				name: 'routing_number',
				required: true,
				premium: false,
				enforced: true,
			},
		],
		responseFields: [],
	},
	validationIban: {
		catalogOperation: 'IBAN_LOOKUP',
		path: 'validation.iban',
		version: 'v1',
		endpoint: 'iban',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/iban',
		params: [{ name: 'iban', required: true, premium: false, enforced: true }],
		responseFields: [
			'iban',
			'bank_name',
			'bank_address',
			'swift_code',
			'account_number',
			'bank_code',
			'country',
			'checksum',
			'valid',
			'invalid_reason',
			'bban',
		],
	},
	validationBin: {
		catalogOperation: 'BIN_LOOKUP',
		path: 'validation.bin',
		version: 'v2',
		endpoint: 'bin',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/bin',
		params: [{ name: 'bin', required: true, premium: false, enforced: true }],
		responseFields: [
			'bin',
			'brand',
			'type',
			'categories',
			'issuer',
			'country_iso2',
			'country',
			'is_valid',
		],
	},
	validationSwiftCode: {
		catalogOperation: 'GET_SWIFT_CODE',
		path: 'validation.swiftCode',
		version: 'v1',
		endpoint: 'swiftcode',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/swiftcode',
		params: [
			{ name: 'swift', required: false, premium: false, enforced: null },
			{ name: 'bank', required: false, premium: true, enforced: null },
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
			{
				name: 'routing_number',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'swift_code',
			'bank_name',
			'address',
			'city',
			'region',
			'postal_code',
			'country',
			'country_code',
		],
	},
	marketsStockPrice: {
		catalogOperation: 'GET_STOCK_PRICE',
		path: 'markets.stockPrice',
		version: 'v1',
		endpoint: 'stockprice',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/stockprice',
		params: [
			{ name: 'ticker', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'ticker',
			'name',
			'price',
			'exchange',
			'updated',
			'currency',
			'volume',
		],
	},
	marketsTicker: {
		catalogOperation: 'GET_TICKER',
		path: 'markets.ticker',
		version: 'v1',
		endpoint: 'ticker',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/ticker',
		params: [
			{ name: 'ticker', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'name',
			'ticker',
			'chief_executive_officer',
			'address',
			'latest_price',
			'latest_market_cap',
			'latest_dividend',
			'cik',
			'cusip',
			'isin',
			'exchange',
			'website',
			'phone_number',
			'ipo_date',
			'latest_earnings',
			'sector',
			'industry',
			'sic_code',
			'sic_description',
		],
	},
	marketsTickerList: {
		catalogOperation: 'LIST_STOCK_TICKERS',
		path: 'markets.tickerList',
		version: 'v1',
		endpoint: 'stockpricelist',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/stockprice',
		params: [
			{ name: 'offset', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: false, enforced: null },
		],
		responseFields: ['ticker', 'name'],
	},
	marketsStockExchanges: {
		catalogOperation: 'GET_STOCK_EXCHANGE',
		path: 'markets.stockExchanges',
		version: 'v1',
		endpoint: 'stockexchange',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/stockexchange',
		params: [
			{ name: 'mic', required: false, premium: false, enforced: null },
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'mic',
			'name',
			'city',
			'country',
			'iso2',
			'description',
			'address',
			'website',
			'founded',
			'num_listings',
			'market_cap_usd',
			'market_cap',
			'currency',
			'timezone',
			'market_open',
			'market_close',
			'is_market_open',
			'closed_reason',
		],
	},
	marketsSp500: {
		catalogOperation: 'GET_SP500_CONSTITUENTS',
		path: 'markets.sp500',
		version: 'v1',
		endpoint: 'sp500',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: null,
		params: [
			{ name: 'ticker', required: false, premium: false, enforced: null },
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'sector', required: false, premium: false, enforced: null },
			{ name: 'date_added', required: false, premium: false, enforced: null },
		],
		responseFields: [],
	},
	marketsMarketCap: {
		catalogOperation: 'MARKET_CAP',
		path: 'markets.marketCap',
		version: 'v1',
		endpoint: 'marketcap',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/marketcap',
		params: [
			{ name: 'ticker', required: true, premium: false, enforced: true },
		],
		responseFields: ['ticker', 'name', 'market_cap', 'currency', 'updated'],
	},
	marketsEarnings: {
		catalogOperation: 'GET_EARNINGS',
		path: 'markets.earnings',
		version: 'v2',
		endpoint: 'earnings',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/earnings',
		params: [
			{ name: 'ticker', required: false, premium: false, enforced: null },
			{ name: 'cik', required: false, premium: false, enforced: null },
			{ name: 'period', required: false, premium: false, enforced: null },
			{ name: 'year', required: false, premium: false, enforced: null },
			{ name: 'quarter', required: false, premium: false, enforced: null },
			{ name: 'date', required: false, premium: false, enforced: null },
			{ name: 'date_start', required: false, premium: false, enforced: null },
			{ name: 'date_end', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'company_info',
			'income_statement',
			'balance_sheet',
			'cash_flow',
			'filing_info',
		],
	},
	marketsEarningsCalendar: {
		catalogOperation: 'EARNINGS_CALENDAR',
		path: 'markets.earningsCalendar',
		version: 'v1',
		endpoint: 'earningscalendar',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/earningscalendar',
		params: [
			{ name: 'ticker', required: false, premium: false, enforced: null },
			{ name: 'date', required: false, premium: false, enforced: null },
			{ name: 'date_start', required: false, premium: false, enforced: null },
			{ name: 'date_end', required: false, premium: false, enforced: null },
			{ name: 'show_upcoming', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'date',
			'ticker',
			'fiscal_year',
			'fiscal_quarter',
			'earnings_timing',
			'earnings_call_timestamp',
			'actual_revenue',
			'estimated_revenue',
			'revenue_difference',
			'revenue_difference_pct',
			'actual_eps',
			'estimated_eps',
			'eps_difference',
			'eps_difference_pct',
			'report_date_status',
			'date_confirmed',
			'report_datetime',
			'sec_8k_url',
			'eps_beat_miss',
			'revenue_beat_miss',
			'eps_surprise_streak',
			'avg_eps_surprise_pct_4q',
			'eps_sue',
			'last_earnings_move_pct',
			'avg_earnings_move_pct',
			'days_to_next_earnings',
			'next_earnings_date',
			'has_transcript',
			'surprise_history',
		],
	},
	marketsEarningsTranscript: {
		catalogOperation: 'EARNINGS_CALL_TRANSCRIPT',
		path: 'markets.earningsTranscript',
		version: 'v1',
		endpoint: 'earningstranscript',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/earningscalltranscript',
		params: [
			{ name: 'ticker', required: false, premium: false, enforced: null },
			{ name: 'cik', required: false, premium: false, enforced: null },
			{ name: 'year', required: false, premium: false, enforced: null },
			{ name: 'quarter', required: false, premium: false, enforced: null },
			{ name: 'qa_only', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'date',
			'timestamp',
			'ticker',
			'cik',
			'year',
			'quarter',
			'earnings_timing',
			'transcript',
			'participants',
			'summary',
			'guidance',
			'risk_factors',
			'overall_sentiment',
			'overall_sentiment_rationale',
			'transcript_split',
		],
	},
	marketsInsiderTransactions: {
		catalogOperation: 'GET_INSIDER_TRANSACTIONS',
		path: 'markets.insiderTransactions',
		version: 'v1',
		endpoint: 'insidertransactions',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/insidertrading',
		params: [
			{ name: 'ticker', required: false, premium: false, enforced: null },
			{ name: 'cik', required: false, premium: false, enforced: null },
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'form_type', required: false, premium: false, enforced: null },
			{
				name: 'transaction_type',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'transaction_code',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'transaction_date',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_transaction_date',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_transaction_date',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'insider_type', required: false, premium: false, enforced: null },
			{
				name: 'min_transaction_value',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_transaction_value',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'accession_number',
			'form',
			'filing_date',
			'sec_filing_url',
			'cik',
			'ticker',
			'company_name',
			'insider_name',
			'insider_position',
			'transaction_code',
			'transaction_name',
			'transaction_type',
			'transaction_price',
			'shares',
			'transaction_value',
			'pre_transaction_shares',
			'pre_transaction_shares_value',
			'remaining_shares',
			'remaining_shares_value',
		],
	},
	marketsSecFilings: {
		catalogOperation: 'GET_SEC_FILING',
		path: 'markets.secFilings',
		version: 'v1',
		endpoint: 'sec',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/sec',
		params: [
			{ name: 'ticker', required: true, premium: false, enforced: true },
			{ name: 'filing', required: true, premium: false, enforced: true },
			{ name: 'start', required: false, premium: true, enforced: null },
			{ name: 'end', required: false, premium: true, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
		],
		responseFields: ['ticker', 'filing_date', 'filing_url', 'form_type'],
	},
	marketsEtf: {
		catalogOperation: 'ETF_INFO',
		path: 'markets.etf',
		version: 'v1',
		endpoint: 'etf',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/etf',
		params: [
			{ name: 'ticker', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'etf_ticker',
			'etf_name',
			'isin',
			'cusip',
			'country',
			'domicile',
			'price',
			'expense_ratio',
			'aum',
			'aum_currency',
			'aum_usd',
			'num_holdings',
			'holdings',
		],
	},
	marketsMutualFund: {
		catalogOperation: 'GET_MUTUAL_FUND',
		path: 'markets.mutualFund',
		version: 'v1',
		endpoint: 'mutualfund',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/mutualfund',
		params: [
			{ name: 'ticker', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'fund_ticker',
			'fund_name',
			'isin',
			'cusip',
			'country',
			'expense_ratio',
			'price',
			'aum',
			'holdings',
			'num_holdings',
		],
	},
	marketsCryptoPrice: {
		catalogOperation: 'CRYPTO_PRICE',
		path: 'markets.cryptoPrice',
		version: 'v1',
		endpoint: 'cryptoprice',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/cryptoprice',
		params: [
			{ name: 'symbol', required: true, premium: false, enforced: true },
		],
		responseFields: ['symbol', 'price', 'timestamp'],
	},
	marketsBitcoin: {
		catalogOperation: 'BITCOIN',
		path: 'markets.bitcoin',
		version: 'v1',
		endpoint: 'bitcoin',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/bitcoin',
		params: [],
		responseFields: [
			'price',
			'timestamp',
			'24h_price_change',
			'24h_price_change_percent',
			'24h_high',
			'24h_low',
			'24h_volume',
		],
	},
	marketsCommodityPrice: {
		catalogOperation: 'COMMODITY_PRICE',
		path: 'markets.commodityPrice',
		version: 'v1',
		endpoint: 'commodityprice',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/commodityprice',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'names', required: false, premium: false, enforced: null },
			{ name: 'currency', required: false, premium: false, enforced: null },
			{ name: 'unit', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'exchange',
			'name',
			'price',
			'currency_unit',
			'unit',
			'previous_close',
			'change_24h',
			'change_24h_percent',
			'high_24h',
			'high_52w',
			'updated',
		],
	},
	marketsConvertCurrency: {
		catalogOperation: 'CONVERT_CURRENCY',
		path: 'markets.convertCurrency',
		version: 'v1',
		endpoint: 'convertcurrency',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/convertcurrency',
		params: [
			{ name: 'have', required: true, premium: false, enforced: true },
			{ name: 'want', required: true, premium: false, enforced: true },
			{ name: 'amount', required: true, premium: false, enforced: true },
		],
		responseFields: [
			'old_amount',
			'old_currency',
			'new_amount',
			'new_currency',
			'timestamp',
		],
	},
	marketsExchangeRate: {
		catalogOperation: 'GET_EXCHANGE_RATE',
		path: 'markets.exchangeRate',
		version: 'v1',
		endpoint: 'exchangerate',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/exchangerate',
		params: [{ name: 'pair', required: true, premium: false, enforced: true }],
		responseFields: ['currency_pair', 'exchange_rate', 'timestamp'],
	},
	economicsGdp: {
		catalogOperation: 'GET_GDP',
		path: 'economics.gdp',
		version: 'v1',
		endpoint: 'gdp',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/gdp',
		params: [
			{ name: 'country', required: false, premium: false, enforced: null },
			{ name: 'year', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'country',
			'year',
			'gdp_growth',
			'gdp_nominal',
			'gdp_per_capita_nominal',
			'gdp_ppp',
			'gdp_per_capita_ppp',
			'gdp_ppp_share',
		],
	},
	economicsInflation: {
		catalogOperation: 'INFLATION',
		path: 'economics.inflation',
		version: 'v1',
		endpoint: 'inflation',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/inflation',
		params: [
			{ name: 'type', required: false, premium: false, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'country',
			'country_code',
			'type',
			'period',
			'monthly_rate_pct',
			'yearly_rate_pct',
		],
	},
	economicsUnemployment: {
		catalogOperation: 'GET_UNEMPLOYMENT',
		path: 'economics.unemployment',
		version: 'v1',
		endpoint: 'unemployment',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/unemployment',
		params: [
			{ name: 'country', required: false, premium: false, enforced: null },
			{ name: 'year', required: false, premium: false, enforced: null },
		],
		responseFields: ['country', 'year', 'unemployment_rate'],
	},
	economicsPopulation: {
		catalogOperation: 'GET_POPULATION',
		path: 'economics.population',
		version: 'v1',
		endpoint: 'population',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/population',
		params: [
			{ name: 'country', required: false, premium: false, enforced: null },
			{
				name: 'min_population',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_population',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'country_name',
			'historical_population',
			'population',
			'yearly_change_percentage',
			'yearly_change',
			'migrants',
			'median_age',
			'fertility_rate',
			'density',
			'urban_population_pct',
			'urban_population',
			'percentage_of_world_population',
			'rank',
			'population_forecast',
		],
	},
	economicsInterestRate: {
		catalogOperation: 'INTEREST_RATE',
		path: 'economics.interestRate',
		version: 'v2',
		endpoint: 'interestrate',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/interestrate',
		params: [{ name: 'rate', required: true, premium: false, enforced: true }],
		responseFields: ['rate_name', 'rate_pct', 'last_updated'],
	},
	economicsMortgageRate: {
		catalogOperation: 'MORTGAGE_RATE',
		path: 'economics.mortgageRate',
		version: 'v2',
		endpoint: 'mortgagerate',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/mortgagerate',
		params: [
			{ name: 'date', required: false, premium: true, enforced: null },
			{ name: 'min_date', required: false, premium: true, enforced: null },
			{ name: 'max_date', required: false, premium: true, enforced: null },
		],
		responseFields: ['date', 'frm_30', 'frm_15'],
	},
	economicsMortgageCalculator: {
		catalogOperation: 'CALCULATE_MORTGAGE',
		path: 'economics.mortgageCalculator',
		version: 'v1',
		endpoint: 'mortgagecalculator',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/mortgagecalculator',
		params: [
			{ name: 'loan_amount', required: false, premium: false, enforced: null },
			{ name: 'home_value', required: false, premium: false, enforced: null },
			{ name: 'downpayment', required: false, premium: false, enforced: null },
			{ name: 'interest_rate', required: true, premium: false, enforced: true },
			{
				name: 'duration_years',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'monthly_hoa', required: false, premium: false, enforced: null },
			{
				name: 'annual_property_tax',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'annual_home_insurance',
				required: false,
				premium: false,
				enforced: null,
			},
		],
		responseFields: [
			'monthly_payment',
			'annual_payment',
			'total_interest_paid',
		],
	},
	economicsIncomeTax: {
		catalogOperation: 'GET_INCOME_TAX',
		path: 'economics.incomeTax',
		version: 'v2',
		endpoint: 'incometax',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/incometax',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'year', required: true, premium: false, enforced: true },
			{ name: 'regions', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'country',
			'year',
			'federal',
			'fica',
			'states',
			'provinces',
		],
	},
	economicsIncomeTaxCalculator: {
		catalogOperation: 'INCOME_TAX_CALCULATOR',
		path: 'economics.incomeTaxCalculator',
		version: 'v1',
		endpoint: 'incometaxcalculator',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/incometaxcalculator',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'region', required: true, premium: false, enforced: true },
			{ name: 'income', required: true, premium: false, enforced: true },
			{ name: 'tax_year', required: false, premium: false, enforced: null },
			{ name: 'filing_status', required: true, premium: false, enforced: true },
			{ name: 'deductions', required: false, premium: false, enforced: null },
			{ name: 'credits', required: false, premium: false, enforced: null },
			{
				name: 'self_employed',
				required: false,
				premium: false,
				enforced: null,
			},
		],
		responseFields: [
			'country',
			'region',
			'income',
			'taxable_income',
			'deductions',
			'credits',
			'federal_effective_rate',
			'federal_taxes_owed',
			'fica_social_security',
			'fica_social_security_rate',
			'fica_social_security_cap',
			'fica_medicare',
			'fica_medicare_rate',
			'fica_total',
			'region_effective_rate',
			'region_taxes_owed',
			'total_taxes_owed',
			'income_after_tax',
			'total_effective_tax_rate',
		],
	},
	economicsSalesTax: {
		catalogOperation: 'GET_SALES_TAX',
		path: 'economics.salesTax',
		version: 'v1',
		endpoint: 'salestax',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/salestax',
		params: [
			{ name: 'zip_code', required: false, premium: false, enforced: null },
			{
				name: 'street_address',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'state', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'street_address',
			'zip_code',
			'state_rate',
			'city_rate',
			'county_rate',
			'additional_rate',
			'total_rate',
		],
	},
	economicsSalesTaxCalculator: {
		catalogOperation: 'CALCULATE_SALES_TAX',
		path: 'economics.salesTaxCalculator',
		version: 'v1',
		endpoint: 'salestaxcalculator',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/salestaxcalculator',
		params: [
			{ name: 'amount', required: true, premium: false, enforced: true },
			{ name: 'zip_code', required: false, premium: false, enforced: null },
			{
				name: 'street_address',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'state', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'street_address',
			'zip_code',
			'state_rate',
			'city_rate',
			'county_rate',
			'additional_rate',
			'total_rate',
			'state_tax',
			'city_tax',
			'county_tax',
			'additional_tax',
			'total_tax',
			'total_price',
		],
	},
	economicsPropertyTax: {
		catalogOperation: 'GET_PROPERTY_TAX',
		path: 'economics.propertyTax',
		version: 'v1',
		endpoint: 'propertytax',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/propertytax',
		params: [
			{ name: 'state', required: false, premium: false, enforced: null },
			{ name: 'county', required: false, premium: false, enforced: null },
			{ name: 'city', required: false, premium: false, enforced: null },
			{ name: 'zip', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'state',
			'county',
			'city',
			'zip',
			'property_tax_25th_percentile',
			'property_tax_50th_percentile',
			'property_tax_75th_percentile',
		],
	},
	economicsVatRates: {
		catalogOperation: 'VALIDATE_EU_VAT',
		path: 'economics.vatRates',
		version: 'v1',
		endpoint: 'vat',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/vat',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
			{ name: 'type', required: false, premium: false, enforced: null },
			{ name: 'min_date', required: false, premium: false, enforced: null },
			{ name: 'max_date', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: ['country', 'type', 'rate', 'date', 'category'],
	},
	textSentiment: {
		catalogOperation: 'ANALYZE_SENTIMENT',
		path: 'text.sentiment',
		version: 'v1',
		endpoint: 'sentiment',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/sentiment',
		params: [{ name: 'text', required: true, premium: false, enforced: true }],
		responseFields: ['score', 'text', 'sentiment'],
	},
	textSimilarity: {
		catalogOperation: 'COMPUTE_TEXT_SIMILARITY',
		path: 'text.similarity',
		version: 'v1',
		endpoint: 'textsimilarity',
		method: 'POST',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/textsimilarity',
		params: [
			{ name: 'text_1', required: true, premium: false, enforced: null },
			{ name: 'text_2', required: true, premium: false, enforced: null },
		],
		responseFields: ['similarity'],
	},
	textEmbeddings: {
		catalogOperation: 'GENERATE_TEXT_EMBEDDINGS',
		path: 'text.embeddings',
		version: 'v1',
		endpoint: 'embeddings',
		method: 'POST',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/embeddings',
		params: [{ name: 'text', required: true, premium: false, enforced: null }],
		responseFields: ['embeddings'],
	},
	textLanguage: {
		catalogOperation: 'DETECT_TEXT_LANGUAGE',
		path: 'text.language',
		version: 'v1',
		endpoint: 'textlanguage',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/textlanguage',
		params: [{ name: 'text', required: true, premium: false, enforced: true }],
		responseFields: ['iso', 'language'],
	},
	textSpellCheck: {
		catalogOperation: 'CHECK_SPELLING',
		path: 'text.spellCheck',
		version: 'v1',
		endpoint: 'spellcheck',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/spellcheck',
		params: [{ name: 'text', required: true, premium: false, enforced: true }],
		responseFields: [
			'original',
			'corrected',
			'corrections',
			'index',
			'correction',
			'candidates',
		],
	},
	textProfanityFilter: {
		catalogOperation: 'FILTER_PROFANITY',
		path: 'text.profanityFilter',
		version: 'v1',
		endpoint: 'profanityfilter',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/profanityfilter',
		params: [{ name: 'text', required: true, premium: false, enforced: true }],
		responseFields: ['original', 'censored', 'has_profanity'],
	},
	textDictionary: {
		catalogOperation: 'GET_DICTIONARY_DEFINITION',
		path: 'text.dictionary',
		version: 'v1',
		endpoint: 'dictionary',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/dictionary',
		params: [{ name: 'word', required: true, premium: false, enforced: true }],
		responseFields: ['word', 'definition', 'valid'],
	},
	textThesaurus: {
		catalogOperation: 'GET_THESAURUS',
		path: 'text.thesaurus',
		version: 'v1',
		endpoint: 'thesaurus',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/thesaurus',
		params: [{ name: 'word', required: true, premium: false, enforced: true }],
		responseFields: ['word', 'synonyms', 'antonyms'],
	},
	textRhymes: {
		catalogOperation: 'GET_RHYMES',
		path: 'text.rhymes',
		version: 'v1',
		endpoint: 'rhyme',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/rhyme',
		params: [{ name: 'word', required: true, premium: false, enforced: true }],
		responseFields: [],
	},
	textRandomWord: {
		catalogOperation: 'GET_RANDOM_WORD',
		path: 'text.randomWord',
		version: 'v2',
		endpoint: 'randomword',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/randomword',
		params: [
			{ name: 'type', required: false, premium: true, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
		],
		responseFields: [],
	},
	textLoremIpsum: {
		catalogOperation: 'GENERATE_LOREM_IPSUM',
		path: 'text.loremIpsum',
		version: 'v1',
		endpoint: 'loremipsum',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/loremipsum',
		params: [
			{ name: 'max_length', required: false, premium: false, enforced: null },
			{ name: 'paragraphs', required: false, premium: false, enforced: null },
			{
				name: 'start_with_lorem_ipsum',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'random', required: false, premium: false, enforced: null },
		],
		responseFields: ['text'],
	},
	utilityQrCode: {
		catalogOperation: 'GENERATE_QR_CODE',
		path: 'utility.qrCode',
		version: 'v1',
		endpoint: 'qrcode',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/qrcode',
		params: [
			{ name: 'data', required: true, premium: false, enforced: true },
			{ name: 'format', required: true, premium: false, enforced: false },
			{ name: 'size', required: false, premium: false, enforced: null },
			{ name: 'fg_color', required: false, premium: false, enforced: null },
			{ name: 'bg_color', required: false, premium: false, enforced: null },
		],
		responseFields: [],
	},
	utilityBarcode: {
		catalogOperation: 'BARCODE_GENERATE',
		path: 'utility.barcode',
		version: 'v1',
		endpoint: 'barcodegenerate',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/barcode',
		params: [
			{ name: 'text', required: true, premium: false, enforced: true },
			{ name: 'type', required: false, premium: false, enforced: null },
			{ name: 'format', required: false, premium: false, enforced: null },
			{ name: 'include_text', required: false, premium: false, enforced: null },
		],
		responseFields: [],
	},
	utilityPassword: {
		catalogOperation: 'GENERATE_PASSWORD',
		path: 'utility.password',
		version: 'v1',
		endpoint: 'passwordgenerator',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/passwordgenerator',
		params: [
			{ name: 'length', required: false, premium: false, enforced: null },
			{
				name: 'exclude_numbers',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'exclude_special_chars',
				required: false,
				premium: false,
				enforced: null,
			},
		],
		responseFields: ['random_password'],
	},
	utilityRandomUser: {
		catalogOperation: 'GENERATE_RANDOM_USER',
		path: 'utility.randomUser',
		version: 'v2',
		endpoint: 'randomuser',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/randomuser',
		params: [
			{ name: 'count', required: false, premium: false, enforced: null },
			{ name: 'gender', required: false, premium: false, enforced: null },
			{ name: 'min_age', required: false, premium: false, enforced: null },
			{ name: 'max_age', required: false, premium: false, enforced: null },
			{ name: 'locale', required: false, premium: false, enforced: null },
			{ name: 'fields', required: false, premium: false, enforced: null },
			{ name: 'exclude', required: false, premium: false, enforced: null },
			{ name: 'seed', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'id',
			'username',
			'password',
			'email',
			'name',
			'first_name',
			'last_name',
			'full_name',
			'prefix',
			'suffix',
			'phone',
			'cell',
			'address',
			'street_address',
			'city',
			'state',
			'postal_code',
			'country',
			'latitude',
			'longitude',
			'timezone',
			'dob',
			'age',
			'gender',
			'job',
			'company',
			'company_email',
			'ssn',
			'credit_card',
			'credit_card_provider',
			'iban',
			'ipv4',
			'ipv6',
			'mac_address',
			'user_agent',
			'url',
			'domain',
			'picture',
			'avatar',
			'uuid',
			'md5',
			'sha1',
			'sha256',
			'locale',
		],
	},
	utilityCounter: {
		catalogOperation: 'GET_COUNTER',
		path: 'utility.counter',
		version: 'v1',
		endpoint: 'counter',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/counter',
		params: [
			{ name: 'id', required: true, premium: false, enforced: true },
			{ name: 'hit', required: false, premium: false, enforced: null },
			{ name: 'value', required: false, premium: false, enforced: null },
		],
		responseFields: ['id', 'value'],
	},
	utilityConvertUnit: {
		catalogOperation: 'CONVERT_UNIT',
		path: 'utility.convertUnit',
		version: 'v1',
		endpoint: 'unitconversion',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/unitconversion',
		params: [
			{ name: 'amount', required: true, premium: false, enforced: true },
			{ name: 'unit', required: true, premium: false, enforced: true },
		],
		responseFields: ['type', 'unit', 'amount', 'conversions'],
	},
	utilityLogo: {
		catalogOperation: 'GET_COMPANY_LOGO',
		path: 'utility.logo',
		version: 'v1',
		endpoint: 'logo',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/logo',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'ticker', required: false, premium: false, enforced: null },
		],
		responseFields: ['name', 'ticker', 'image'],
	},
	utilityCountryFlag: {
		catalogOperation: 'GET_COUNTRY_FLAG',
		path: 'utility.countryFlag',
		version: 'v1',
		endpoint: 'countryflag',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/countryflag',
		params: [
			{ name: 'country', required: true, premium: false, enforced: true },
		],
		responseFields: ['country', 'square_image_url', 'rectangle_image_url'],
	},
	utilityRandomImage: {
		catalogOperation: 'GET_RANDOM_IMAGE',
		path: 'utility.randomImage',
		version: 'v1',
		endpoint: 'randomimage',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/randomimage',
		params: [
			{ name: 'category', required: false, premium: false, enforced: null },
			{ name: 'width', required: false, premium: false, enforced: null },
			{ name: 'height', required: false, premium: false, enforced: null },
		],
		responseFields: [],
	},
	utilityEmoji: {
		catalogOperation: 'GET_EMOJI',
		path: 'utility.emoji',
		version: 'v1',
		endpoint: 'emoji',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/emoji',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'code', required: false, premium: false, enforced: null },
			{ name: 'group', required: false, premium: false, enforced: null },
			{ name: 'subgroup', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: ['code', 'character', 'image', 'name', 'group', 'subgroup'],
	},
	transportAircraft: {
		catalogOperation: 'GET_AIRCRAFT',
		path: 'transport.aircraft',
		version: 'v1',
		endpoint: 'aircraft',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/aircraft',
		params: [
			{ name: 'manufacturer', required: false, premium: false, enforced: null },
			{ name: 'model', required: false, premium: false, enforced: null },
			{ name: 'engine_type', required: false, premium: false, enforced: null },
			{ name: 'min_speed', required: false, premium: false, enforced: null },
			{ name: 'max_speed', required: false, premium: false, enforced: null },
			{ name: 'min_range', required: false, premium: false, enforced: null },
			{ name: 'max_range', required: false, premium: false, enforced: null },
			{ name: 'min_length', required: false, premium: false, enforced: null },
			{ name: 'max_length', required: false, premium: false, enforced: null },
			{ name: 'min_height', required: false, premium: false, enforced: null },
			{ name: 'max_height', required: false, premium: false, enforced: null },
			{ name: 'min_wingspan', required: false, premium: false, enforced: null },
			{ name: 'max_wingspan', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'manufacturer',
			'model',
			'engine_type',
			'engine_thrust_lb_ft',
			'max_speed_knots',
			'cruise_speed_knots',
			'ceiling_ft',
			'takeoff_ground_run_ft',
			'landing_ground_roll_ft',
			'gross_weight_lbs',
			'empty_weight_lbs',
			'length_ft',
			'height_ft',
			'wing_span_ft',
			'range_nautical_miles',
		],
	},
	transportAirlines: {
		catalogOperation: 'GET_AIRLINES',
		path: 'transport.airlines',
		version: 'v1',
		endpoint: 'airlines',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: null,
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'iata', required: false, premium: false, enforced: null },
			{ name: 'icao', required: false, premium: false, enforced: null },
		],
		responseFields: [],
	},
	transportAirports: {
		catalogOperation: 'GET_AIRPORTS',
		path: 'transport.airports',
		version: 'v1',
		endpoint: 'airports',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/airports',
		params: [
			{ name: 'iata', required: false, premium: false, enforced: null },
			{ name: 'icao', required: false, premium: false, enforced: null },
			{ name: 'name', required: false, premium: true, enforced: null },
			{ name: 'country', required: false, premium: false, enforced: null },
			{ name: 'region', required: false, premium: true, enforced: null },
			{ name: 'city', required: false, premium: true, enforced: null },
			{ name: 'timezone', required: false, premium: false, enforced: null },
			{
				name: 'min_elevation',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_elevation',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'size', required: false, premium: false, enforced: null },
			{ name: 'has_iata', required: false, premium: false, enforced: null },
			{
				name: 'min_runway_length',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'type', required: false, premium: false, enforced: null },
			{
				name: 'scheduled_service',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'continent', required: false, premium: false, enforced: null },
			{ name: 'surface', required: false, premium: false, enforced: null },
			{ name: 'has_lights', required: false, premium: false, enforced: null },
			{ name: 'q', required: false, premium: false, enforced: null },
			{
				name: 'include_closed',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'limit', required: false, premium: false, enforced: null },
			{ name: 'sort', required: false, premium: false, enforced: null },
			{ name: 'order', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'iata',
			'icao',
			'name',
			'city',
			'region',
			'country',
			'elevation_ft',
			'latitude',
			'longitude',
			'timezone',
			'size',
			'num_runways',
			'ident',
			'type',
			'region_code',
			'country_name',
			'continent',
			'elevation_m',
			'scheduled_service',
			'is_closed',
			'gps_code',
			'local_code',
			'home_link',
			'wikipedia_link',
			'keywords',
			'longest_runway_ft',
			'runways',
			'estimated_annual_passengers',
		],
	},
	transportHelicopters: {
		catalogOperation: 'GET_HELICOPTER',
		path: 'transport.helicopters',
		version: 'v1',
		endpoint: 'helicopter',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/helicopter',
		params: [
			{ name: 'manufacturer', required: false, premium: false, enforced: null },
			{ name: 'model', required: false, premium: false, enforced: null },
			{ name: 'min_speed', required: false, premium: false, enforced: null },
			{ name: 'max_speed', required: false, premium: false, enforced: null },
			{ name: 'min_range', required: false, premium: false, enforced: null },
			{ name: 'max_range', required: false, premium: false, enforced: null },
			{ name: 'min_length', required: false, premium: false, enforced: null },
			{ name: 'max_length', required: false, premium: false, enforced: null },
			{ name: 'min_height', required: false, premium: false, enforced: null },
			{ name: 'max_height', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'manufacturer',
			'model',
			'max_speed_sl_knots',
			'cruise_speed_sl_knots',
			'range_nautical_miles',
			'cruise_time_min',
			'fuel_capacity_gallons',
			'gross_external_load_lbs',
			'external_load_limit_lbs',
			'main_rotor_diameter_ft',
			'num_blades',
			'blade_material',
			'rotor_type',
			'storage_width_ft',
			'length_ft',
			'height_ft',
		],
	},
	transportCars: {
		catalogOperation: 'GET_CARS',
		path: 'transport.cars',
		version: 'v1',
		endpoint: 'cars',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/cars',
		params: [
			{ name: 'make', required: true, premium: false, enforced: false },
			{ name: 'model', required: true, premium: false, enforced: true },
			{ name: 'trim', required: true, premium: false, enforced: false },
		],
		responseFields: [],
	},
	transportMotorcycles: {
		catalogOperation: 'GET_MOTORCYCLES',
		path: 'transport.motorcycles',
		version: 'v1',
		endpoint: 'motorcycles',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/motorcycles',
		params: [
			{ name: 'make', required: false, premium: false, enforced: null },
			{ name: 'model', required: false, premium: false, enforced: null },
			{ name: 'year', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [],
	},
	transportElectricVehicles: {
		catalogOperation: 'GET_ELECTRIC_VEHICLE_INFO',
		path: 'transport.electricVehicles',
		version: 'v1',
		endpoint: 'electricvehicle',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/electricvehicle',
		params: [
			{ name: 'make', required: false, premium: false, enforced: null },
			{ name: 'model', required: false, premium: false, enforced: null },
			{ name: 'min_year', required: false, premium: false, enforced: null },
			{ name: 'max_year', required: false, premium: false, enforced: null },
			{ name: 'min_range', required: false, premium: false, enforced: null },
			{ name: 'max_range', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'make',
			'model',
			'year_start',
			'battery_capacity',
			'battery_useable_capacity',
			'charge_power',
			'charge_power_max',
			'top_speed',
			'electric_range',
			'total_power',
			'vehicle_consumption',
			'length, width, height',
			'seats',
		],
	},
	transportVin: {
		catalogOperation: 'LOOKUP_VIN',
		path: 'transport.vin',
		version: 'v1',
		endpoint: 'vinlookup',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/vinlookup',
		params: [{ name: 'vin', required: true, premium: false, enforced: true }],
		responseFields: [],
	},
	healthCaloriesBurned: {
		catalogOperation: 'CALCULATE_CALORIES_BURNED',
		path: 'health.caloriesBurned',
		version: 'v1',
		endpoint: 'caloriesburned',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/caloriesburned',
		params: [
			{ name: 'activity', required: true, premium: false, enforced: true },
			{ name: 'weight', required: false, premium: false, enforced: null },
			{ name: 'duration', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'name',
			'calories_per_hour',
			'duration_minutes',
			'total_calories',
		],
	},
	healthNutrition: {
		catalogOperation: 'NUTRITION',
		path: 'health.nutrition',
		version: 'v1',
		endpoint: 'nutrition',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/nutrition',
		params: [{ name: 'query', required: true, premium: false, enforced: true }],
		responseFields: [
			'calories',
			'serving_size_g',
			'fat_total_g',
			'fat_saturated_g',
			'fat_trans_g',
			'protein_g',
			'sodium_mg',
			'potassium_mg',
			'cholesterol_mg',
			'carbohydrates_total_g',
			'fiber_g',
			'sugar_g',
			'added_sugars_g',
			'net_carbs_g',
			'iron_mg',
			'calcium_mg',
			'magnesium_mg',
			'zinc_mg',
			'vitamin_a_mcg',
			'vitamin_c_mg',
			'vitamin_d_mcg',
		],
	},
	healthExercises: {
		catalogOperation: 'GET_EXERCISES',
		path: 'health.exercises',
		version: 'v1',
		endpoint: 'exercises',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: true,
		documented: 'https://api-ninjas.com/api/exercises',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'type', required: false, premium: false, enforced: null },
			{ name: 'muscle', required: false, premium: false, enforced: null },
			{ name: 'difficulty', required: false, premium: false, enforced: null },
			{ name: 'equipments', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'name',
			'type',
			'muscle',
			'difficulty',
			'instructions',
			'equipments',
			'safety_info',
		],
	},
	healthRecipes: {
		catalogOperation: 'GET_RECIPE',
		path: 'health.recipes',
		version: 'v3',
		endpoint: 'recipe',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/recipe',
		params: [
			{ name: 'title', required: false, premium: false, enforced: null },
			{ name: 'ingredients', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'title',
			'ingredients',
			'servings',
			'instructions',
			'nutrition',
		],
	},
	healthCocktails: {
		catalogOperation: 'GET_COCKTAIL',
		path: 'health.cocktails',
		version: 'v1',
		endpoint: 'cocktail',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/cocktail',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'ingredients', required: false, premium: false, enforced: null },
		],
		responseFields: ['name', 'ingredients', 'instructions'],
	},
	referenceAnimals: {
		catalogOperation: 'GET_ANIMALS',
		path: 'reference.animals',
		version: 'v1',
		endpoint: 'animals',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/animals',
		params: [{ name: 'name', required: true, premium: false, enforced: true }],
		responseFields: ['name', 'taxonomy', 'locations', 'characteristics'],
	},
	referenceCats: {
		catalogOperation: 'GET_CATS',
		path: 'reference.cats',
		version: 'v1',
		endpoint: 'cats',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/cats',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'min_weight', required: false, premium: false, enforced: null },
			{ name: 'max_weight', required: false, premium: false, enforced: null },
			{
				name: 'min_life_expectancy',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_life_expectancy',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'shedding', required: false, premium: false, enforced: null },
			{
				name: 'family_friendly',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'playfulness', required: false, premium: false, enforced: null },
			{ name: 'grooming', required: false, premium: false, enforced: null },
			{
				name: 'other_pets_friendly',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'children_friendly',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'name',
			'image_link',
			'length',
			'origin',
			'family_friendly',
			'children_friendly',
			'other_pets_friendly',
			'shedding',
			'grooming',
			'general_health',
			'playfulness',
			'intelligence',
			'min_weight',
			'max_weight',
			'min_life_expectancy',
			'max_life_expectancy',
		],
	},
	referenceDogs: {
		catalogOperation: 'GET_DOGS',
		path: 'reference.dogs',
		version: 'v1',
		endpoint: 'dogs',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/dogs',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'min_height', required: false, premium: false, enforced: null },
			{ name: 'max_height', required: false, premium: false, enforced: null },
			{ name: 'min_weight', required: false, premium: false, enforced: null },
			{ name: 'max_weight', required: false, premium: false, enforced: null },
			{
				name: 'min_life_expectancy',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_life_expectancy',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'shedding', required: false, premium: false, enforced: null },
			{ name: 'barking', required: false, premium: false, enforced: null },
			{ name: 'energy', required: false, premium: false, enforced: null },
			{
				name: 'protectiveness',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'trainability', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'name',
			'image_link',
			'good_with_children',
			'good_with_other_dogs',
			'good_with_strangers',
			'shedding',
			'grooming',
			'drooling',
			'coat_length',
			'playfulness',
			'protectiveness',
			'trainability',
			'energy',
			'barking',
			'min_life_expectancy',
			'max_life_expectancy',
			'min_height_male',
			'max_height_male',
			'min_height_female',
			'max_height_female',
			'min_weight_male',
			'max_weight_male',
			'min_weight_female',
			'max_weight_female',
		],
	},
	referencePlanets: {
		catalogOperation: 'GET_PLANETS',
		path: 'reference.planets',
		version: 'v1',
		endpoint: 'planets',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/planets',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{ name: 'min_mass', required: false, premium: false, enforced: null },
			{ name: 'max_mass', required: false, premium: false, enforced: null },
			{ name: 'min_radius', required: false, premium: false, enforced: null },
			{ name: 'max_radius', required: false, premium: false, enforced: null },
			{ name: 'min_period', required: false, premium: false, enforced: null },
			{ name: 'max_period', required: false, premium: false, enforced: null },
			{
				name: 'min_temperature',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_temperature',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_distance_light_year',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_distance_light_year',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_semi_major_axis',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_semi_major_axis',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'name',
			'mass',
			'radius',
			'period',
			'semi_major_axis',
			'temperature',
			'distance_light_year',
			'host_star_mass',
			'host_star_temperature',
		],
	},
	referenceStars: {
		catalogOperation: 'GET_STARS',
		path: 'reference.stars',
		version: 'v1',
		endpoint: 'stars',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/stars',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{
				name: 'constellation',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_apparent_magnitude',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_apparent_magnitude',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_absolute_magnitude',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_absolute_magnitude',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'min_distance_light_year',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_distance_light_year',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: [
			'name',
			'constellation',
			'right_ascension',
			'declination',
			'apparent_magnitude',
			'absolute_magnitude',
			'distance_light_year',
			'spectral_class',
		],
	},
	referenceHistoricalEvents: {
		catalogOperation: 'GET_HISTORICAL_EVENTS',
		path: 'reference.historicalEvents',
		version: 'v1',
		endpoint: 'historicalevents',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/historicalevents',
		params: [
			{ name: 'text', required: false, premium: false, enforced: null },
			{ name: 'year', required: false, premium: false, enforced: null },
			{ name: 'month', required: false, premium: false, enforced: null },
			{ name: 'day', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: ['year', 'month', 'day', 'event'],
	},
	referenceHistoricalFigures: {
		catalogOperation: 'GET_HISTORICAL_FIGURES',
		path: 'reference.historicalFigures',
		version: 'v1',
		endpoint: 'historicalfigures',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/historicalfigures',
		params: [
			{ name: 'name', required: true, premium: false, enforced: true },
			{ name: 'offset', required: false, premium: false, enforced: null },
		],
		responseFields: ['name', 'title', 'info'],
	},
	referenceDayInHistory: {
		catalogOperation: 'GET_DAY_IN_HISTORY',
		path: 'reference.dayInHistory',
		version: 'v1',
		endpoint: 'dayinhistory',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/dayinhistory',
		params: [
			{ name: 'month', required: false, premium: true, enforced: null },
			{ name: 'day', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
		],
		responseFields: ['year', 'month', 'day', 'event'],
	},
	referenceCelebrities: {
		catalogOperation: 'GET_CELEBRITY',
		path: 'reference.celebrities',
		version: 'v1',
		endpoint: 'celebrity',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/celebrity',
		params: [
			{ name: 'name', required: false, premium: false, enforced: null },
			{
				name: 'min_net_worth',
				required: false,
				premium: false,
				enforced: null,
			},
			{
				name: 'max_net_worth',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'nationality', required: false, premium: false, enforced: null },
			{ name: 'min_height', required: false, premium: false, enforced: null },
			{ name: 'max_height', required: false, premium: false, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: [
			'name',
			'net_worth',
			'gender',
			'nationality',
			'occupation',
			'height',
			'birthday',
			'age',
			'is_alive',
		],
	},
	referenceBabyNames: {
		catalogOperation: 'GET_BABY_NAMES',
		path: 'reference.babyNames',
		version: 'v1',
		endpoint: 'babynames',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/babynames',
		params: [
			{ name: 'gender', required: false, premium: false, enforced: null },
			{ name: 'popular_only', required: false, premium: false, enforced: null },
		],
		responseFields: [],
	},
	entertainmentJokes: {
		catalogOperation: 'GET_JOKES',
		path: 'entertainment.jokes',
		version: 'v1',
		endpoint: 'jokes',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/jokes',
		params: [{ name: 'limit', required: false, premium: true, enforced: null }],
		responseFields: ['joke'],
	},
	entertainmentDadJokes: {
		catalogOperation: 'GET_DAD_JOKE',
		path: 'entertainment.dadJokes',
		version: 'v1',
		endpoint: 'dadjokes',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/dadjokes',
		params: [{ name: 'limit', required: false, premium: true, enforced: null }],
		responseFields: ['joke'],
	},
	entertainmentChuckNorris: {
		catalogOperation: 'GET_CHUCK_NORRIS_JOKE',
		path: 'entertainment.chuckNorris',
		version: 'v1',
		endpoint: 'chucknorris',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/chucknorris',
		params: [],
		responseFields: ['joke'],
	},
	entertainmentJokeOfTheDay: {
		catalogOperation: 'GET_JOKE_OF_THE_DAY',
		path: 'entertainment.jokeOfTheDay',
		version: 'v1',
		endpoint: 'jokeoftheday',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/jokes',
		params: [],
		responseFields: [],
	},
	entertainmentFacts: {
		catalogOperation: 'GET_FACTS',
		path: 'entertainment.facts',
		version: 'v1',
		endpoint: 'facts',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/facts',
		params: [{ name: 'limit', required: false, premium: true, enforced: null }],
		responseFields: [],
	},
	entertainmentFactOfTheDay: {
		catalogOperation: 'GET_FACT_OF_THE_DAY',
		path: 'entertainment.factOfTheDay',
		version: 'v1',
		endpoint: 'factoftheday',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/facts',
		params: [],
		responseFields: [],
	},
	entertainmentQuotes: {
		catalogOperation: 'GET_QUOTES',
		path: 'entertainment.quotes',
		version: 'v2',
		endpoint: 'quotes',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/quotes',
		params: [
			{ name: 'categories', required: false, premium: false, enforced: null },
			{
				name: 'exclude_categories',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'author', required: false, premium: false, enforced: null },
			{ name: 'work', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
			{ name: 'offset', required: false, premium: true, enforced: null },
		],
		responseFields: ['quote', 'author', 'work', 'categories'],
	},
	entertainmentRandomQuotes: {
		catalogOperation: 'GET_RANDOM_QUOTES',
		path: 'entertainment.randomQuotes',
		version: 'v2',
		endpoint: 'randomquotes',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/quotes',
		params: [
			{ name: 'categories', required: false, premium: false, enforced: null },
			{
				name: 'exclude_categories',
				required: false,
				premium: false,
				enforced: null,
			},
			{ name: 'author', required: false, premium: false, enforced: null },
			{ name: 'work', required: false, premium: false, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
		],
		responseFields: [],
	},
	entertainmentQuoteOfTheDay: {
		catalogOperation: 'GET_QUOTE_OF_THE_DAY',
		path: 'entertainment.quoteOfTheDay',
		version: 'v2',
		endpoint: 'quoteoftheday',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/quotes',
		params: [],
		responseFields: [],
	},
	entertainmentAdvice: {
		catalogOperation: 'GET_ADVICE',
		path: 'entertainment.advice',
		version: 'v1',
		endpoint: 'advice',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/advice',
		params: [],
		responseFields: ['advice'],
	},
	entertainmentBucketList: {
		catalogOperation: 'GET_BUCKETLIST',
		path: 'entertainment.bucketList',
		version: 'v1',
		endpoint: 'bucketlist',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/bucketlist',
		params: [],
		responseFields: ['item'],
	},
	entertainmentHobbies: {
		catalogOperation: 'GET_HOBBIES',
		path: 'entertainment.hobbies',
		version: 'v1',
		endpoint: 'hobbies',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/hobbies',
		params: [
			{ name: 'category', required: false, premium: false, enforced: null },
		],
		responseFields: ['hobby', 'link', 'category'],
	},
	entertainmentHoroscope: {
		catalogOperation: 'GET_HOROSCOPE',
		path: 'entertainment.horoscope',
		version: 'v1',
		endpoint: 'horoscope',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/horoscope',
		params: [
			{ name: 'zodiac', required: true, premium: false, enforced: true },
			{ name: 'date', required: false, premium: true, enforced: null },
		],
		responseFields: ['date', 'sign', 'horoscope'],
	},
	entertainmentRiddles: {
		catalogOperation: 'GET_RIDDLES',
		path: 'entertainment.riddles',
		version: 'v1',
		endpoint: 'riddles',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/riddles',
		params: [{ name: 'limit', required: false, premium: true, enforced: null }],
		responseFields: ['title', 'question', 'answer'],
	},
	entertainmentTrivia: {
		catalogOperation: 'GET_TRIVIA',
		path: 'entertainment.trivia',
		version: 'v1',
		endpoint: 'trivia',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/trivia',
		params: [
			{ name: 'category', required: false, premium: true, enforced: null },
			{ name: 'limit', required: false, premium: true, enforced: null },
		],
		responseFields: ['category', 'question', 'answer'],
	},
	entertainmentTriviaOfTheDay: {
		catalogOperation: 'GET_TRIVIA_OF_THE_DAY',
		path: 'entertainment.triviaOfTheDay',
		version: 'v1',
		endpoint: 'triviaoftheday',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/trivia',
		params: [],
		responseFields: [],
	},
	entertainmentGenerateSudoku: {
		catalogOperation: 'GENERATE_SUDOKU',
		path: 'entertainment.generateSudoku',
		version: 'v1',
		endpoint: 'sudokugenerate',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/sudoku',
		params: [
			{ name: 'width', required: false, premium: false, enforced: null },
			{ name: 'height', required: false, premium: false, enforced: null },
			{ name: 'difficulty', required: false, premium: false, enforced: null },
			{ name: 'seed', required: false, premium: false, enforced: null },
		],
		responseFields: ['puzzle', 'solution'],
	},
	entertainmentSolveSudoku: {
		catalogOperation: 'SOLVE_SUDOKU',
		path: 'entertainment.solveSudoku',
		version: 'v1',
		endpoint: 'sudokusolve',
		method: 'GET',
		/** True when the documentation describes a choice of parameter combinations. */
		combination: false,
		documented: 'https://api-ninjas.com/api/sudoku',
		params: [
			{ name: 'puzzle', required: true, premium: false, enforced: true },
			{ name: 'width', required: true, premium: false, enforced: true },
			{ name: 'height', required: true, premium: false, enforced: true },
		],
		responseFields: ['status', 'solution'],
	},
};
