export const baseLinkerOperationCatalog = [
	{
		code: 'BASELINKER_ADD_INVENTORY',
		title: 'Add Inventory',
		description:
			'Tool to add or update a BaseLinker catalog (inventory). Use when you need to create a new catalog or update an existing one with the same identifier.',
		method: 'addInventory',
		group: 'inventory',
		path: 'inventory.addInventory',
		riskLevel: 'write',
		inputFields: [
			'inventory_id',
			'name',
			'description',
			'languages',
			'default_language',
			'price_groups',
			'default_price_group',
			'warehouses',
			'default_warehouse',
			'reservations',
		],
		outputFields: ['status', 'inventory_id'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_CATEGORY',
		title: 'Add Inventory Category',
		description:
			'Tool to add or update a category in the BaseLinker catalog. Use when you need to create a new category or update an existing one. Adding a category with the same identifier again updates the previously saved category.',
		method: 'addInventoryCategory',
		group: 'inventory',
		path: 'inventory.addInventoryCategory',
		riskLevel: 'write',
		inputFields: ['inventory_id', 'category_id', 'name', 'parent_id'],
		outputFields: ['status', 'category_id'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_DOCUMENT',
		title: 'Add Inventory Document',
		description:
			'Tool to create a new inventory document in BaseLinker storage. Use when you need to create goods receipts, issues, or transfers. Documents are created as drafts and require confirmation via user action or setInventoryDocumentStatusConfirmed API method.',
		method: 'addInventoryDocument',
		group: 'inventoryDocuments',
		path: 'inventoryDocuments.addInventoryDocument',
		riskLevel: 'write',
		inputFields: [
			'warehouse_id',
			'document_type',
			'target_warehouse_id',
			'date_add',
			'date_execute',
			'contractor',
			'invoice_no',
			'notes',
		],
		outputFields: ['status', 'document_id', 'document_number'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_MANUFACTURER',
		title: 'Add Inventory Manufacturer',
		description:
			'Tool to add or update a manufacturer in the BaseLinker catalog. Use when you need to create a new manufacturer or update an existing one. Adding a manufacturer with the same identifier again updates the previously saved manufacturer.',
		method: 'addInventoryManufacturer',
		group: 'inventory',
		path: 'inventory.addInventoryManufacturer',
		riskLevel: 'write',
		inputFields: [
			'manufacturer_id',
			'name',
			'manufacturer_name',
			'manufacturer_photo',
			'manufacturer_url',
			'manufacturer_street',
			'manufacturer_postcode',
			'manufacturer_city',
			'manufacturer_state',
			'manufacturer_country_code',
			'manufacturer_email',
			'manufacturer_phone',
		],
		outputFields: ['status', 'manufacturer_id'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_PAYER',
		title: 'Add Inventory Payer',
		description:
			"Tool to add a new payer or update an existing one in BaseLinker storage. Use when you need to create a new payer with contact details or update an existing payer's information.",
		method: 'addInventoryPayer',
		group: 'inventory',
		path: 'inventory.addInventoryPayer',
		riskLevel: 'write',
		inputFields: ['payer_id', 'name', 'address', 'postcode', 'city', 'tax_no'],
		outputFields: ['status', 'payer_id'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_PRICE_GROUP',
		title: 'Add Inventory Price Group',
		description:
			'Tool to create or update a price group in BaseLinker storage. Use when you need to define pricing tiers (e.g., wholesale, retail, VIP) that can be later assigned to inventory items via addInventory method.',
		method: 'addInventoryPriceGroup',
		group: 'inventory',
		path: 'inventory.addInventoryPriceGroup',
		riskLevel: 'write',
		inputFields: [
			'price_group_id',
			'name',
			'description',
			'currency',
			'price_group_type',
			'source_price_group_id',
			'price_multiplier',
			'price_addition',
			'is_bundle_price_calculated',
			'bundle_price_multiplier',
			'bundle_price_addition',
		],
		outputFields: ['status', 'price_group_id'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_PRODUCT',
		title: 'Add Inventory Product',
		description:
			'Add a new product to BaseLinker catalog or update an existing product. Use when creating inventory items or modifying product details like SKU, price, stock, dimensions, and text fields. Provide product_id to update existing products, omit it to create new ones.',
		method: 'addInventoryProduct',
		group: 'inventory',
		path: 'inventory.addInventoryProduct',
		riskLevel: 'write',
		inputFields: [
			'inventory_id',
			'product_id',
			'parent_id',
			'is_bundle',
			'sku',
			'ean',
			'ean_additional',
			'asin',
			'tags',
			'tax_rate',
			'weight',
			'height',
			'width',
			'length',
			'average_cost',
			'star',
			'manufacturer_id',
			'category_id',
			'prices',
			'stock',
			'locations',
			'text_fields',
			'images',
			'videos',
			'media_options',
			'links',
			'bundle_products',
			'suppliers',
		],
		outputFields: ['status', 'product_id', 'warnings'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_PURCHASE_ORDER',
		title: 'Add Inventory Purchase Order',
		description:
			'Tool to create a new purchase order in BaseLinker storage. Orders are created as drafts by default. Use when you need to create a new purchase order for inventory management.',
		method: 'addInventoryPurchaseOrder',
		group: 'purchaseOrders',
		path: 'purchaseOrders.addInventoryPurchaseOrder',
		riskLevel: 'write',
		inputFields: [
			'warehouse_id',
			'supplier_id',
			'payer_id',
			'currency',
			'name',
			'notes',
			'invoice_no',
			'date_delivery_expected',
			'additional_costs',
			'packages',
		],
		outputFields: ['status', 'order_id', 'document_number'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_PURCHASE_ORDER_ITEMS',
		title: 'Add Inventory Purchase Order Items',
		description:
			'Tool to add items to an existing purchase order in BaseLinker. Use when you need to add products to a purchase order that has already been created.',
		method: 'addInventoryPurchaseOrderItems',
		group: 'purchaseOrders',
		path: 'purchaseOrders.addInventoryPurchaseOrderItems',
		riskLevel: 'write',
		inputFields: ['order_id', 'items'],
		outputFields: ['status', 'items'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_SUPPLIER',
		title: 'Add Inventory Supplier',
		description:
			'Tool to add a new supplier or update an existing one in BaseLinker storage. Use when you need to manage supplier information for inventory management. If supplier_id is provided, the existing supplier will be updated; otherwise, a new supplier will be created.',
		method: 'addInventorySupplier',
		group: 'inventory',
		path: 'inventory.addInventorySupplier',
		riskLevel: 'write',
		inputFields: [
			'supplier_id',
			'name',
			'take_product_cost_from',
			'take_product_code_from',
			'address',
			'postcode',
			'city',
			'phone',
			'email',
			'email_copy_to',
			'currency',
			'tax_no',
		],
		outputFields: ['status', 'supplier_id'],
	},
	{
		code: 'BASELINKER_ADD_INVENTORY_WAREHOUSE',
		title: 'Add Inventory Warehouse',
		description:
			'Tool to add a new warehouse or update an existing warehouse in BaseLinker inventories. Use when you need to create new warehouse locations for inventory management or update warehouse details. Adding a warehouse with the same identifier again will update the previously saved warehouse. The method does not allow editing warehouses created automatically for external stocks.',
		method: 'addInventoryWarehouse',
		group: 'inventory',
		path: 'inventory.addInventoryWarehouse',
		riskLevel: 'write',
		inputFields: [
			'warehouse_id',
			'name',
			'description',
			'stock_edition',
			'country',
			'address',
			'postcode',
			'city',
		],
		outputFields: ['status', 'warehouse_id'],
	},
	{
		code: 'BASELINKER_ADD_INVOICE',
		title: 'Add Invoice',
		description:
			'Tool to issue an order invoice in BaseLinker. Use when you need to generate an invoice for an existing order using a specific numbering series.',
		method: 'addInvoice',
		group: 'documents',
		path: 'documents.addInvoice',
		riskLevel: 'write',
		inputFields: ['order_id', 'series_id', 'vat_rate'],
		outputFields: ['status', 'invoice_id'],
	},
	{
		code: 'BASELINKER_ADD_INVOICE_CORRECTION',
		title: 'Add Invoice Correction',
		description:
			'Tool to issue an order invoice correction. Use when correcting pricing errors, handling returns, or updating invoice data. Either original_invoice_id or return_order_id must be provided.',
		method: 'addInvoiceCorrection',
		group: 'documents',
		path: 'documents.addInvoiceCorrection',
		riskLevel: 'write',
		inputFields: [
			'original_invoice_id',
			'return_order_id',
			'series_id',
			'date_sell',
			'correcting_reason',
			'correcting_items',
			'correcting_data',
			'invoice_fullname',
			'invoice_company',
			'invoice_address',
			'invoice_postcode',
			'invoice_city',
			'invoice_state',
			'invoice_country_code',
			'invoice_nip',
			'items',
			'fv_payment',
			'fv_person',
		],
		outputFields: ['status', 'invoice_id'],
	},
	{
		code: 'BASELINKER_ADD_ORDER',
		title: 'Add Order',
		description:
			'Tool to add a new order to the BaseLinker order manager. Use when you need to create a new order with customer details, products, and delivery information.',
		method: 'addOrder',
		group: 'orders',
		path: 'orders.addOrder',
		riskLevel: 'write',
		inputFields: [
			'order_status_id',
			'custom_source_id',
			'date_add',
			'currency',
			'payment_method',
			'payment_method_cod',
			'paid',
			'user_comments',
			'admin_comments',
			'email',
			'phone',
			'user_login',
			'delivery_method',
			'delivery_price',
			'delivery_fullname',
			'delivery_company',
			'delivery_address',
			'delivery_postcode',
			'delivery_city',
			'delivery_state',
			'delivery_country_code',
			'delivery_point_id',
			'delivery_point_name',
			'delivery_point_address',
			'delivery_point_postcode',
			'delivery_point_city',
			'invoice_fullname',
			'invoice_company',
			'invoice_nip',
			'invoice_address',
			'invoice_postcode',
			'invoice_city',
			'invoice_state',
			'invoice_country_code',
			'want_invoice',
			'extra_field_1',
			'extra_field_2',
			'custom_extra_fields',
			'products',
		],
		outputFields: ['status', 'order_id'],
	},
	{
		code: 'BASELINKER_ADD_ORDER_BY_SPLIT',
		title: 'Add Order By Split',
		description:
			'Tool to create a new order by splitting selected products from an existing order. Use when you need to split an order into multiple shipments or separate deliveries. The new order inherits all customer details, addresses, and settings from the original order, with only the specified products and optional delivery costs moved to it.',
		method: 'addOrderBySplit',
		group: 'orders',
		path: 'orders.addOrderBySplit',
		riskLevel: 'write',
		inputFields: ['order_id', 'items_to_split', 'delivery_cost_to_split'],
		outputFields: ['status', 'new_order_id'],
	},
	{
		code: 'BASELINKER_ADD_ORDER_DUPLICATE',
		title: 'Add Order Duplicate',
		description:
			'Tool to add a new order by duplicating an existing order in BaseLinker. The new order will have the same data as the original order but with a different ID.',
		method: 'addOrderDuplicate',
		group: 'orders',
		path: 'orders.addOrderDuplicate',
		riskLevel: 'write',
		inputFields: ['order_id'],
		outputFields: ['status', 'order_id'],
	},
	{
		code: 'BASELINKER_ADD_ORDER_RETURN',
		title: 'Add Order Return',
		description:
			'Tool to add a new order return to BaseLinker. Use when creating a return for an order. Requires status_id (get from getOrderReturnStatusList), date_add (Unix timestamp), currency (3-letter code), and refunded status.',
		method: 'addOrderReturn',
		group: 'returns',
		path: 'returns.addOrderReturn',
		riskLevel: 'write',
		inputFields: [
			'order_id',
			'status_id',
			'custom_source_id',
			'reference_number',
			'date_add',
			'currency',
			'refunded',
			'admin_comments',
			'email',
			'phone',
			'user_login',
			'delivery_price',
			'delivery_fullname',
			'delivery_company',
			'delivery_address',
			'delivery_postcode',
			'delivery_city',
			'delivery_state',
			'delivery_country_code',
			'extra_field_1',
			'extra_field_2',
			'custom_extra_fields',
			'products',
			'refund_account_number',
			'refund_iban',
			'refund_swift',
		],
		outputFields: ['status', 'return_id'],
	},
	{
		code: 'BASELINKER_ADD_ORDER_RETURN_PRODUCT',
		title: 'Add Order Return Product',
		description:
			'Tool to add a new product to an existing order return in BaseLinker. Use when a customer is returning items and you need to register the returned products.',
		method: 'addOrderReturnProduct',
		group: 'returns',
		path: 'returns.addOrderReturnProduct',
		riskLevel: 'write',
		inputFields: [
			'return_id',
			'order_product_id',
			'storage',
			'storage_id',
			'product_id',
			'variant_id',
			'auction_id',
			'name',
			'sku',
			'ean',
			'location',
			'warehouse_id',
			'attributes',
			'price_brutto',
			'tax_rate',
			'quantity',
			'weight',
			'status_id',
			'return_reason_id',
		],
		outputFields: ['status', 'order_return_product_id'],
	},
	{
		code: 'BASELINKER_ADD_SHOP_CATEGORY',
		title: 'Add Shop Category',
		description:
			"Tool to add a new category to BaseLinker storage (shops, warehouses, or BaseLinker inventory). Use when you need to create a new category in a connected storage's category structure. Requires a storage_id which can be obtained from GetExternalStoragesList or use 'bl_1' for BaseLinker inventory.",
		method: 'addCategory',
		group: 'externalStorages',
		path: 'externalStorages.addCategory',
		riskLevel: 'write',
		inputFields: ['storage_id', 'category_id', 'name', 'parent_id'],
		outputFields: ['status', 'storage_id', 'category_id'],
	},
	{
		code: 'BASELINKER_CREATE_PACKAGE_MANUAL',
		title: 'Create Package Manual',
		description:
			'Tool to register shipping details for orders when shipments are created outside BaseLinker. Use when you need to add tracking numbers and courier information for manually created shipments. Supports marking packages as return shipments.',
		method: 'createPackageManual',
		group: 'couriers',
		path: 'couriers.createPackageManual',
		riskLevel: 'write',
		inputFields: [
			'order_id',
			'courier_code',
			'package_number',
			'pickup_date',
			'return_shipment',
		],
		outputFields: ['status', 'package_id', 'package_number'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY',
		title: 'Delete Inventory',
		description:
			'Tool to delete a catalog from BaseLinker storage. Use when you need to permanently remove an inventory/catalog.',
		method: 'deleteInventory',
		group: 'inventory',
		path: 'inventory.deleteInventory',
		riskLevel: 'destructive',
		inputFields: ['inventory_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY_CATEGORY',
		title: 'Delete Inventory Category',
		description:
			'Tool to remove categories from BaseLinker warehouse. Along with the category, the products contained therein are removed (however, this does not apply to products in subcategories). The subcategories will be changed to the highest level categories.',
		method: 'deleteInventoryCategory',
		group: 'inventory',
		path: 'inventory.deleteInventoryCategory',
		riskLevel: 'destructive',
		inputFields: ['category_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY_MANUFACTURER',
		title: 'Delete Inventory Manufacturer',
		description:
			'Tool to remove a manufacturer from the BaseLinker catalog. Use when you need to delete a manufacturer that is no longer needed or was added by mistake.',
		method: 'deleteInventoryManufacturer',
		group: 'inventory',
		path: 'inventory.deleteInventoryManufacturer',
		riskLevel: 'destructive',
		inputFields: ['manufacturer_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY_PAYER',
		title: 'Delete Inventory Payer',
		description:
			'Tool to remove a payer from BaseLinker storage. Use when you need to delete an existing payer entry by its ID.',
		method: 'deleteInventoryPayer',
		group: 'inventory',
		path: 'inventory.deleteInventoryPayer',
		riskLevel: 'destructive',
		inputFields: ['payer_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY_PRICE_GROUP',
		title: 'Delete Inventory Price Group',
		description:
			'Tool to remove a price group from BaseLinker storage. Use when you need to delete an existing price group by its identifier.',
		method: 'deleteInventoryPriceGroup',
		group: 'inventory',
		path: 'inventory.deleteInventoryPriceGroup',
		riskLevel: 'destructive',
		inputFields: ['price_group_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY_PRODUCT',
		title: 'Delete Inventory Product',
		description:
			'Tool to remove a product from the BaseLinker catalog. Use when you need to permanently delete an inventory product by its ID.',
		method: 'deleteInventoryProduct',
		group: 'inventory',
		path: 'inventory.deleteInventoryProduct',
		riskLevel: 'destructive',
		inputFields: ['product_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_INVENTORY_WAREHOUSE',
		title: 'Delete Inventory Warehouse',
		description:
			'Tool to remove a warehouse from BaseLinker inventories. Use when you need to delete a warehouse that is no longer needed. Note: This method does not allow removal of warehouses created automatically for external stock management (shops, wholesalers, etc.).',
		method: 'deleteInventoryWarehouse',
		group: 'inventory',
		path: 'inventory.deleteInventoryWarehouse',
		riskLevel: 'destructive',
		inputFields: ['warehouse_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_ORDER_PRODUCT',
		title: 'Delete Order Product',
		description:
			'Tool to remove a specific product from an order in BaseLinker. Use when you need to delete an order item without canceling the entire order.',
		method: 'deleteOrderProduct',
		group: 'orders',
		path: 'orders.deleteOrderProduct',
		riskLevel: 'destructive',
		inputFields: ['order_id', 'order_product_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_ORDER_RETURN_PRODUCT',
		title: 'Delete Order Return Product',
		description:
			'Tool to remove a specific product from an order return in BaseLinker. Use when you need to delete a product item from an existing return request.',
		method: 'deleteOrderReturnProduct',
		group: 'returns',
		path: 'returns.deleteOrderReturnProduct',
		riskLevel: 'destructive',
		inputFields: ['return_id', 'order_return_product_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_DELETE_ORDERS',
		title: 'Delete Orders',
		description:
			'Tool to delete multiple orders from BaseLinker order manager. Use when you need to permanently remove orders from the system.',
		method: 'deleteOrders',
		group: 'orders',
		path: 'orders.deleteOrders',
		riskLevel: 'destructive',
		inputFields: ['order_ids'],
		outputFields: ['status', 'deleted_order_ids'],
	},
	{
		code: 'BASELINKER_GET_CONNECT_INTEGRATION_CONTRACTORS',
		title: 'Get Connect Integration Contractors',
		description:
			'Tool to retrieve a list of contractors connected to a selected Base Connect integration. Use when you need to discover available contractors for a specific integration before performing contractor-specific operations.',
		method: 'getConnectIntegrationContractors',
		group: 'connect',
		path: 'connect.getConnectIntegrationContractors',
		riskLevel: 'read',
		inputFields: ['connect_integration_id'],
		outputFields: ['status', 'contractors'],
	},
	{
		code: 'BASELINKER_GET_CONNECT_INTEGRATIONS',
		title: 'Get Connect Integrations',
		description:
			'Tool to retrieve a list of all Base Connect integrations on this account. Returns both integrations created on the account and integrations to which the account has connected.',
		method: 'getConnectIntegrations',
		group: 'connect',
		path: 'connect.getConnectIntegrations',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'integrations'],
	},
	{
		code: 'BASELINKER_GET_COURIER_ACCOUNTS',
		title: 'Get Courier Accounts',
		description:
			'Tool to retrieve the list of accounts connected to a given courier. Use when you need to identify available courier accounts before performing shipping operations.',
		method: 'getCourierAccounts',
		group: 'couriers',
		path: 'couriers.getCourierAccounts',
		riskLevel: 'read',
		inputFields: ['courier_code'],
		outputFields: ['status', 'accounts'],
	},
	{
		code: 'BASELINKER_GET_COURIER_FIELDS',
		title: 'Get Courier Fields',
		description:
			'Tool to retrieve the form fields required for creating shipments with a specific courier. Use when you need to discover which fields are required or optional for shipment creation.',
		method: 'getCourierFields',
		group: 'couriers',
		path: 'couriers.getCourierFields',
		riskLevel: 'read',
		inputFields: ['courier_code'],
		outputFields: ['status', 'multi_packages', 'fields', 'package_fields'],
	},
	{
		code: 'BASELINKER_GET_COURIER_PACKAGES_STATUS_HISTORY',
		title: 'Get Courier Packages Status History',
		description:
			'Tool to retrieve the history of status changes for courier packages. Use when you need to track the delivery progress of shipments through their complete status timeline. Returns chronological status updates for up to 100 packages per request.',
		method: 'getCourierPackagesStatusHistory',
		group: 'couriers',
		path: 'couriers.getCourierPackagesStatusHistory',
		riskLevel: 'read',
		inputFields: ['package_ids'],
		outputFields: ['status', 'packages_history'],
	},
	{
		code: 'BASELINKER_GET_COURIERS_LIST',
		title: 'Get Couriers List',
		description:
			'Tool to retrieve a list of available couriers from BaseLinker. Use when you need to discover which shipping carriers are configured before creating packages or querying courier-specific fields.',
		method: 'getCouriersList',
		group: 'couriers',
		path: 'couriers.getCouriersList',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'couriers'],
	},
	{
		code: 'BASELINKER_GET_EXTERNAL_STORAGE_PRODUCTS_QUANTITY',
		title: 'Get External Storage Products Quantity',
		description:
			'Retrieve stock quantities from an external storage (shop/wholesaler) connected to BaseLinker. Use this tool to check current inventory levels for products in external integrations. Returns product IDs with their quantities, including variant-level stock if applicable.',
		method: 'getExternalStorageProductsQuantity',
		group: 'externalStorages',
		path: 'externalStorages.getExternalStorageProductsQuantity',
		riskLevel: 'read',
		inputFields: ['storage_id', 'page'],
		outputFields: ['status', 'storage_id', 'products'],
	},
	{
		code: 'BASELINKER_GET_EXTERNAL_STORAGES_LIST',
		title: 'Get External Storages List',
		description:
			"Retrieve a list of external storages (shops, warehouses, wholesalers) connected to BaseLinker that can be referenced via API. Returns storage IDs (e.g., 'shop_2444', 'warehouse_1334'), names, and supported API methods for each storage. Use this to discover available integrations before calling storage-specific methods like getExternalStorageProductsList.",
		method: 'getExternalStoragesList',
		group: 'externalStorages',
		path: 'externalStorages.getExternalStoragesList',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'storages'],
	},
	{
		code: 'BASELINKER_GET_INVENTORIES',
		title: 'Get Inventories',
		description:
			'Tool to retrieve a list of catalogs (inventories) available in the BaseLinker storage. Use when you need to discover available catalogs and their configurations before performing inventory-specific operations.',
		method: 'getInventories',
		group: 'inventory',
		path: 'inventory.getInventories',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'inventories'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_AVAILABLE_TEXT_FIELD_KEYS',
		title: 'Get Inventory Available Text Field Keys',
		description:
			'Tool to retrieve a list of product text fields that can be overwritten for a specific integration. Use when you need to discover which text fields are available for modification within a given inventory catalog.',
		method: 'getInventoryAvailableTextFieldKeys',
		group: 'inventory',
		path: 'inventory.getInventoryAvailableTextFieldKeys',
		riskLevel: 'read',
		inputFields: ['inventory_id'],
		outputFields: ['status', 'text_field_keys'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_CATEGORIES',
		title: 'Get Inventory Categories',
		description:
			'Tool to retrieve a list of categories for a BaseLinker catalog. Use when you need to fetch category hierarchies for inventory management or product organization.',
		method: 'getInventoryCategories',
		group: 'inventory',
		path: 'inventory.getInventoryCategories',
		riskLevel: 'read',
		inputFields: ['inventory_id'],
		outputFields: ['status', 'categories'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_DOCUMENT_ITEMS',
		title: 'Get Inventory Document Items',
		description:
			'Tool to retrieve items from inventory documents in BaseLinker. Use when you need to fetch product details from a specific document with support for pagination (100 items per page).',
		method: 'getInventoryDocumentItems',
		group: 'inventoryDocuments',
		path: 'inventoryDocuments.getInventoryDocumentItems',
		riskLevel: 'read',
		inputFields: ['document_id', 'page'],
		outputFields: ['status', 'items'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_DOCUMENT_SERIES',
		title: 'Get Inventory Document Series',
		description:
			'Tool to retrieve available inventory document series. Use when you need to assign a numbering series to a new inventory document.',
		method: 'getInventoryDocumentSeries',
		group: 'inventoryDocuments',
		path: 'inventoryDocuments.getInventoryDocumentSeries',
		riskLevel: 'read',
		inputFields: ['warehouse_id'],
		outputFields: ['status', 'document_series'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_DOCUMENTS',
		title: 'Get Inventory Documents',
		description:
			'Tool to retrieve a list of inventory documents. Use when you need to fetch inventory records with optional filters for ID, type, status, date range, warehouse, or pagination.',
		method: 'getInventoryDocuments',
		group: 'inventoryDocuments',
		path: 'inventoryDocuments.getInventoryDocuments',
		riskLevel: 'read',
		inputFields: [
			'filter_source_object_type',
			'filter_source_object_id',
			'filter_document_id',
			'filter_document_type',
			'filter_document_status',
			'filter_date_from',
			'filter_date_to',
			'filter_warehouse_id',
			'page',
		],
		outputFields: ['status', 'documents'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_EXTRA_FIELDS',
		title: 'Get Inventory Extra Fields',
		description:
			'Tool to retrieve extra fields defined for BaseLinker catalog inventory items. Use before fetching or updating inventory products to list available custom fields.',
		method: 'getInventoryExtraFields',
		group: 'inventory',
		path: 'inventory.getInventoryExtraFields',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'extra_fields'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_INTEGRATIONS',
		title: 'Get Inventory Integrations',
		description:
			'Tool to retrieve a list of integrations where text values in the catalog can be overwritten. Use when you need to discover which sales channels support text customization and what languages are available for each integration.',
		method: 'getInventoryIntegrations',
		group: 'inventory',
		path: 'inventory.getInventoryIntegrations',
		riskLevel: 'read',
		inputFields: ['inventory_id'],
		outputFields: ['status', 'integrations'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_MANUFACTURERS',
		title: 'Get Inventory Manufacturers',
		description:
			'Tool to retrieve a list of manufacturers from the BaseLinker catalog. Use when you need to view all manufacturers available in the system before adding or modifying manufacturer information.',
		method: 'getInventoryManufacturers',
		group: 'inventory',
		path: 'inventory.getInventoryManufacturers',
		riskLevel: 'read',
		inputFields: ['page'],
		outputFields: ['status', 'manufacturers'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PAYERS',
		title: 'Get Inventory Payers',
		description:
			'Tool to retrieve a list of payers available in BaseLinker storage. Use when you need to list payers, optionally filtered by ID or name.',
		method: 'getInventoryPayers',
		group: 'inventory',
		path: 'inventory.getInventoryPayers',
		riskLevel: 'read',
		inputFields: ['filter_id', 'filter_name'],
		outputFields: ['status', 'payers'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRICE_GROUPS',
		title: 'Get Inventory Price Groups',
		description:
			'Tool to retrieve price groups existing in BaseLinker storage. Use when you need to discover available pricing tiers before assigning them to inventory items or performing price-related operations.',
		method: 'getInventoryPriceGroups',
		group: 'inventory',
		path: 'inventory.getInventoryPriceGroups',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'price_groups'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRINTOUT_TEMPLATES',
		title: 'Get Inventory Printout Templates',
		description:
			'Tool to retrieve a list of all configured printout templates available for inventory (products). Use when you need to discover available printout templates before generating product documents.',
		method: 'getInventoryPrintoutTemplates',
		group: 'inventory',
		path: 'inventory.getInventoryPrintoutTemplates',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'printouts'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRODUCT_LOGS',
		title: 'Get Inventory Product Logs',
		description:
			'Tool to retrieve a list of events related to product changes in the BaseLinker catalog. Use when tracking product modification history, auditing changes, or monitoring inventory updates.',
		method: 'getInventoryProductLogs',
		group: 'inventory',
		path: 'inventory.getInventoryProductLogs',
		riskLevel: 'read',
		inputFields: [
			'product_id',
			'date_from',
			'date_to',
			'log_type',
			'sort',
			'page',
		],
		outputFields: ['status', 'logs'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRODUCTS_DATA',
		title: 'Get Inventory Products Data',
		description:
			'Tool to retrieve detailed data for selected products from the BaseLinker inventory. Use when you need comprehensive product information including SKU, prices, stock, dimensions, descriptions, images, variants, and bundle details.',
		method: 'getInventoryProductsData',
		group: 'inventory',
		path: 'inventory.getInventoryProductsData',
		riskLevel: 'read',
		inputFields: [
			'inventory_id',
			'products',
			'include_erp_units',
			'include_wms_units',
			'include_additional_eans',
			'include_suppliers',
			'include_relations',
			'include_marketplace_categories',
			'include_channels_media',
		],
		outputFields: ['status', 'products'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRODUCTS_LIST',
		title: 'Get Inventory Products List',
		description:
			'Tool to retrieve basic data of chosen products from BaseLinker catalogs. Use when you need to list products with optional filtering by ID, category, EAN, SKU, name, price range, or stock levels. Supports pagination for large catalogs (1000 products per page).',
		method: 'getInventoryProductsList',
		group: 'inventory',
		path: 'inventory.getInventoryProductsList',
		riskLevel: 'read',
		inputFields: [
			'inventory_id',
			'filter_id',
			'filter_category_id',
			'filter_ean',
			'filter_sku',
			'filter_name',
			'filter_price_from',
			'filter_price_to',
			'filter_stock_from',
			'filter_stock_to',
			'page',
			'filter_sort',
			'filter_locations',
			'include_variants',
		],
		outputFields: ['status', 'products'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRODUCTS_PRICES',
		title: 'Get Inventory Products Prices',
		description:
			'Retrieve gross prices of products from BaseLinker inventories. Use when you need to get pricing information for products and their variants across different price groups. Supports pagination for large product catalogs.',
		method: 'getInventoryProductsPrices',
		group: 'inventory',
		path: 'inventory.getInventoryProductsPrices',
		riskLevel: 'read',
		inputFields: ['inventory_id', 'page'],
		outputFields: ['status', 'products'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PRODUCTS_STOCK',
		title: 'Get Inventory Products Stock',
		description:
			'Tool to retrieve stock data of products from BaseLinker catalogs. Use when you need to check current inventory levels, reservations, or variant stock across warehouses. Results are paginated at 1000 products per page.',
		method: 'getInventoryProductsStock',
		group: 'inventory',
		path: 'inventory.getInventoryProductsStock',
		riskLevel: 'read',
		inputFields: [
			'inventory_id',
			'filter_id',
			'filter_category_id',
			'filter_ean',
			'filter_sku',
			'filter_name',
			'filter_asin',
			'filter_stock_from',
			'filter_stock_to',
			'page',
			'filter_sort',
			'filter_locations',
		],
		outputFields: ['status', 'products'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PURCHASE_ORDER_ITEMS',
		title: 'Get Inventory Purchase Order Items',
		description:
			'Tool to retrieve items from a specific purchase order in BaseLinker. Use when you need to fetch product details from a purchase order with support for pagination (100 items per page).',
		method: 'getInventoryPurchaseOrderItems',
		group: 'purchaseOrders',
		path: 'purchaseOrders.getInventoryPurchaseOrderItems',
		riskLevel: 'read',
		inputFields: ['order_id', 'page'],
		outputFields: ['status', 'items'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PURCHASE_ORDER_SERIES',
		title: 'Get Inventory Purchase Order Series',
		description:
			'Tool to retrieve a list of purchase order document series. Use when you need to select a numbering series for a new purchase order.',
		method: 'getInventoryPurchaseOrderSeries',
		group: 'purchaseOrders',
		path: 'purchaseOrders.getInventoryPurchaseOrderSeries',
		riskLevel: 'read',
		inputFields: ['warehouse_id'],
		outputFields: ['status', 'series'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_PURCHASE_ORDERS',
		title: 'Get Inventory Purchase Orders',
		description:
			'Tool to retrieve a list of purchase orders from BaseLinker storage. Use when you need to fetch purchase orders with optional filters like date range, supplier or pagination.',
		method: 'getInventoryPurchaseOrders',
		group: 'purchaseOrders',
		path: 'purchaseOrders.getInventoryPurchaseOrders',
		riskLevel: 'read',
		inputFields: [
			'warehouse_id',
			'supplier_id',
			'series_id',
			'date_from',
			'date_to',
			'filter_document_number',
			'filter_product_id',
			'page',
		],
		outputFields: ['status', 'purchase_orders'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_SUPPLIERS',
		title: 'Get Inventory Suppliers',
		description:
			'Tool to retrieve a list of suppliers available in BaseLinker storage. Use when you need to list suppliers, optionally filtered by ID or name.',
		method: 'getInventorySuppliers',
		group: 'inventory',
		path: 'inventory.getInventorySuppliers',
		riskLevel: 'read',
		inputFields: ['filter_id', 'filter_name'],
		outputFields: ['status', 'suppliers'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_TAGS',
		title: 'Get Inventory Tags',
		description:
			'Tool to retrieve a list of tags for a BaseLinker catalog. Use when you need to view all tags available in the system before categorizing or filtering inventory items.',
		method: 'getInventoryTags',
		group: 'inventory',
		path: 'inventory.getInventoryTags',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'tags'],
	},
	{
		code: 'BASELINKER_GET_INVENTORY_WAREHOUSES',
		title: 'Get Inventory Warehouses',
		description:
			'Tool to retrieve a list of warehouses available in BaseLinker inventories. Use when you need to discover available warehouse locations before performing inventory or stock operations. Returns warehouses created manually as well as those created automatically for external stocks (shops, wholesalers).',
		method: 'getInventoryWarehouses',
		group: 'inventory',
		path: 'inventory.getInventoryWarehouses',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'warehouses'],
	},
	{
		code: 'BASELINKER_GET_INVOICE_FILE',
		title: 'Get Invoice File',
		description:
			'Tool to retrieve an invoice file from BaseLinker in base64-encoded format. Use when you need to download an invoice document generated by BaseLinker or from an external accounting system.',
		method: 'getInvoiceFile',
		group: 'documents',
		path: 'documents.getInvoiceFile',
		riskLevel: 'read',
		inputFields: ['invoice_id', 'get_external'],
		outputFields: ['status', 'invoice', 'invoice_number'],
	},
	{
		code: 'BASELINKER_GET_INVOICES',
		title: 'Get Invoices',
		description:
			'Download invoices from BaseLinker order manager with optional filtering. Use this tool to: - Fetch all invoices from a specific date onwards - Retrieve a single invoice by ID or order ID - Filter invoices by numbering series - Paginate through invoices using id_from parameter Returns up to 100 invoices per request. Use getSeries to get available series IDs for filtering.',
		method: 'getInvoices',
		group: 'documents',
		path: 'documents.getInvoices',
		riskLevel: 'read',
		inputFields: [
			'invoice_id',
			'order_id',
			'date_from',
			'id_from',
			'series_id',
			'get_external_invoices',
			'get_government_data',
		],
		outputFields: ['status', 'invoices'],
	},
	{
		code: 'BASELINKER_GET_JOURNAL_LIST',
		title: 'Get Journal List',
		description:
			'Tool to download order event logs from the last 3 days. Use when you need to track order activities, changes, or events. IMPORTANT: This method must be activated by BaseLinker support on your account. If not activated, it returns an empty response. Events include order creation, status changes, payments, invoices, receipts, product modifications, and package operations. Use last_log_id to paginate through results incrementally.',
		method: 'getJournalList',
		group: 'orders',
		path: 'orders.getJournalList',
		riskLevel: 'read',
		inputFields: ['last_log_id', 'logs_types', 'order_id'],
		outputFields: ['status', 'logs'],
	},
	{
		code: 'BASELINKER_GET_NEW_RECEIPTS',
		title: 'Get New Receipts',
		description:
			'Tool to retrieve receipts waiting to be issued. Use after confirming fiscal printer availability; fetch pending receipts and mark them with setOrderReceipt.',
		method: 'getNewReceipts',
		group: 'documents',
		path: 'documents.getNewReceipts',
		riskLevel: 'read',
		inputFields: ['series_id', 'id_from'],
		outputFields: [
			'status',
			'orders',
			'receipt_id',
			'series_id',
			'receipt_full_nr',
			'order_id',
			'date_add',
			'payment_method',
			'nip',
			'products',
		],
	},
	{
		code: 'BASELINKER_GET_ORDER_EXTRA_FIELDS',
		title: 'Get Order Extra Fields',
		description:
			'Tool to retrieve extra fields defined for orders. Use before fetching orders with include_custom_extra_fields to list available custom order fields.',
		method: 'getOrderExtraFields',
		group: 'orders',
		path: 'orders.getOrderExtraFields',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'extra_fields'],
	},
	{
		code: 'BASELINKER_GET_ORDER_PACKAGES',
		title: 'Get Order Packages',
		description:
			'Tool to download shipments previously created for a selected order. Use when you need to retrieve tracking numbers, courier information, and delivery status for order packages.',
		method: 'getOrderPackages',
		group: 'couriers',
		path: 'couriers.getOrderPackages',
		riskLevel: 'read',
		inputFields: ['order_id'],
		outputFields: ['status', 'packages'],
	},
	{
		code: 'BASELINKER_GET_ORDER_PAYMENTS_HISTORY',
		title: 'Get Order Payments History',
		description:
			'Tool to retrieve payment history for a selected order, including external payment identifiers from payment gateways. Use when you need to track payment events for an order. One order can have multiple payment history entries due to surcharges, order value changes, or manual payment editing.',
		method: 'getOrderPaymentsHistory',
		group: 'orders',
		path: 'orders.getOrderPaymentsHistory',
		riskLevel: 'read',
		inputFields: ['order_id', 'show_full_history'],
		outputFields: ['status', 'payments'],
	},
	{
		code: 'BASELINKER_GET_ORDER_PICK_PACK_HISTORY',
		title: 'Get Order Pick Pack History',
		description:
			'Tool to retrieve pick and pack history for a selected order. Use when you need to track the fulfillment timeline and events for an order (reservations, picking, packing, photography). Returns chronological list of pick/pack events with timestamps and responsible profiles.',
		method: 'getOrderPickPackHistory',
		group: 'orders',
		path: 'orders.getOrderPickPackHistory',
		riskLevel: 'read',
		inputFields: ['order_id', 'action_type'],
		outputFields: ['status', 'history'],
	},
	{
		code: 'BASELINKER_GET_ORDER_PRINTOUT_TEMPLATES',
		title: 'Get Order Printout Templates',
		description:
			'Tool to retrieve a list of all configured printout templates available for orders. Use when you need to discover available printout templates before generating order documents.',
		method: 'getOrderPrintoutTemplates',
		group: 'orders',
		path: 'orders.getOrderPrintoutTemplates',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'printouts'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURN_EXTRA_FIELDS',
		title: 'Get Order Return Extra Fields',
		description:
			'Tool to retrieve extra fields defined for order returns. Use before calling getOrderReturns with include_custom_extra_fields to list available custom fields. Field values can be set via setOrderReturnFields.',
		method: 'getOrderReturnExtraFields',
		group: 'returns',
		path: 'returns.getOrderReturnExtraFields',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'extra_fields'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURN_JOURNAL_LIST',
		title: 'Get Order Return Journal List',
		description:
			'Tool to download return event logs from the last 3 days in BaseLinker. Use when tracking return order history, monitoring return status changes, or auditing return-related activities. Returns events like return creation, status changes, product modifications, and refund creation.',
		method: 'getOrderReturnJournalList',
		group: 'returns',
		path: 'returns.getOrderReturnJournalList',
		riskLevel: 'read',
		inputFields: ['last_log_id', 'logs_types', 'return_id'],
		outputFields: ['status', 'logs'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURN_PAYMENTS_HISTORY',
		title: 'Get Order Return Payments History',
		description:
			'Tool to retrieve payment history for a selected order return, including external payment identifiers from the payment gateway. Use when you need to track payment events, surcharges, order value changes, or manual payment edits for a return.',
		method: 'getOrderReturnPaymentsHistory',
		group: 'returns',
		path: 'returns.getOrderReturnPaymentsHistory',
		riskLevel: 'read',
		inputFields: ['return_id', 'show_full_history'],
		outputFields: ['status', 'payments'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURN_PRODUCT_STATUSES',
		title: 'Get Order Return Product Statuses',
		description:
			'Tool to retrieve a list of order return product statuses from BaseLinker. Use when you need to identify valid status IDs for return items, or to map status IDs to human-readable names.',
		method: 'getOrderReturnProductStatuses',
		group: 'returns',
		path: 'returns.getOrderReturnProductStatuses',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'order_return_product_statuses'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURN_REASONS_LIST',
		title: 'Get Order Return Reasons List',
		description:
			'Tool to retrieve a list of order return reasons. Use when you need to discover available return reasons before setting return fields with setOrderReturnFields.',
		method: 'getOrderReturnReasonsList',
		group: 'returns',
		path: 'returns.getOrderReturnReasonsList',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'return_reasons'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURN_STATUS_LIST',
		title: 'Get Order Return Status List',
		description:
			'Tool to retrieve order return statuses created in the BaseLinker order manager. Use when you need to map return status IDs to human-readable names.',
		method: 'getOrderReturnStatusList',
		group: 'returns',
		path: 'returns.getOrderReturnStatusList',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'statuses'],
	},
	{
		code: 'BASELINKER_GET_ORDER_RETURNS',
		title: 'Get Order Returns',
		description:
			'Download order returns from BaseLinker return manager with optional filtering. Use this tool to: - Fetch returns from a specific date onwards using date_from parameter - Retrieve a single return by return_id - Filter returns by source order, status, or marketplace source - Paginate through returns using id_from parameter Returns up to 100 order returns per request. For complete return data including custom fields, set include_custom_extra_fields=true. Use include_connect_data=true for Base Connect integration info.',
		method: 'getOrderReturns',
		group: 'returns',
		path: 'returns.getOrderReturns',
		riskLevel: 'read',
		inputFields: [
			'order_id',
			'return_id',
			'date_from',
			'id_from',
			'status_id',
			'filter_order_return_source',
			'filter_order_return_source_id',
			'include_custom_extra_fields',
			'include_connect_data',
		],
		outputFields: ['status', 'returns'],
	},
	{
		code: 'BASELINKER_GET_ORDER_SOURCES',
		title: 'Get Order Sources',
		description:
			'Tool to retrieve types of order sources along with their IDs from BaseLinker. Use when you need to understand available order sources for filtering orders or mapping order_source field values from getOrders method.',
		method: 'getOrderSources',
		group: 'orders',
		path: 'orders.getOrderSources',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'sources'],
	},
	{
		code: 'BASELINKER_GET_ORDER_STATUS_LIST',
		title: 'Get Order Status List',
		description:
			'Tool to retrieve a list of order statuses created in the BaseLinker order manager. Use when you need to map status IDs to human-readable names.',
		method: 'getOrderStatusList',
		group: 'orders',
		path: 'orders.getOrderStatusList',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'statuses'],
	},
	{
		code: 'BASELINKER_GET_ORDER_TRANSACTION_DATA',
		title: 'Get Order Transaction Data',
		description:
			'Tool to retrieve transaction details for a selected order. Use when you need marketplace transaction IDs, fulfillment data, or detailed tax breakdowns for an order.',
		method: 'getOrderTransactionData',
		group: 'orders',
		path: 'orders.getOrderTransactionData',
		riskLevel: 'read',
		inputFields: ['order_id', 'include_complex_taxes', 'include_amazon_data'],
		outputFields: [
			'status',
			'currency',
			'fulfillment_shipments',
			'fulfillment_center_id',
			'ship_date_from',
			'ship_date_to',
			'delivery_date_from',
			'delivery_date_to',
			'marketplace_transaction_id',
			'account_id',
			'transaction_date',
			'order_items',
		],
	},
	{
		code: 'BASELINKER_GET_ORDERS',
		title: 'Get Orders',
		description:
			'Download orders from BaseLinker order manager with optional filtering. Use this tool to: - Fetch all orders from a specific date onwards - Retrieve a single order by ID - Filter orders by status, email, or marketplace source - Paginate through orders using id_from parameter Returns up to 100 orders per request. For confirmed orders only, omit get_unconfirmed_orders. Tip: Use getOrderStatusList to get status IDs for filtering.',
		method: 'getOrders',
		group: 'orders',
		path: 'orders.getOrders',
		riskLevel: 'read',
		inputFields: [
			'order_id',
			'date_confirmed_from',
			'date_from',
			'id_from',
			'get_unconfirmed_orders',
			'status_id',
			'filter_email',
			'filter_order_source',
			'filter_order_source_id',
			'filter_shop_order_id',
			'filter_external_order_id',
			'include_custom_extra_fields',
			'include_commissions',
			'include_connect_data',
			'include_discounts_data',
		],
		outputFields: ['status', 'orders'],
	},
	{
		code: 'BASELINKER_GET_ORDERS_BY_PHONE',
		title: 'Get Orders by Phone',
		description:
			'Search for orders associated with a specific phone number in BaseLinker. Use when identifying callers in phone recognition systems or finding order history by phone. Returns basic order information including status, recipient names, and timestamps.',
		method: 'getOrdersByPhone',
		group: 'orders',
		path: 'orders.getOrdersByPhone',
		riskLevel: 'read',
		inputFields: ['phone'],
		outputFields: ['status', 'orders'],
	},
	{
		code: 'BASELINKER_GET_PACKAGE_DETAILS',
		title: 'Get Package Details',
		description:
			'Tool to get detailed information about a package. If the package contains multiple subpackages, information about all of them is included in the response. Use when you need comprehensive package dimensions, weight, COD, insurance, and shipping cost details.',
		method: 'getPackageDetails',
		group: 'couriers',
		path: 'couriers.getPackageDetails',
		riskLevel: 'read',
		inputFields: ['package_id'],
		outputFields: ['status', 'package_details'],
	},
	{
		code: 'BASELINKER_GET_PICK_PACK_CARTS',
		title: 'Get PickPack Carts',
		description:
			'Tool to retrieve a list of all PickPack carts belonging to the authenticated user. Use when you need to discover available carts and their details (ID, name, color) before performing cart-specific operations.',
		method: 'getPickPackCarts',
		group: 'orders',
		path: 'orders.getPickPackCarts',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'carts'],
	},
	{
		code: 'BASELINKER_GET_PROTOCOL',
		title: 'Get Protocol',
		description:
			'Tool to download a parcel protocol for selected shipments. Use when you need to retrieve shipping protocol documents (PDF or HTML) for packages sent via a courier. The protocol is available only if supported by the chosen courier.',
		method: 'getProtocol',
		group: 'couriers',
		path: 'couriers.getProtocol',
		riskLevel: 'read',
		inputFields: [
			'courier_code',
			'package_ids',
			'package_numbers',
			'account_id',
		],
		outputFields: ['status', 'extension', 'protocol'],
	},
	{
		code: 'BASELINKER_GET_RECEIPTS',
		title: 'Get Receipts',
		description:
			'Tool to retrieve issued receipts from BaseLinker. Use when you need to fetch historical receipt data. Max 100 receipts returned per request.',
		method: 'getReceipts',
		group: 'documents',
		path: 'documents.getReceipts',
		riskLevel: 'read',
		inputFields: ['series_id', 'id_from', 'date_from', 'date_to'],
		outputFields: ['status', 'receipts'],
	},
	{
		code: 'BASELINKER_GET_REQUEST_PARCEL_PICKUP_FIELDS',
		title: 'Get Request Parcel Pickup Fields',
		description:
			'Tool to retrieve additional fields for a parcel pickup request from a specific courier. Use when preparing to request a parcel pickup and need to know which additional information the courier requires (e.g., pickup time, contact details, special instructions).',
		method: 'getRequestParcelPickupFields',
		group: 'couriers',
		path: 'couriers.getRequestParcelPickupFields',
		riskLevel: 'read',
		inputFields: ['courier_code'],
		outputFields: ['status', 'fields'],
	},
	{
		code: 'BASELINKER_GET_SERIES',
		title: 'Get Series',
		description:
			'Tool to download invoice/receipt numbering series. Use when you need to retrieve all series configurations before issuing documents.',
		method: 'getSeries',
		group: 'documents',
		path: 'documents.getSeries',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'series'],
	},
	{
		code: 'BASELINKER_GET_STORAGES_LIST',
		title: 'Get Storages List',
		description:
			'Tool to download a list of available storages accessible via API. Use when you need to discover storage endpoints and capabilities before performing storage-specific operations.',
		method: 'getStoragesList',
		group: 'externalStorages',
		path: 'externalStorages.getStoragesList',
		riskLevel: 'read',
		inputFields: [],
		outputFields: ['status', 'storages'],
	},
	{
		code: 'BASELINKER_RUN_ORDER_MACRO_TRIGGER',
		title: 'Run Order Macro Trigger',
		description:
			'Tool to run personal trigger for orders automatic actions. Use when you need to execute a specific automation trigger on an order.',
		method: 'runOrderMacroTrigger',
		group: 'orders',
		path: 'orders.runOrderMacroTrigger',
		riskLevel: 'write',
		inputFields: ['order_id', 'trigger_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_RUN_PRODUCT_MACRO_TRIGGER',
		title: 'Run Product Macro Trigger',
		description:
			'Tool to execute a personal trigger for products automatic actions. Use when you need to manually run a custom event trigger for a specific product in BaseLinker inventory.',
		method: 'runProductMacroTrigger',
		group: 'inventory',
		path: 'inventory.runProductMacroTrigger',
		riskLevel: 'write',
		inputFields: ['product_id', 'trigger_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_RUN_REQUEST_PARCEL_PICKUP',
		title: 'Run Request Parcel Pickup',
		description:
			'Tool to request a parcel pickup for previously created shipments. Use when you need to schedule a courier pickup for packages that have been created. The method sends a pickup request to the courier API if the courier supports it. Use getRequestParcelPickupFields first to check if the courier requires additional fields.',
		method: 'runRequestParcelPickup',
		group: 'couriers',
		path: 'couriers.runRequestParcelPickup',
		riskLevel: 'write',
		inputFields: [
			'courier_code',
			'package_ids',
			'package_numbers',
			'account_id',
			'fields',
		],
		outputFields: ['status', 'pickup_number'],
	},
	{
		code: 'BASELINKER_SET_INVENTORY_PURCHASE_ORDER_STATUS',
		title: 'Set Inventory Purchase Order Status',
		description:
			"Tool to change the status of a purchase order in BaseLinker inventory. Use when you need to update a purchase order's status (e.g., mark as sent, received, completed, or canceled).",
		method: 'setInventoryPurchaseOrderStatus',
		group: 'purchaseOrders',
		path: 'purchaseOrders.setInventoryPurchaseOrderStatus',
		riskLevel: 'write',
		inputFields: ['order_id', 'status', 'completed_items'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_FIELDS',
		title: 'Set Order Fields',
		description:
			'Tool to edit selected fields of a specific order in BaseLinker. Use when you need to update order details such as address data, notes, payment method, delivery information, or invoice details. Only provide the fields you want to change; other fields can be omitted.',
		method: 'setOrderFields',
		group: 'orders',
		path: 'orders.setOrderFields',
		riskLevel: 'write',
		inputFields: [
			'order_id',
			'admin_comments',
			'user_comments',
			'payment_method',
			'payment_method_cod',
			'email',
			'phone',
			'user_login',
			'delivery_method',
			'delivery_price',
			'delivery_fullname',
			'delivery_company',
			'delivery_address',
			'delivery_postcode',
			'delivery_city',
			'delivery_state',
			'delivery_country_code',
			'delivery_point_id',
			'delivery_point_name',
			'delivery_point_address',
			'delivery_point_postcode',
			'delivery_point_city',
			'invoice_fullname',
			'invoice_company',
			'invoice_nip',
			'invoice_address',
			'invoice_postcode',
			'invoice_city',
			'invoice_state',
			'invoice_country_code',
			'want_invoice',
			'extra_field_1',
			'extra_field_2',
			'custom_extra_fields',
			'pick_state',
			'pack_state',
			'star',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_PAYMENT',
		title: 'Set Order Payment',
		description:
			'Tool to add a payment to an order in BaseLinker. Use when recording a payment for an order. The payment amount replaces (not adds to) the current payment value; if it matches the order total, the order is marked as paid.',
		method: 'setOrderPayment',
		group: 'orders',
		path: 'orders.setOrderPayment',
		riskLevel: 'write',
		inputFields: [
			'order_id',
			'payment_done',
			'payment_date',
			'payment_comment',
			'external_payment_id',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_PRODUCT_FIELDS',
		title: 'Set Order Product Fields',
		description:
			'Tool to edit data of selected items in a specific BaseLinker order. Use when you need to update product fields like prices, quantities, SKU, or other item details. Only provide the fields you want to edit; other fields can be omitted.',
		method: 'setOrderProductFields',
		group: 'orders',
		path: 'orders.setOrderProductFields',
		riskLevel: 'write',
		inputFields: [
			'order_id',
			'order_product_id',
			'storage',
			'storage_id',
			'product_id',
			'variant_id',
			'auction_id',
			'name',
			'sku',
			'ean',
			'location',
			'warehouse_id',
			'attributes',
			'price_brutto',
			'tax_rate',
			'quantity',
			'weight',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_RECEIPT',
		title: 'Set Order Receipt',
		description:
			'Tool to mark orders with a receipt already issued. Use after printing receipts retrieved from getNewReceipts to confirm receipt issuance.',
		method: 'setOrderReceipt',
		group: 'documents',
		path: 'documents.setOrderReceipt',
		riskLevel: 'write',
		inputFields: [
			'receipt_id',
			'receipt_nr',
			'date',
			'printer_error',
			'printer_name',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_RETURN_FIELDS',
		title: 'Set Order Return Fields',
		description:
			'Tool to edit selected fields of a specific order return. Use when updating return information such as buyer contact details, delivery address, or custom fields. Only the fields that need to be changed should be provided; other fields can be omitted.',
		method: 'setOrderReturnFields',
		group: 'returns',
		path: 'returns.setOrderReturnFields',
		riskLevel: 'write',
		inputFields: [
			'return_id',
			'admin_comments',
			'email',
			'phone',
			'user_login',
			'delivery_price',
			'delivery_fullname',
			'delivery_company',
			'delivery_address',
			'delivery_postcode',
			'delivery_city',
			'delivery_state',
			'delivery_country_code',
			'extra_field_1',
			'extra_field_2',
			'custom_extra_fields',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_RETURN_PRODUCT_FIELDS',
		title: 'Set Order Return Product Fields',
		description:
			'Tool to edit data of selected items (e.g., prices, quantities, attributes) of a specific order return product. Use when you need to update fields of a returned product in an order return.',
		method: 'setOrderReturnProductFields',
		group: 'returns',
		path: 'returns.setOrderReturnProductFields',
		riskLevel: 'write',
		inputFields: [
			'return_id',
			'order_return_product_id',
			'storage',
			'storage_id',
			'product_id',
			'variant_id',
			'auction_id',
			'name',
			'sku',
			'ean',
			'location',
			'warehouse_id',
			'attributes',
			'price_brutto',
			'tax_rate',
			'quantity',
			'weight',
			'status_id',
			'return_reason_id',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_RETURN_REFUND',
		title: 'Set Order Return Refund',
		description:
			"Tool to mark an order return as refunded in BaseLinker. Use when recording that a refund has been issued for a return. Note: This method doesn't issue an actual money refund - it only updates the refund status in BaseLinker.",
		method: 'setOrderReturnRefund',
		group: 'returns',
		path: 'returns.setOrderReturnRefund',
		riskLevel: 'write',
		inputFields: [
			'return_id',
			'order_refund_done',
			'refund_date',
			'refund_comment',
			'external_refund_id',
		],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_RETURN_STATUS',
		title: 'Set Order Return Status',
		description:
			'Tool to change order return status in BaseLinker. Use when you need to update the status of a single order return.',
		method: 'setOrderReturnStatus',
		group: 'returns',
		path: 'returns.setOrderReturnStatus',
		riskLevel: 'write',
		inputFields: ['return_id', 'status_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_RETURN_STATUSES',
		title: 'Set Order Return Statuses',
		description:
			'Tool to batch set order return statuses in BaseLinker. Use when you need to update the status of multiple order returns at once.',
		method: 'setOrderReturnStatuses',
		group: 'returns',
		path: 'returns.setOrderReturnStatuses',
		riskLevel: 'write',
		inputFields: ['return_ids', 'status_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_STATUS',
		title: 'Set Order Status',
		description:
			"Tool to change the status of an existing order in BaseLinker. Use when you need to update an order's status to a different value.",
		method: 'setOrderStatus',
		group: 'orders',
		path: 'orders.setOrderStatus',
		riskLevel: 'write',
		inputFields: ['order_id', 'status_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDER_STATUSES',
		title: 'Set Order Statuses',
		description:
			'Tool to batch update order statuses in BaseLinker. Use when you need to set the same status for multiple orders at once.',
		method: 'setOrderStatuses',
		group: 'orders',
		path: 'orders.setOrderStatuses',
		riskLevel: 'write',
		inputFields: ['order_ids', 'status_id'],
		outputFields: ['status'],
	},
	{
		code: 'BASELINKER_SET_ORDERS_MERGE',
		title: 'Set Orders Merge',
		description:
			'Tool to merge multiple orders into one, based on the selected merge mode. Use when you need to combine orders together with either technical merge or into main order mode.',
		method: 'setOrdersMerge',
		group: 'orders',
		path: 'orders.setOrdersMerge',
		riskLevel: 'destructive',
		inputFields: [
			'main_order_id',
			'order_ids_to_merge',
			'merge_mode',
			'sum_delivery_costs',
		],
		outputFields: ['status', 'merged_order_id'],
	},
	{
		code: 'BASELINKER_UPDATE_INVENTORY_PRODUCTS_STOCK',
		title: 'Update Inventory Products Stock',
		description:
			'Tool to update stocks of products and their variants in BaseLinker catalog. Use when you need to modify inventory levels for products across warehouses. Maximum 1000 products per request.',
		method: 'updateInventoryProductsStock',
		group: 'inventory',
		path: 'inventory.updateInventoryProductsStock',
		riskLevel: 'write',
		inputFields: ['inventory_id', 'products'],
		outputFields: ['status', 'counter', 'warnings'],
	},
] as const;

export type BaseLinkerOperation = (typeof baseLinkerOperationCatalog)[number];
export type BaseLinkerMethod = BaseLinkerOperation['method'];
export type BaseLinkerOperationPath = BaseLinkerOperation['path'];

export const baseLinkerReadOperationPaths = new Set<BaseLinkerOperationPath>(
	baseLinkerOperationCatalog
		.filter((operation) => operation.riskLevel === 'read')
		.map((operation) => operation.path),
);
