import {
	ActiveCampaignAccount,
	ActiveCampaignAccountContact,
	ActiveCampaignAccountCustomFieldMeta,
	ActiveCampaignAddress,
	ActiveCampaignAutomation,
	ActiveCampaignBranding,
	ActiveCampaignCalendar,
	ActiveCampaignCampaign,
	ActiveCampaignConnection,
	ActiveCampaignContact,
	ActiveCampaignContactList,
	ActiveCampaignContactTag,
	ActiveCampaignCustomObjectSchema,
	ActiveCampaignDeal,
	ActiveCampaignDealCustomFieldMeta,
	ActiveCampaignDealGroup,
	ActiveCampaignDealRole,
	ActiveCampaignDealStage,
	ActiveCampaignDealTask,
	ActiveCampaignDealTaskType,
	ActiveCampaignEcomCustomer,
	ActiveCampaignEventTrackingEvent,
	ActiveCampaignField,
	ActiveCampaignFieldOption,
	ActiveCampaignFieldRel,
	ActiveCampaignFieldValue,
	ActiveCampaignForm,
	ActiveCampaignGroup,
	ActiveCampaignGroupLimit,
	ActiveCampaignGroupMember,
	ActiveCampaignList,
	ActiveCampaignListGroup,
	ActiveCampaignMessage,
	ActiveCampaignNote,
	ActiveCampaignPersonalization,
	ActiveCampaignSavedResponse,
	ActiveCampaignScore,
	ActiveCampaignSegment,
	ActiveCampaignTag,
	ActiveCampaignTaskOutcome,
	ActiveCampaignTemplate,
	ActiveCampaignUser,
	ActiveCampaignWebhook,
} from './database';

/**
 * Entities mirrored into the local store.
 *
 * All of these are reference data - records that are created once and updated
 * in place, which an agent needs to resolve ids and to segment on.
 *
 * Deliberately absent, because they are transactional rather than reference:
 * deal activities, email activities, contact automations, e-commerce orders,
 * order products and order activities, campaign links, and the account config
 * key/value store. Those are appended continuously and are only meaningful
 * against a date range, so mirroring them would grow without bound while
 * answering nothing a live call cannot.
 */
export const ActiveCampaignSchema = {
	version: '1.0.0',
	entities: {
		// Contacts and their attributes
		contacts: ActiveCampaignContact,
		lists: ActiveCampaignList,
		tags: ActiveCampaignTag,
		fields: ActiveCampaignField,
		contactLists: ActiveCampaignContactList,
		contactTags: ActiveCampaignContactTag,
		fieldValues: ActiveCampaignFieldValue,
		fieldOptions: ActiveCampaignFieldOption,
		fieldRels: ActiveCampaignFieldRel,
		groupMembers: ActiveCampaignGroupMember,
		listGroups: ActiveCampaignListGroup,
		// CRM
		deals: ActiveCampaignDeal,
		dealGroups: ActiveCampaignDealGroup,
		dealStages: ActiveCampaignDealStage,
		dealTasks: ActiveCampaignDealTask,
		dealTaskTypes: ActiveCampaignDealTaskType,
		dealRoles: ActiveCampaignDealRole,
		taskOutcomes: ActiveCampaignTaskOutcome,
		dealCustomFieldMeta: ActiveCampaignDealCustomFieldMeta,
		accounts: ActiveCampaignAccount,
		accountContacts: ActiveCampaignAccountContact,
		accountCustomFieldMeta: ActiveCampaignAccountCustomFieldMeta,
		// Content
		notes: ActiveCampaignNote,
		campaigns: ActiveCampaignCampaign,
		messages: ActiveCampaignMessage,
		templates: ActiveCampaignTemplate,
		savedResponses: ActiveCampaignSavedResponse,
		forms: ActiveCampaignForm,
		personalizations: ActiveCampaignPersonalization,
		// Automations and segments
		automations: ActiveCampaignAutomation,
		segments: ActiveCampaignSegment,
		// E-commerce reference data
		connections: ActiveCampaignConnection,
		ecomCustomers: ActiveCampaignEcomCustomer,
		// Custom objects
		customObjectSchemas: ActiveCampaignCustomObjectSchema,
		// Account administration
		users: ActiveCampaignUser,
		groups: ActiveCampaignGroup,
		groupLimits: ActiveCampaignGroupLimit,
		addresses: ActiveCampaignAddress,
		calendars: ActiveCampaignCalendar,
		scores: ActiveCampaignScore,
		brandings: ActiveCampaignBranding,
		webhooks: ActiveCampaignWebhook,
		eventTrackingEvents: ActiveCampaignEventTrackingEvent,
	},
} as const;

export type {
	ActiveCampaignAccount,
	ActiveCampaignAccountContact,
	ActiveCampaignAddress,
	ActiveCampaignAutomation,
	ActiveCampaignBranding,
	ActiveCampaignCalendar,
	ActiveCampaignCampaign,
	ActiveCampaignConnection,
	ActiveCampaignContact,
	ActiveCampaignContactList,
	ActiveCampaignContactTag,
	ActiveCampaignCustomObjectSchema,
	ActiveCampaignDeal,
	ActiveCampaignDealCustomFieldMeta,
	ActiveCampaignDealGroup,
	ActiveCampaignDealRole,
	ActiveCampaignDealStage,
	ActiveCampaignDealTask,
	ActiveCampaignDealTaskType,
	ActiveCampaignEcomCustomer,
	ActiveCampaignEventTrackingEvent,
	ActiveCampaignField,
	ActiveCampaignFieldOption,
	ActiveCampaignFieldRel,
	ActiveCampaignFieldValue,
	ActiveCampaignForm,
	ActiveCampaignGroup,
	ActiveCampaignGroupLimit,
	ActiveCampaignGroupMember,
	ActiveCampaignList,
	ActiveCampaignListGroup,
	ActiveCampaignMessage,
	ActiveCampaignNote,
	ActiveCampaignPersonalization,
	ActiveCampaignSavedResponse,
	ActiveCampaignScore,
	ActiveCampaignSegment,
	ActiveCampaignTag,
	ActiveCampaignTaskOutcome,
	ActiveCampaignTemplate,
	ActiveCampaignUser,
	ActiveCampaignWebhook,
} from './database';
