/**
 * The operation registry as data, shared by every suite. Generated from the
 * same map that generates the handlers, so the two cannot drift.
 */
export const OPERATION_TABLE = [
	{
		key: 'monitors.create',
		slug: 'BETTER_STACK_CREATE_MONITOR',
		group: 'monitors',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/monitors',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'monitors.get',
		slug: 'BETTER_STACK_GET_MONITOR',
		group: 'monitors',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitors/{monitor_id}',
		tier: 'read',
		pathParams: ['monitor_id'] as const,
	},
	{
		key: 'monitors.list',
		slug: 'BETTER_STACK_LIST_MONITORS',
		group: 'monitors',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitors',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'monitors.update',
		slug: 'BETTER_STACK_UPDATE_MONITOR',
		group: 'monitors',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/monitors/{monitor_id}',
		tier: 'write',
		pathParams: ['monitor_id'] as const,
	},
	{
		key: 'monitors.remove',
		slug: 'BETTER_STACK_DELETE_MONITOR',
		group: 'monitors',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/monitors/{monitor_id}',
		tier: 'destructive',
		pathParams: ['monitor_id'] as const,
	},
	{
		key: 'monitors.availability',
		slug: 'BETTER_STACK_GET_MONITOR_AVAILABILITY',
		group: 'monitors',
		handler: 'availability',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitors/{monitor_id}/sla',
		tier: 'read',
		pathParams: ['monitor_id'] as const,
	},
	{
		key: 'monitors.responseTimes',
		slug: 'BETTER_STACK_GET_MONITOR_RESPONSE_TIMES',
		group: 'monitors',
		handler: 'responseTimes',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitors/{monitor_id}/response-times',
		tier: 'read',
		pathParams: ['monitor_id'] as const,
	},
	{
		key: 'monitorGroups.create',
		slug: 'BETTER_STACK_CREATE_MONITOR_GROUP',
		group: 'monitorGroups',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/monitor-groups',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'monitorGroups.get',
		slug: 'BETTER_STACK_GET_MONITOR_GROUPS',
		group: 'monitorGroups',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitor-groups/{monitor_group_id}',
		tier: 'read',
		pathParams: ['monitor_group_id'] as const,
	},
	{
		key: 'monitorGroups.list',
		slug: 'BETTER_STACK_LIST_MONITOR_GROUPS',
		group: 'monitorGroups',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitor-groups',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'monitorGroups.update',
		slug: 'BETTER_STACK_UPDATE_MONITOR_GROUP',
		group: 'monitorGroups',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/monitor-groups/{monitor_group_id}',
		tier: 'write',
		pathParams: ['monitor_group_id'] as const,
	},
	{
		key: 'monitorGroups.remove',
		slug: 'BETTER_STACK_DELETE_MONITOR_GROUP',
		group: 'monitorGroups',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/monitor-groups/{monitor_group_id}',
		tier: 'destructive',
		pathParams: ['monitor_group_id'] as const,
	},
	{
		key: 'monitorGroups.monitors',
		slug: 'BETTER_STACK_GET_MONITOR_GROUPS_MONITORS',
		group: 'monitorGroups',
		handler: 'monitors',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/monitor-groups/{monitor_group_id}/monitors',
		tier: 'read',
		pathParams: ['monitor_group_id'] as const,
	},
	{
		key: 'heartbeats.create',
		slug: 'BETTER_STACK_CREATE_HEARTBEAT',
		group: 'heartbeats',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/heartbeats',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'heartbeats.get',
		slug: 'BETTER_STACK_GET_HEARTBEAT',
		group: 'heartbeats',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/heartbeats/{heartbeat_id}',
		tier: 'read',
		pathParams: ['heartbeat_id'] as const,
	},
	{
		key: 'heartbeats.list',
		slug: 'BETTER_STACK_LIST_HEARTBEATS',
		group: 'heartbeats',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/heartbeats',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'heartbeats.update',
		slug: 'BETTER_STACK_UPDATE_HEARTBEAT',
		group: 'heartbeats',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/heartbeats/{heartbeat_id}',
		tier: 'write',
		pathParams: ['heartbeat_id'] as const,
	},
	{
		key: 'heartbeats.remove',
		slug: 'BETTER_STACK_DELETE_HEARTBEAT',
		group: 'heartbeats',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/heartbeats/{heartbeat_id}',
		tier: 'destructive',
		pathParams: ['heartbeat_id'] as const,
	},
	{
		key: 'heartbeats.availability',
		slug: 'BETTER_STACK_GET_HEARTBEAT_AVAILABILITY',
		group: 'heartbeats',
		handler: 'availability',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/heartbeats/{heartbeat_id}/availability',
		tier: 'read',
		pathParams: ['heartbeat_id'] as const,
	},
	{
		key: 'heartbeatGroups.create',
		slug: 'BETTER_STACK_CREATE_HEARTBEAT_GROUP',
		group: 'heartbeatGroups',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/heartbeat-groups',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'heartbeatGroups.get',
		slug: 'BETTER_STACK_GET_HEARTBEAT_GROUP',
		group: 'heartbeatGroups',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/heartbeat-groups/{heartbeat_group_id}',
		tier: 'read',
		pathParams: ['heartbeat_group_id'] as const,
	},
	{
		key: 'heartbeatGroups.list',
		slug: 'BETTER_STACK_LIST_HEARTBEAT_GROUPS',
		group: 'heartbeatGroups',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/heartbeat-groups',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'heartbeatGroups.update',
		slug: 'BETTER_STACK_UPDATE_HEARTBEAT_GROUP',
		group: 'heartbeatGroups',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/heartbeat-groups/{heartbeat_group_id}',
		tier: 'write',
		pathParams: ['heartbeat_group_id'] as const,
	},
	{
		key: 'heartbeatGroups.remove',
		slug: 'BETTER_STACK_DELETE_HEARTBEAT_GROUP',
		group: 'heartbeatGroups',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/heartbeat-groups/{heartbeat_group_id}',
		tier: 'destructive',
		pathParams: ['heartbeat_group_id'] as const,
	},
	{
		key: 'incidents.create',
		slug: 'BETTER_STACK_CREATE_INCIDENT',
		group: 'incidents',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v3/incidents',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'incidents.get',
		slug: 'BETTER_STACK_LIST_SINGLE_INCIDENT',
		group: 'incidents',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v3/incidents/{incident_id}',
		tier: 'read',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidents.list',
		slug: 'BETTER_STACK_LIST_INCIDENTS_UPTIME',
		group: 'incidents',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v3/incidents',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'incidents.remove',
		slug: 'BETTER_STACK_DELETE_INCIDENT',
		group: 'incidents',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v3/incidents/{incident_id}',
		tier: 'destructive',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidents.acknowledge',
		slug: 'BETTER_STACK_ACKNOWLEDGE_INCIDENT',
		group: 'incidents',
		handler: 'acknowledge',
		api: 'uptime',
		method: 'POST',
		path: '/api/v3/incidents/{incident_id}/acknowledge',
		tier: 'write',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidents.resolve',
		slug: 'BETTER_STACK_RESOLVE_INCIDENT',
		group: 'incidents',
		handler: 'resolve',
		api: 'uptime',
		method: 'POST',
		path: '/api/v3/incidents/{incident_id}/resolve',
		tier: 'write',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidents.escalate',
		slug: 'BETTER_STACK_ESCALATE_INCIDENT',
		group: 'incidents',
		handler: 'escalate',
		api: 'uptime',
		method: 'POST',
		path: '/api/v3/incidents/{incident_id}/escalate',
		tier: 'write',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidents.timeline',
		slug: 'BETTER_STACK_LIST_INCIDENTS_TIMELINE',
		group: 'incidents',
		handler: 'timeline',
		api: 'uptime',
		method: 'GET',
		path: '/api/v3/incidents/{incident_id}/timeline',
		tier: 'read',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidentComments.create',
		slug: 'BETTER_STACK_CREATE_INCIDENT_COMMENT',
		group: 'incidentComments',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/incidents/{incident_id}/comments',
		tier: 'write',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidentComments.get',
		slug: 'BETTER_STACK_GET_INCIDENT_COMMENT',
		group: 'incidentComments',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/incidents/{incident_id}/comments/{comment_id}',
		tier: 'read',
		pathParams: ['incident_id', 'comment_id'] as const,
	},
	{
		key: 'incidentComments.list',
		slug: 'BETTER_STACK_LIST_INCIDENTS_COMMENTS',
		group: 'incidentComments',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/incidents/{incident_id}/comments',
		tier: 'read',
		pathParams: ['incident_id'] as const,
	},
	{
		key: 'incidentComments.update',
		slug: 'BETTER_STACK_UPDATE_INCIDENT_COMMENT',
		group: 'incidentComments',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/incidents/{incident_id}/comments/{comment_id}',
		tier: 'write',
		pathParams: ['incident_id', 'comment_id'] as const,
	},
	{
		key: 'incidentComments.remove',
		slug: 'BETTER_STACK_DELETE_INCIDENT_COMMENT',
		group: 'incidentComments',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/incidents/{incident_id}/comments/{comment_id}',
		tier: 'destructive',
		pathParams: ['incident_id', 'comment_id'] as const,
	},
	{
		key: 'policies.create',
		slug: 'BETTER_STACK_CREATE_ESCALATION_POLICY',
		group: 'policies',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v3/policies',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'policies.get',
		slug: 'BETTER_STACK_GET_ESCALATION_POLICY',
		group: 'policies',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v3/policies/{policy_id}',
		tier: 'read',
		pathParams: ['policy_id'] as const,
	},
	{
		key: 'policies.list',
		slug: 'BETTER_STACK_LIST_POLICIES',
		group: 'policies',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v3/policies',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'policies.update',
		slug: 'BETTER_STACK_UPDATE_ESCALATION_POLICY',
		group: 'policies',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v3/policies/{policy_id}',
		tier: 'write',
		pathParams: ['policy_id'] as const,
	},
	{
		key: 'policies.remove',
		slug: 'BETTER_STACK_DELETE_ESCALATION_POLICY',
		group: 'policies',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v3/policies/{policy_id}',
		tier: 'destructive',
		pathParams: ['policy_id'] as const,
	},
	{
		key: 'policyGroups.create',
		slug: 'BETTER_STACK_CREATE_POLICY_GROUP',
		group: 'policyGroups',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/policy-groups',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'policyGroups.get',
		slug: 'BETTER_STACK_GET_POLICY_GROUP',
		group: 'policyGroups',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/policy-groups/{policy_group_id}',
		tier: 'read',
		pathParams: ['policy_group_id'] as const,
	},
	{
		key: 'policyGroups.list',
		slug: 'BETTER_STACK_LIST_POLICY_GROUPS',
		group: 'policyGroups',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/policy-groups',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'policyGroups.update',
		slug: 'BETTER_STACK_UPDATE_POLICY_GROUP',
		group: 'policyGroups',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/policy-groups/{policy_group_id}',
		tier: 'write',
		pathParams: ['policy_group_id'] as const,
	},
	{
		key: 'policyGroups.remove',
		slug: 'BETTER_STACK_DELETE_POLICY_GROUP',
		group: 'policyGroups',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/policy-groups/{policy_group_id}',
		tier: 'destructive',
		pathParams: ['policy_group_id'] as const,
	},
	{
		key: 'onCalls.create',
		slug: 'BETTER_STACK_CREATE_ON_CALL_SCHEDULE',
		group: 'onCalls',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/on-calls',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'onCalls.get',
		slug: 'BETTER_STACK_GET_ON_CALL_SCHEDULE',
		group: 'onCalls',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/on-calls/{schedule_id}',
		tier: 'read',
		pathParams: ['schedule_id'] as const,
	},
	{
		key: 'onCalls.list',
		slug: 'BETTER_STACK_LIST_ON_CALL_SCHEDULES',
		group: 'onCalls',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/on-calls',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'onCalls.update',
		slug: 'BETTER_STACK_UPDATE_ON_CALL_SCHEDULE',
		group: 'onCalls',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/on-calls/{schedule_id}',
		tier: 'write',
		pathParams: ['schedule_id'] as const,
	},
	{
		key: 'onCalls.remove',
		slug: 'BETTER_STACK_DELETE_ON_CALL_SCHEDULE',
		group: 'onCalls',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/on-calls/{schedule_id}',
		tier: 'destructive',
		pathParams: ['schedule_id'] as const,
	},
	{
		key: 'onCalls.events',
		slug: 'BETTER_STACK_LIST_ON_CALL_EVENTS',
		group: 'onCalls',
		handler: 'events',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/on-calls/{schedule_id}/events',
		tier: 'read',
		pathParams: ['schedule_id'] as const,
	},
	{
		key: 'urgencies.create',
		slug: 'BETTER_STACK_CREATE_URGENCIES',
		group: 'urgencies',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/urgencies',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'urgencies.get',
		slug: 'BETTER_STACK_GET_URGENCY',
		group: 'urgencies',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/urgencies/{urgency_id}',
		tier: 'read',
		pathParams: ['urgency_id'] as const,
	},
	{
		key: 'urgencies.list',
		slug: 'BETTER_STACK_LIST_URGENCIES',
		group: 'urgencies',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/urgencies',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'urgencies.update',
		slug: 'BETTER_STACK_UPDATE_URGENCIES',
		group: 'urgencies',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/urgencies/{urgency_id}',
		tier: 'write',
		pathParams: ['urgency_id'] as const,
	},
	{
		key: 'urgencies.remove',
		slug: 'BETTER_STACK_DELETE_URGENCY',
		group: 'urgencies',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/urgencies/{urgency_id}',
		tier: 'destructive',
		pathParams: ['urgency_id'] as const,
	},
	{
		key: 'urgencyGroups.create',
		slug: 'BETTER_STACK_CREATE_URGENCY_GROUP',
		group: 'urgencyGroups',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/urgency-groups',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'urgencyGroups.get',
		slug: 'BETTER_STACK_GET_URGENCY_GROUP',
		group: 'urgencyGroups',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/urgency-groups/{urgency_group_id}',
		tier: 'read',
		pathParams: ['urgency_group_id'] as const,
	},
	{
		key: 'urgencyGroups.list',
		slug: 'BETTER_STACK_LIST_URGENCY_GROUPS',
		group: 'urgencyGroups',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/urgency-groups',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'urgencyGroups.update',
		slug: 'BETTER_STACK_UPDATE_URGENCY_GROUP',
		group: 'urgencyGroups',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/urgency-groups/{urgency_group_id}',
		tier: 'write',
		pathParams: ['urgency_group_id'] as const,
	},
	{
		key: 'urgencyGroups.remove',
		slug: 'BETTER_STACK_DELETE_URGENCY_GROUP',
		group: 'urgencyGroups',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/urgency-groups/{urgency_group_id}',
		tier: 'destructive',
		pathParams: ['urgency_group_id'] as const,
	},
	{
		key: 'statusPages.get',
		slug: 'BETTER_STACK_GET_STATUS_PAGE',
		group: 'statusPages',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}',
		tier: 'read',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPages.list',
		slug: 'BETTER_STACK_LIST_STATUS_PAGES',
		group: 'statusPages',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'statusPages.update',
		slug: 'BETTER_STACK_UPDATE_STATUS_PAGES',
		group: 'statusPages',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/status-pages/{status_page_id}',
		tier: 'write',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageSections.create',
		slug: 'BETTER_STACK_CREATE_STATUS_PAGE_SECTION',
		group: 'statusPageSections',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/status-pages/{status_page_id}/sections',
		tier: 'write',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageSections.get',
		slug: 'BETTER_STACK_GET_STATUS_PAGE_SECTION',
		group: 'statusPageSections',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/sections/{section_id}',
		tier: 'read',
		pathParams: ['status_page_id', 'section_id'] as const,
	},
	{
		key: 'statusPageSections.list',
		slug: 'BETTER_STACK_LIST_STATUS_PAGE_SECTIONS',
		group: 'statusPageSections',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/sections',
		tier: 'read',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageSections.update',
		slug: 'BETTER_STACK_UPDATE_STATUS_PAGE_SECTION',
		group: 'statusPageSections',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/status-pages/{status_page_id}/sections/{section_id}',
		tier: 'write',
		pathParams: ['status_page_id', 'section_id'] as const,
	},
	{
		key: 'statusPageSections.remove',
		slug: 'BETTER_STACK_DELETE_STATUS_PAGE_SECTION',
		group: 'statusPageSections',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/status-pages/{status_page_id}/sections/{section_id}',
		tier: 'destructive',
		pathParams: ['status_page_id', 'section_id'] as const,
	},
	{
		key: 'statusPageResources.create',
		slug: 'BETTER_STACK_CREATE_STATUS_PAGE_RESOURCE',
		group: 'statusPageResources',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/status-pages/{status_page_id}/resources',
		tier: 'write',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageResources.get',
		slug: 'BETTER_STACK_GET_STATUS_PAGE_RESOURCE',
		group: 'statusPageResources',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/resources/{resource_id}',
		tier: 'read',
		pathParams: ['status_page_id', 'resource_id'] as const,
	},
	{
		key: 'statusPageResources.list',
		slug: 'BETTER_STACK_LIST_STATUS_PAGES_RESOURCES',
		group: 'statusPageResources',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/resources',
		tier: 'read',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageResources.update',
		slug: 'BETTER_STACK_UPDATE_STATUS_PAGE_RESOURCE',
		group: 'statusPageResources',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/status-pages/{status_page_id}/resources/{resource_id}',
		tier: 'write',
		pathParams: ['status_page_id', 'resource_id'] as const,
	},
	{
		key: 'statusPageResources.remove',
		slug: 'BETTER_STACK_DELETE_STATUS_PAGE_RESOURCE',
		group: 'statusPageResources',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/status-pages/{status_page_id}/resources/{resource_id}',
		tier: 'destructive',
		pathParams: ['status_page_id', 'resource_id'] as const,
	},
	{
		key: 'statusPageReports.create',
		slug: 'BETTER_STACK_CREATE_STATUS_PAGE_REPORT',
		group: 'statusPageReports',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/status-pages/{status_page_id}/status-reports',
		tier: 'write',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageReports.get',
		slug: 'BETTER_STACK_GET_STATUS_PAGE_REPORT',
		group: 'statusPageReports',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}',
		tier: 'read',
		pathParams: ['status_page_id', 'status_report_id'] as const,
	},
	{
		key: 'statusPageReports.list',
		slug: 'BETTER_STACK_LIST_STATUS_PAGE_REPORTS',
		group: 'statusPageReports',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/status-reports',
		tier: 'read',
		pathParams: ['status_page_id'] as const,
	},
	{
		key: 'statusPageReports.update',
		slug: 'BETTER_STACK_UPDATE_STATUS_PAGE_REPORT',
		group: 'statusPageReports',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}',
		tier: 'write',
		pathParams: ['status_page_id', 'status_report_id'] as const,
	},
	{
		key: 'statusPageReports.remove',
		slug: 'BETTER_STACK_DELETE_STATUS_PAGE_REPORT',
		group: 'statusPageReports',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}',
		tier: 'destructive',
		pathParams: ['status_page_id', 'status_report_id'] as const,
	},
	{
		key: 'statusUpdates.create',
		slug: 'BETTER_STACK_CREATE_STATUS_UPDATE',
		group: 'statusUpdates',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}/status-updates',
		tier: 'write',
		pathParams: ['status_page_id', 'status_report_id'] as const,
	},
	{
		key: 'statusUpdates.get',
		slug: 'BETTER_STACK_GET_STATUS_UPDATE',
		group: 'statusUpdates',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}/status-updates/{status_update_id}',
		tier: 'read',
		pathParams: [
			'status_page_id',
			'status_report_id',
			'status_update_id',
		] as const,
	},
	{
		key: 'statusUpdates.list',
		slug: 'BETTER_STACK_LIST_STATUS_PAGE_REPORT_STATUS_UPDATES',
		group: 'statusUpdates',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}/status-updates',
		tier: 'read',
		pathParams: ['status_page_id', 'status_report_id'] as const,
	},
	{
		key: 'statusUpdates.update',
		slug: 'BETTER_STACK_UPDATE_STATUS_PAGE_STATUS_REPORT_STATUS_UPDATE',
		group: 'statusUpdates',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}/status-updates/{status_update_id}',
		tier: 'write',
		pathParams: [
			'status_page_id',
			'status_report_id',
			'status_update_id',
		] as const,
	},
	{
		key: 'statusUpdates.remove',
		slug: 'BETTER_STACK_DELETE_STATUS_PAGE_STATUS_REPORT_STATUS_UPDATE',
		group: 'statusUpdates',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/status-pages/{status_page_id}/status-reports/{status_report_id}/status-updates/{status_update_id}',
		tier: 'destructive',
		pathParams: [
			'status_page_id',
			'status_report_id',
			'status_update_id',
		] as const,
	},
	{
		key: 'statusPageGroups.create',
		slug: 'BETTER_STACK_CREATE_STATUS_PAGE_GROUP',
		group: 'statusPageGroups',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/status-page-groups',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'statusPageGroups.get',
		slug: 'BETTER_STACK_GET_STATUS_PAGE_GROUP',
		group: 'statusPageGroups',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-page-groups/{status_page_group_id}',
		tier: 'read',
		pathParams: ['status_page_group_id'] as const,
	},
	{
		key: 'statusPageGroups.list',
		slug: 'BETTER_STACK_LIST_STATUS_PAGE_GROUPS',
		group: 'statusPageGroups',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-page-groups',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'statusPageGroups.update',
		slug: 'BETTER_STACK_UPDATE_STATUS_PAGE_GROUP',
		group: 'statusPageGroups',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/status-page-groups/{status_page_group_id}',
		tier: 'write',
		pathParams: ['status_page_group_id'] as const,
	},
	{
		key: 'statusPageGroups.remove',
		slug: 'BETTER_STACK_DELETE_STATUS_PAGE_GROUP',
		group: 'statusPageGroups',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/status-page-groups/{status_page_group_id}',
		tier: 'destructive',
		pathParams: ['status_page_group_id'] as const,
	},
	{
		key: 'statusPageGroups.statusPages',
		slug: 'BETTER_STACK_LIST_STATUS_PAGE_GROUPS_STATUS_PAGES',
		group: 'statusPageGroups',
		handler: 'statusPages',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/status-page-groups/{status_page_group_id}/status-pages',
		tier: 'read',
		pathParams: ['status_page_group_id'] as const,
	},
	{
		key: 'metadata.create',
		slug: 'BETTER_STACK_CREATE_METADATA',
		group: 'metadata',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v3/metadata',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'metadata.list',
		slug: 'BETTER_STACK_LIST_METADATA',
		group: 'metadata',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v3/metadata',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'outgoingWebhooks.create',
		slug: 'BETTER_STACK_CREATE_OUTGOING_WEBHOOK',
		group: 'outgoingWebhooks',
		handler: 'create',
		api: 'uptime',
		method: 'POST',
		path: '/api/v2/outgoing-webhooks',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'outgoingWebhooks.get',
		slug: 'BETTER_STACK_GET_OUTGOING_WEBHOOK',
		group: 'outgoingWebhooks',
		handler: 'get',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/outgoing-webhooks/{outgoing_webhook_id}',
		tier: 'read',
		pathParams: ['outgoing_webhook_id'] as const,
	},
	{
		key: 'outgoingWebhooks.list',
		slug: 'BETTER_STACK_LIST_OUTGOING_WEBHOOKS',
		group: 'outgoingWebhooks',
		handler: 'list',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/outgoing-webhooks',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'outgoingWebhooks.update',
		slug: 'BETTER_STACK_UPDATE_OUTGOING_WEBHOOK',
		group: 'outgoingWebhooks',
		handler: 'update',
		api: 'uptime',
		method: 'PATCH',
		path: '/api/v2/outgoing-webhooks/{outgoing_webhook_id}',
		tier: 'write',
		pathParams: ['outgoing_webhook_id'] as const,
	},
	{
		key: 'outgoingWebhooks.remove',
		slug: 'BETTER_STACK_DELETE_OUTGOING_WEBHOOK',
		group: 'outgoingWebhooks',
		handler: 'remove',
		api: 'uptime',
		method: 'DELETE',
		path: '/api/v2/outgoing-webhooks/{outgoing_webhook_id}',
		tier: 'destructive',
		pathParams: ['outgoing_webhook_id'] as const,
	},
	{
		key: 'sourceGroups.create',
		slug: 'BETTER_STACK_CREATE_SOURCE_GROUP',
		group: 'sourceGroups',
		handler: 'create',
		api: 'telemetry',
		method: 'POST',
		path: '/api/v1/source-groups',
		tier: 'write',
		pathParams: [] as const,
	},
	{
		key: 'sourceGroups.update',
		slug: 'BETTER_STACK_UPDATE_SOURCE_GROUP',
		group: 'sourceGroups',
		handler: 'update',
		api: 'telemetry',
		method: 'PATCH',
		path: '/api/v1/source-groups/{source_group_id}',
		tier: 'write',
		pathParams: ['source_group_id'] as const,
	},
	{
		key: 'sourceGroups.remove',
		slug: 'BETTER_STACK_DELETE_SOURCE_GROUP',
		group: 'sourceGroups',
		handler: 'remove',
		api: 'telemetry',
		method: 'DELETE',
		path: '/api/v1/source-groups/{source_group_id}',
		tier: 'destructive',
		pathParams: ['source_group_id'] as const,
	},
	{
		key: 'integrations.awsCloudWatch',
		slug: 'BETTER_STACK_LIST_AWS_CLOUDWATCH_INTEGRATIONS',
		group: 'integrations',
		handler: 'awsCloudWatch',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/aws-cloudwatch-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.azure',
		slug: 'BETTER_STACK_LIST_AZURE_INTEGRATIONS',
		group: 'integrations',
		handler: 'azure',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/azure-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.datadog',
		slug: 'BETTER_STACK_LIST_DATADOG_INTEGRATIONS',
		group: 'integrations',
		handler: 'datadog',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/datadog-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.elastic',
		slug: 'BETTER_STACK_LIST_ELASTIC_INTEGRATIONS',
		group: 'integrations',
		handler: 'elastic',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/elastic-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.email',
		slug: 'BETTER_STACK_LIST_EMAIL_INTEGRATIONS',
		group: 'integrations',
		handler: 'email',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/email-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.googleMonitoring',
		slug: 'BETTER_STACK_LIST_GOOGLE_MONITORING_INTEGRATIONS',
		group: 'integrations',
		handler: 'googleMonitoring',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/google-monitoring-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.grafana',
		slug: 'BETTER_STACK_LIST_GRAFANA_INTEGRATIONS',
		group: 'integrations',
		handler: 'grafana',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/grafana-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.jira',
		slug: 'BETTER_STACK_LIST_JIRA_INTEGRATIONS',
		group: 'integrations',
		handler: 'jira',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/jira-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.newRelic',
		slug: 'BETTER_STACK_LIST_NEW_RELIC_INTEGRATIONS',
		group: 'integrations',
		handler: 'newRelic',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/new-relic-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.pagerDuty',
		slug: 'BETTER_STACK_LIST_PAGER_DUTY_WEBHOOKS',
		group: 'integrations',
		handler: 'pagerDuty',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/pager-duty-webhooks',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.prometheus',
		slug: 'BETTER_STACK_LIST_PROMETHEUS_INTEGRATIONS',
		group: 'integrations',
		handler: 'prometheus',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/prometheus-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.slack',
		slug: 'BETTER_STACK_LIST_SLACK_INTEGRATIONS',
		group: 'integrations',
		handler: 'slack',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/slack-integrations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'integrations.splunkOnCall',
		slug: 'BETTER_STACK_LIST_SPLUNK_ON_CALL_INTEGRATIONS',
		group: 'integrations',
		handler: 'splunkOnCall',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/splunk-on-calls',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'catalog.relations',
		slug: 'BETTER_STACK_LIST_CATALOG_RELATIONS',
		group: 'catalog',
		handler: 'relations',
		api: 'uptime',
		method: 'GET',
		path: '/api/v2/catalog/relations',
		tier: 'read',
		pathParams: [] as const,
	},
	{
		key: 'token.describe',
		slug: 'BETTER_STACK_GET_UPTIME_API_TOKEN',
		group: 'token',
		handler: 'describe',
		api: 'local',
		method: null,
		path: null,
		tier: 'read',
		pathParams: [] as const,
	},
] as const;

export type OperationRow = (typeof OPERATION_TABLE)[number];
