import {
	holidays as calendarHolidays,
	isPublicHoliday as calendarIsPublicHoliday,
	isWorkingDay as calendarIsWorkingDay,
	publicHolidays as calendarPublicHolidays,
	timezone as calendarTimezone,
	workingDays as calendarWorkingDays,
	worldTime as calendarWorldTime,
} from './calendar';
import {
	gdp as economicsGdp,
	incomeTax as economicsIncomeTax,
	incomeTaxCalculator as economicsIncomeTaxCalculator,
	inflation as economicsInflation,
	interestRate as economicsInterestRate,
	mortgageCalculator as economicsMortgageCalculator,
	mortgageRate as economicsMortgageRate,
	population as economicsPopulation,
	propertyTax as economicsPropertyTax,
	salesTax as economicsSalesTax,
	salesTaxCalculator as economicsSalesTaxCalculator,
	unemployment as economicsUnemployment,
	vatRates as economicsVatRates,
} from './economics';
import {
	advice as entertainmentAdvice,
	bucketList as entertainmentBucketList,
	chuckNorris as entertainmentChuckNorris,
	dadJokes as entertainmentDadJokes,
	factOfTheDay as entertainmentFactOfTheDay,
	facts as entertainmentFacts,
	generateSudoku as entertainmentGenerateSudoku,
	hobbies as entertainmentHobbies,
	horoscope as entertainmentHoroscope,
	jokeOfTheDay as entertainmentJokeOfTheDay,
	jokes as entertainmentJokes,
	quoteOfTheDay as entertainmentQuoteOfTheDay,
	quotes as entertainmentQuotes,
	randomQuotes as entertainmentRandomQuotes,
	riddles as entertainmentRiddles,
	solveSudoku as entertainmentSolveSudoku,
	trivia as entertainmentTrivia,
	triviaOfTheDay as entertainmentTriviaOfTheDay,
} from './entertainment';
import {
	caloriesBurned as healthCaloriesBurned,
	cocktails as healthCocktails,
	exercises as healthExercises,
	nutrition as healthNutrition,
	recipes as healthRecipes,
} from './health';
import {
	dnsRecords as internetDnsRecords,
	domain as internetDomain,
	ipLookup as internetIpLookup,
	mxRecords as internetMxRecords,
	scrape as internetScrape,
	urlLookup as internetUrlLookup,
	userAgent as internetUserAgent,
	webpage as internetWebpage,
	whois as internetWhois,
} from './internet';
import {
	airQuality as locationAirQuality,
	cities as locationCities,
	country as locationCountry,
	county as locationCounty,
	evChargers as locationEvChargers,
	geocode as locationGeocode,
	hospitals as locationHospitals,
	postalCode as locationPostalCode,
	reverseGeocode as locationReverseGeocode,
	universities as locationUniversities,
	weather as locationWeather,
	weatherForecast as locationWeatherForecast,
	zipCode as locationZipCode,
} from './location';
import {
	bitcoin as marketsBitcoin,
	commodityPrice as marketsCommodityPrice,
	convertCurrency as marketsConvertCurrency,
	cryptoPrice as marketsCryptoPrice,
	earnings as marketsEarnings,
	earningsCalendar as marketsEarningsCalendar,
	earningsTranscript as marketsEarningsTranscript,
	etf as marketsEtf,
	exchangeRate as marketsExchangeRate,
	insiderTransactions as marketsInsiderTransactions,
	marketCap as marketsMarketCap,
	mutualFund as marketsMutualFund,
	secFilings as marketsSecFilings,
	sp500 as marketsSp500,
	stockExchanges as marketsStockExchanges,
	stockPrice as marketsStockPrice,
	ticker as marketsTicker,
	tickerList as marketsTickerList,
} from './markets';
import {
	animals as referenceAnimals,
	babyNames as referenceBabyNames,
	cats as referenceCats,
	celebrities as referenceCelebrities,
	dayInHistory as referenceDayInHistory,
	dogs as referenceDogs,
	historicalEvents as referenceHistoricalEvents,
	historicalFigures as referenceHistoricalFigures,
	planets as referencePlanets,
	stars as referenceStars,
} from './reference';
import {
	dictionary as textDictionary,
	embeddings as textEmbeddings,
	language as textLanguage,
	loremIpsum as textLoremIpsum,
	profanityFilter as textProfanityFilter,
	randomWord as textRandomWord,
	rhymes as textRhymes,
	sentiment as textSentiment,
	similarity as textSimilarity,
	spellCheck as textSpellCheck,
	thesaurus as textThesaurus,
} from './text';
import {
	aircraft as transportAircraft,
	airlines as transportAirlines,
	airports as transportAirports,
	cars as transportCars,
	electricVehicles as transportElectricVehicles,
	helicopters as transportHelicopters,
	motorcycles as transportMotorcycles,
	vin as transportVin,
} from './transport';
import {
	barcode as utilityBarcode,
	convertUnit as utilityConvertUnit,
	counter as utilityCounter,
	countryFlag as utilityCountryFlag,
	emoji as utilityEmoji,
	logo as utilityLogo,
	password as utilityPassword,
	qrCode as utilityQrCode,
	randomImage as utilityRandomImage,
	randomUser as utilityRandomUser,
} from './utility';
import {
	bin as validationBin,
	disposableEmail as validationDisposableEmail,
	email as validationEmail,
	iban as validationIban,
	phone as validationPhone,
	routingNumber as validationRoutingNumber,
	swiftCode as validationSwiftCode,
} from './validation';

export const Location = {
	geocode: locationGeocode,
	reverseGeocode: locationReverseGeocode,
	cities: locationCities,
	country: locationCountry,
	county: locationCounty,
	zipCode: locationZipCode,
	postalCode: locationPostalCode,
	universities: locationUniversities,
	hospitals: locationHospitals,
	evChargers: locationEvChargers,
	weather: locationWeather,
	weatherForecast: locationWeatherForecast,
	airQuality: locationAirQuality,
};

export const Calendar = {
	timezone: calendarTimezone,
	worldTime: calendarWorldTime,
	holidays: calendarHolidays,
	publicHolidays: calendarPublicHolidays,
	isPublicHoliday: calendarIsPublicHoliday,
	isWorkingDay: calendarIsWorkingDay,
	workingDays: calendarWorkingDays,
};

export const Internet = {
	domain: internetDomain,
	dnsRecords: internetDnsRecords,
	mxRecords: internetMxRecords,
	whois: internetWhois,
	ipLookup: internetIpLookup,
	urlLookup: internetUrlLookup,
	webpage: internetWebpage,
	scrape: internetScrape,
	userAgent: internetUserAgent,
};

export const Validation = {
	email: validationEmail,
	disposableEmail: validationDisposableEmail,
	phone: validationPhone,
	routingNumber: validationRoutingNumber,
	iban: validationIban,
	bin: validationBin,
	swiftCode: validationSwiftCode,
};

export const Markets = {
	stockPrice: marketsStockPrice,
	ticker: marketsTicker,
	tickerList: marketsTickerList,
	stockExchanges: marketsStockExchanges,
	sp500: marketsSp500,
	marketCap: marketsMarketCap,
	earnings: marketsEarnings,
	earningsCalendar: marketsEarningsCalendar,
	earningsTranscript: marketsEarningsTranscript,
	insiderTransactions: marketsInsiderTransactions,
	secFilings: marketsSecFilings,
	etf: marketsEtf,
	mutualFund: marketsMutualFund,
	cryptoPrice: marketsCryptoPrice,
	bitcoin: marketsBitcoin,
	commodityPrice: marketsCommodityPrice,
	convertCurrency: marketsConvertCurrency,
	exchangeRate: marketsExchangeRate,
};

export const Economics = {
	gdp: economicsGdp,
	inflation: economicsInflation,
	unemployment: economicsUnemployment,
	population: economicsPopulation,
	interestRate: economicsInterestRate,
	mortgageRate: economicsMortgageRate,
	mortgageCalculator: economicsMortgageCalculator,
	incomeTax: economicsIncomeTax,
	incomeTaxCalculator: economicsIncomeTaxCalculator,
	salesTax: economicsSalesTax,
	salesTaxCalculator: economicsSalesTaxCalculator,
	propertyTax: economicsPropertyTax,
	vatRates: economicsVatRates,
};

export const Text = {
	sentiment: textSentiment,
	similarity: textSimilarity,
	embeddings: textEmbeddings,
	language: textLanguage,
	spellCheck: textSpellCheck,
	profanityFilter: textProfanityFilter,
	dictionary: textDictionary,
	thesaurus: textThesaurus,
	rhymes: textRhymes,
	randomWord: textRandomWord,
	loremIpsum: textLoremIpsum,
};

export const Utility = {
	qrCode: utilityQrCode,
	barcode: utilityBarcode,
	password: utilityPassword,
	randomUser: utilityRandomUser,
	counter: utilityCounter,
	convertUnit: utilityConvertUnit,
	logo: utilityLogo,
	countryFlag: utilityCountryFlag,
	randomImage: utilityRandomImage,
	emoji: utilityEmoji,
};

export const Transport = {
	aircraft: transportAircraft,
	airlines: transportAirlines,
	airports: transportAirports,
	helicopters: transportHelicopters,
	cars: transportCars,
	motorcycles: transportMotorcycles,
	electricVehicles: transportElectricVehicles,
	vin: transportVin,
};

export const Health = {
	caloriesBurned: healthCaloriesBurned,
	nutrition: healthNutrition,
	exercises: healthExercises,
	recipes: healthRecipes,
	cocktails: healthCocktails,
};

export const Reference = {
	animals: referenceAnimals,
	cats: referenceCats,
	dogs: referenceDogs,
	planets: referencePlanets,
	stars: referenceStars,
	historicalEvents: referenceHistoricalEvents,
	historicalFigures: referenceHistoricalFigures,
	dayInHistory: referenceDayInHistory,
	celebrities: referenceCelebrities,
	babyNames: referenceBabyNames,
};

export const Entertainment = {
	jokes: entertainmentJokes,
	dadJokes: entertainmentDadJokes,
	chuckNorris: entertainmentChuckNorris,
	jokeOfTheDay: entertainmentJokeOfTheDay,
	facts: entertainmentFacts,
	factOfTheDay: entertainmentFactOfTheDay,
	quotes: entertainmentQuotes,
	randomQuotes: entertainmentRandomQuotes,
	quoteOfTheDay: entertainmentQuoteOfTheDay,
	advice: entertainmentAdvice,
	bucketList: entertainmentBucketList,
	hobbies: entertainmentHobbies,
	horoscope: entertainmentHoroscope,
	riddles: entertainmentRiddles,
	trivia: entertainmentTrivia,
	triviaOfTheDay: entertainmentTriviaOfTheDay,
	generateSudoku: entertainmentGenerateSudoku,
	solveSudoku: entertainmentSolveSudoku,
};

export * from './types';
