import type { EndpointRiskLevel } from 'corsair/core';

export type BooqableMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type BooqableRoute = {
	key: string;
	group: string;
	name: string;
	method: BooqableMethod;
	path: string;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const booqableRoutes = [
	{
		key: 'createCustomer',
		group: 'customers',
		name: 'createCustomer',
		method: 'POST',
		path: '/customers',
		riskLevel: 'write',
		description: 'Create a new customer in Booqable.',
	},
	{
		key: 'deleteCustomer',
		group: 'customers',
		name: 'deleteCustomer',
		method: 'DELETE',
		path: '/customers/{id}',
		pathParams: ['id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete (archive) a customer by ID.',
	},
	{
		key: 'getCustomer',
		group: 'customers',
		name: 'getCustomer',
		method: 'GET',
		path: '/customers/{id}',
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Fetch a specific customer by ID.',
	},
	{
		key: 'getCustomers',
		group: 'customers',
		name: 'getCustomers',
		method: 'GET',
		path: '/customers',
		riskLevel: 'read',
		description: 'Retrieve a paginated list of customers.',
	},
	{
		key: 'searchCustomers',
		group: 'customers',
		name: 'searchCustomers',
		method: 'POST',
		path: '/customers/search',
		riskLevel: 'read',
		description: 'Search customers with advanced filtering.',
	},
	{
		key: 'createOrder',
		group: 'orders',
		name: 'createOrder',
		method: 'POST',
		path: '/orders',
		riskLevel: 'write',
		description: 'Create a new order.',
	},
	{
		key: 'deleteOrder',
		group: 'orders',
		name: 'deleteOrder',
		method: 'DELETE',
		path: '/orders/{id}',
		pathParams: ['id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete (archive) an order by ID.',
	},
	{
		key: 'getNewOrder',
		group: 'orders',
		name: 'getNewOrder',
		method: 'GET',
		path: '/orders/new',
		riskLevel: 'read',
		description: 'Retrieve a new order template with default values.',
	},
	{
		key: 'getOrder',
		group: 'orders',
		name: 'getOrder',
		method: 'GET',
		path: '/orders/{id}',
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Retrieve a specific order by ID.',
	},
	{
		key: 'listOrders',
		group: 'orders',
		name: 'listOrders',
		method: 'GET',
		path: '/orders',
		riskLevel: 'read',
		description: 'Retrieve a paginated list of orders.',
	},
	{
		key: 'searchOrders',
		group: 'orders',
		name: 'searchOrders',
		method: 'POST',
		path: '/orders/search',
		riskLevel: 'read',
		description: 'Search orders with advanced filtering.',
	},
	{
		key: 'createProductGroup',
		group: 'productGroups',
		name: 'createProductGroup',
		method: 'POST',
		path: '/product_groups',
		riskLevel: 'write',
		description: 'Create a new product group.',
	},
	{
		key: 'deleteProductGroup',
		group: 'productGroups',
		name: 'deleteProductGroup',
		method: 'DELETE',
		path: '/product_groups/{id}',
		pathParams: ['id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a product group by ID.',
	},
	{
		key: 'getProductGroup',
		group: 'productGroups',
		name: 'getProductGroup',
		method: 'GET',
		path: '/product_groups/{id}',
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Fetch a specific product group by ID.',
	},
	{
		key: 'listProductGroups',
		group: 'productGroups',
		name: 'listProductGroups',
		method: 'GET',
		path: '/product_groups',
		riskLevel: 'read',
		description: 'List product groups with filtering and pagination.',
	},
	{
		key: 'getProduct',
		group: 'products',
		name: 'getProduct',
		method: 'GET',
		path: '/products/{id}',
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Fetch a specific product by ID.',
	},
	{
		key: 'listProducts',
		group: 'products',
		name: 'listProducts',
		method: 'GET',
		path: '/products',
		riskLevel: 'read',
		description: 'Retrieve a paginated list of products.',
	},
	{
		key: 'updateCompany',
		group: 'companies',
		name: 'updateCompany',
		method: 'PUT',
		path: '/companies/current',
		riskLevel: 'write',
		description: 'Update the current company information.',
	},
	{
		key: 'getInventoryLevels',
		group: 'inventoryLevels',
		name: 'getInventoryLevels',
		method: 'GET',
		path: '/inventory_levels',
		riskLevel: 'read',
		description: 'Fetch inventory levels for products across locations.',
	},
	{
		key: 'listBarcodes',
		group: 'barcodes',
		name: 'listBarcodes',
		method: 'GET',
		path: '/barcodes',
		riskLevel: 'read',
		description: 'Retrieve a list of barcodes.',
	},
	{
		key: 'listBundleItems',
		group: 'bundleItems',
		name: 'listBundleItems',
		method: 'GET',
		path: '/bundle_items',
		riskLevel: 'read',
		description: 'Retrieve a list of bundle items.',
	},
	{
		key: 'searchBundles',
		group: 'bundles',
		name: 'searchBundles',
		method: 'POST',
		path: '/bundles/search',
		riskLevel: 'read',
		description: 'Search bundles with advanced filtering.',
	},
	{
		key: 'listClusters',
		group: 'clusters',
		name: 'listClusters',
		method: 'GET',
		path: '/clusters',
		riskLevel: 'read',
		description: 'Retrieve a list of clusters.',
	},
	{
		key: 'listCoupons',
		group: 'coupons',
		name: 'listCoupons',
		method: 'GET',
		path: '/coupons',
		riskLevel: 'read',
		description: 'Retrieve a list of coupons.',
	},
	{
		key: 'listDefaultProperties',
		group: 'defaultProperties',
		name: 'listDefaultProperties',
		method: 'GET',
		path: '/default_properties',
		riskLevel: 'read',
		description: 'Retrieve default property definitions.',
	},
	{
		key: 'listDocuments',
		group: 'documents',
		name: 'listDocuments',
		method: 'GET',
		path: '/documents',
		riskLevel: 'read',
		description: 'Retrieve a list of documents.',
	},
	{
		key: 'searchDocuments',
		group: 'documents',
		name: 'searchDocuments',
		method: 'POST',
		path: '/documents/search',
		riskLevel: 'read',
		description: 'Search documents with advanced filtering.',
	},
	{
		key: 'listEmailTemplates',
		group: 'emailTemplates',
		name: 'listEmailTemplates',
		method: 'GET',
		path: '/email_templates',
		riskLevel: 'read',
		description: 'List email templates.',
	},
	{
		key: 'listEmployees',
		group: 'employees',
		name: 'listEmployees',
		method: 'GET',
		path: '/employees',
		riskLevel: 'read',
		description: 'Retrieve a list of employees.',
	},
	{
		key: 'listInventoryBreakdowns',
		group: 'inventoryBreakdowns',
		name: 'listInventoryBreakdowns',
		method: 'GET',
		path: '/inventory_breakdowns',
		riskLevel: 'read',
		description: 'Retrieve inventory breakdowns by status and product.',
	},
	{
		key: 'listItems',
		group: 'items',
		name: 'listItems',
		method: 'GET',
		path: '/items',
		riskLevel: 'read',
		description: 'Retrieve a list of items (products and product groups).',
	},
	{
		key: 'searchItems',
		group: 'items',
		name: 'searchItems',
		method: 'POST',
		path: '/items/search',
		riskLevel: 'read',
		description: 'Search items with advanced filtering.',
	},
	{
		key: 'listLines',
		group: 'lines',
		name: 'listLines',
		method: 'GET',
		path: '/lines',
		riskLevel: 'read',
		description: 'Retrieve a paginated list of order lines.',
	},
	{
		key: 'listLocations',
		group: 'locations',
		name: 'listLocations',
		method: 'GET',
		path: '/locations',
		riskLevel: 'read',
		description: 'Retrieve a list of locations.',
	},
	{
		key: 'listNotes',
		group: 'notes',
		name: 'listNotes',
		method: 'GET',
		path: '/notes',
		riskLevel: 'read',
		description: 'Retrieve a list of notes.',
	},
	{
		key: 'listPaymentMethods',
		group: 'paymentMethods',
		name: 'listPaymentMethods',
		method: 'GET',
		path: '/payment_methods',
		riskLevel: 'read',
		description: 'Retrieve a list of payment methods.',
	},
	{
		key: 'listPayments',
		group: 'payments',
		name: 'listPayments',
		method: 'GET',
		path: '/payments',
		riskLevel: 'read',
		description: 'List all payments.',
	},
	{
		key: 'listPhotos',
		group: 'photos',
		name: 'listPhotos',
		method: 'GET',
		path: '/photos',
		riskLevel: 'read',
		description: 'Retrieve a paginated list of photos.',
	},
	{
		key: 'listPlannings',
		group: 'plannings',
		name: 'listPlannings',
		method: 'GET',
		path: '/plannings',
		riskLevel: 'read',
		description: 'Retrieve planning records for reservations.',
	},
	{
		key: 'searchPlannings',
		group: 'plannings',
		name: 'searchPlannings',
		method: 'POST',
		path: '/plannings/search',
		riskLevel: 'read',
		description: 'Search plannings with advanced filtering.',
	},
	{
		key: 'listPriceRulesets',
		group: 'priceRulesets',
		name: 'listPriceRulesets',
		method: 'GET',
		path: '/price_rulesets',
		riskLevel: 'read',
		description: 'List price rulesets.',
	},
	{
		key: 'listPriceStructures',
		group: 'priceStructures',
		name: 'listPriceStructures',
		method: 'GET',
		path: '/price_structures',
		riskLevel: 'read',
		description: 'List price structures.',
	},
	{
		key: 'listProperties',
		group: 'properties',
		name: 'listProperties',
		method: 'GET',
		path: '/properties',
		riskLevel: 'read',
		description: 'Retrieve a list of custom properties.',
	},
	{
		key: 'listProvinces',
		group: 'provinces',
		name: 'listProvinces',
		method: 'GET',
		path: '/provinces',
		riskLevel: 'read',
		description: 'Retrieve a list of provinces.',
	},
	{
		key: 'listStockItemPlannings',
		group: 'stockItemPlannings',
		name: 'listStockItemPlannings',
		method: 'GET',
		path: '/stock_item_plannings',
		riskLevel: 'read',
		description: 'Retrieve stock item plannings.',
	},
	{
		key: 'listStockItems',
		group: 'stockItems',
		name: 'listStockItems',
		method: 'GET',
		path: '/stock_items',
		riskLevel: 'read',
		description: 'Retrieve a list of stock items.',
	},
	{
		key: 'listTaxRates',
		group: 'taxRates',
		name: 'listTaxRates',
		method: 'GET',
		path: '/tax_rates',
		riskLevel: 'read',
		description: 'Retrieve a list of tax rates.',
	},
	{
		key: 'listTaxValues',
		group: 'taxValues',
		name: 'listTaxValues',
		method: 'GET',
		path: '/tax_values',
		riskLevel: 'read',
		description: 'Retrieve a list of tax values.',
	},
	{
		key: 'listUsers',
		group: 'users',
		name: 'listUsers',
		method: 'GET',
		path: '/users',
		riskLevel: 'read',
		description: 'Retrieve a list of users.',
	},
] as const satisfies readonly BooqableRoute[];
