import type { EndpointRiskLevel } from 'corsair/core';

export type AffindaMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type AffindaRoute = {
	key: string;
	group: string;
	name: string;
	method: AffindaMethod;
	path: string;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const affindaRoutes = [
	{
		key: 'addTagToDocuments',
		group: 'documents',
		name: 'addTagToDocuments',
		method: 'POST',
		path: '/documents/batch_add_tag',
		description:
			'Tool to add a tag to multiple documents in a single operation. Use when you need to organize or categorize multiple documents by assigning them a shared tag. Tags enable efficient filtering and grouping of documents in your workspace.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'batchUpdateAnnotations',
		group: 'annotations',
		name: 'batchUpdateAnnotations',
		method: 'POST',
		path: '/annotations/batch_update',
		description:
			"Batch update multiple document annotations in a single API call. Use this action to efficiently update parsed values or other fields across many annotations at once, rather than making individual update requests for each annotation. Prerequisites: - Obtain annotation IDs using the 'Get Annotations' action with a document filter - Annotations must exist in documents that have been processed by Affinda Common use cases: - Correcting OCR/extraction errors in bulk - Updating parsed values after manual review - Modifying annotation data programmatically",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createApiUser',
		group: 'apiUsers',
		name: 'createApiUser',
		method: 'POST',
		path: '/api_users',
		description:
			'Tool to create a new API user within an organization. Use when you need to generate a new API user with authentication credentials for programmatic access to Affinda services.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createBatchAnnotations',
		group: 'annotations',
		name: 'createBatchAnnotations',
		method: 'POST',
		path: '/annotations/batch_create',
		description:
			"Batch create multiple document annotations in a single API call. Use this action to efficiently create multiple annotations at once for documents that have been processed by Affinda. This is useful for programmatically adding structured data to documents or importing annotation data from external sources. Prerequisites: - Documents must be created first using 'Create Document' action - Obtain document identifiers from 'Create Document' or 'Get Documents' actions - Know the data point identifiers for your collection (from extractor configuration) Common use cases: - Importing annotation data from external systems - Programmatically adding structured data to documents - Creating annotations for validation or training purposes",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createCollection',
		group: 'collections',
		name: 'createCollection',
		method: 'POST',
		path: '/collections',
		description:
			'Tool to create a new collection. Use after you have a valid workspace ID and want to group documents by a specific extractor within that workspace.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDataFieldForCollection',
		group: 'collections',
		name: 'createDataFieldForCollection',
		method: 'POST',
		path: '/collections/{identifier}/create_data_field',
		description:
			'Tool to create a data field for a collection along with a new data point. Use when you need to add a custom field to a collection for document processing and validation.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDataPoint',
		group: 'dataPoints',
		name: 'createDataPoint',
		method: 'POST',
		path: '/data_points',
		description:
			'Tool to create a custom data point for document extraction. Use when you need to define a new field that should be extracted from documents in a specific extractor. Note: This endpoint is deprecated but still functional. Data points define custom fields for extraction models.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDataPointChoice',
		group: 'dataPointChoices',
		name: 'createDataPointChoice',
		method: 'POST',
		path: '/data_point_choices',
		description:
			'Tool to create a custom data point choice. Use when you need to add a new choice option for a specific data point in a collection or organization. Note: This endpoint is deprecated but still functional.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDataSource',
		group: 'dataSources',
		name: 'createDataSource',
		method: 'POST',
		path: '/mapping_data_sources',
		description:
			'Tool to create a custom mapping data source. Use when you need to set up a new data source for mapping AI-extracted values to your database records.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDataSourceValue',
		group: 'dataSources',
		name: 'createDataSourceValue',
		method: 'POST',
		path: '/mapping_data_sources/{identifier}/values',
		description:
			'Tool to add a new value to a mapping data source. Use when you need to add entries to a data source for mapping or validation purposes. The created value can then be referenced in document extraction and mapping workflows.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDocument',
		group: 'documents',
		name: 'createDocument',
		method: 'POST',
		path: '/documents',
		description:
			"Upload a document to Affinda for parsing and data extraction. Use this action when you need to: - Parse resumes/CVs to extract candidate information - Process invoices to extract line items, amounts, and vendor details - Extract data from any supported document type (PDF, DOCX, images) You can upload either a file directly or provide a publicly accessible URL. The document will be processed by Affinda's AI extraction engine. Prerequisites: - For collection-based uploads: Get collection ID from get_collections action - For workspace-specific uploads: Get workspace ID from get_workspaces action",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDocumentType',
		group: 'documentTypes',
		name: 'createDocumentType',
		method: 'POST',
		path: '/document_types',
		description:
			'Tool to create a new document type in the specified organization. Use when you need to define a new category of documents for processing. Document types allow you to organize and categorize documents within an organization.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createExtractor',
		group: 'extractors',
		name: 'createExtractor',
		method: 'POST',
		path: '/extractors',
		description:
			'Tool to create a new extractor. Use when you need to define a custom document parser with specific fields and extraction rules, typically derived from a base extractor.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createFromDataDocuments',
		group: 'documents',
		name: 'createFromDataDocuments',
		method: 'POST',
		path: '/documents/create_from_data',
		description:
			'Create a document from structured resume or job description data for Search & Match. Use this when you have structured data to create a document programmatically without file uploads. Returns an identifier for subsequent status checks via /documents/{identifier}.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createIndex',
		group: 'indexes',
		name: 'createIndex',
		method: 'POST',
		path: '/index',
		description:
			'Tool to create a new index for search and match functionality. Use when you need to set up a new index for organizing and searching documents like resumes or job descriptions.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createInvitation',
		group: 'invitations',
		name: 'createInvitation',
		method: 'POST',
		path: '/invitations',
		description:
			'Tool to create a new organization invitation. Use when you need to invite a user to join an organization with a specific role.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createJobDescriptionSearch',
		group: 'jobDescriptionSearch',
		name: 'createJobDescriptionSearch',
		method: 'POST',
		path: '/job_description_search',
		description:
			"Search through parsed job descriptions using custom criteria or resume matching. Use this action when you need to find job postings that match specific requirements such as skills, experience, location, education, or to find jobs matching a candidate's resume. Returns ranked results with detailed match scores.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createJobDescriptionSearchEmbedUrl',
		group: 'jobDescriptionSearch',
		name: 'createJobDescriptionSearchEmbedUrl',
		method: 'POST',
		path: '/job_description_search/embed',
		description:
			'Tool to create and return a signed URL for the embeddable job description search tool. Use this when you need to generate a URL that can be embedded on a web page to provide job description search functionality. Optionally pass config_override to customize display settings, field weights, and theme.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createMapping',
		group: 'mappings',
		name: 'createMapping',
		method: 'POST',
		path: '/mappings',
		description:
			'Tool to create a custom mapping for a data source. Use when you need to configure specific lookup settings for a MappingDataSource. Note: This endpoint is deprecated.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createOrganization',
		group: 'organizations',
		name: 'createOrganization',
		method: 'POST',
		path: '/organizations',
		description:
			'Tool to create a new organization. Use when you have a unique organization name and want to group resources under it.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createResthookSubscription',
		group: 'resthooks',
		name: 'createResthookSubscription',
		method: 'POST',
		path: '/resthook_subscriptions',
		description:
			'Tool to create a new RESTHook subscription. Use after confirming your webhook endpoint is ready to receive document event notifications.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createResumeSearch',
		group: 'resumeSearch',
		name: 'createResumeSearch',
		method: 'POST',
		path: '/resume_search',
		description:
			'Tool to search through parsed resumes using three methods: match to a job description, match to a resume, or custom criteria. Use when you need to find candidates matching specific requirements.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createResumeSearchEmbedUrl',
		group: 'resumeSearch',
		name: 'createResumeSearchEmbedUrl',
		method: 'POST',
		path: '/resume_search/embed',
		description:
			'Tool to create and return a signed URL for the embeddable resume search tool. Use this when you need to generate a URL that can be embedded on a web page to provide resume search functionality. Optionally pass config_override to customize display settings, field weights, and theme.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createTag',
		group: 'tags',
		name: 'createTag',
		method: 'POST',
		path: '/tags',
		description:
			'Creates a new tag in the specified workspace. Tags can be used to categorize and label documents for organization and filtering. Each tag name must be unique within its workspace. Returns the created tag with its ID and metadata.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createValidationResult',
		group: 'validationResults',
		name: 'createValidationResult',
		method: 'POST',
		path: '/validation_results',
		description:
			'Create a validation result for document annotations in Affinda. Use this tool to record validation outcomes after parsing a document. Validation results track whether specific annotations (extracted data fields) pass or fail business rules. Prerequisites: 1. Get a document identifier from Get Documents or Create Document 2. Get annotation IDs from Get Annotations for that document 3. Define a kebab-case rule slug that identifies your validation rule Example use cases: - Recording that an invoice total matches the sum of line items - Marking that a required field is present and valid - Logging validation failures for review workflows',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createValidationResultsBatch',
		group: 'validationResults',
		name: 'createValidationResultsBatch',
		method: 'POST',
		path: '/validation_results/batch_create',
		description:
			'Batch create multiple validation results for document annotations in a single API call. Use this action to efficiently record validation outcomes for multiple documents or rules at once, rather than making individual create requests for each validation result. This is particularly useful for bulk validation workflows or when validating multiple rules across many documents. Prerequisites: - Obtain document identifiers from Get Documents or Create Document actions - Get annotation IDs from Get Annotations for those documents - Define kebab-case rule slugs that identify your validation rules Common use cases: - Bulk recording of validation results across multiple documents - Validating multiple business rules on the same document - Automated validation workflows for large document batches',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createWorkspace',
		group: 'workspaces',
		name: 'createWorkspace',
		method: 'POST',
		path: '/workspaces',
		description:
			'Tool to create a new workspace. Use when you need to programmatically create a workspace container within an organization.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createWorkspaceMembership',
		group: 'workspaceMemberships',
		name: 'createWorkspaceMembership',
		method: 'POST',
		path: '/workspace_memberships',
		description:
			'Tool to add a user to a workspace by creating a membership. Use when you need to grant a user access to a specific workspace.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'deleteAnnotationsBatch',
		group: 'annotations',
		name: 'deleteAnnotationsBatch',
		method: 'POST',
		path: '/annotations/batch_delete',
		description:
			"Batch delete multiple document annotations in a single API call. Use this action to efficiently remove multiple annotations at once rather than making individual delete requests for each annotation. Prerequisites: - Obtain annotation IDs using the 'Get Annotations' action with a document filter - Annotations must exist in documents that have been processed by Affinda Common use cases: - Removing incorrect or unwanted annotations in bulk - Cleaning up annotations after document reprocessing - Deleting specific extracted data fields programmatically",
		pathParams: [],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteCollection',
		group: 'collections',
		name: 'deleteCollection',
		method: 'DELETE',
		path: '/collections/{identifier}',
		description:
			'Permanently delete a collection from Affinda by its identifier. This is a destructive operation that cannot be undone. Use Get Collections first to verify the collection ID before deletion. Note: Documents in the collection may also be affected.',
		pathParams: ['collection_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteDataPoint',
		group: 'dataPoints',
		name: 'deleteDataPoint',
		method: 'DELETE',
		path: '/data_points/{identifier}',
		description:
			'Tool to permanently delete a data point by its identifier. Use when you need to remove a data point from the database after confirming the identifier. Note: This endpoint is deprecated but still functional.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteDataSource',
		group: 'dataSources',
		name: 'deleteDataSource',
		method: 'DELETE',
		path: '/mapping_data_sources/{identifier}',
		description:
			'Permanently delete a mapping data source from the database by its identifier. This is a destructive operation that cannot be undone. Use when you need to remove a data source that is no longer needed or was created in error.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteDataSourceValue',
		group: 'dataSources',
		name: 'deleteDataSourceValue',
		method: 'DELETE',
		path: '/mapping_data_sources/{identifier}/values/{value}',
		description:
			'Tool to delete a specific value from a mapping data source. Use when you need to remove an incorrect or outdated value from a data source mapping.',
		pathParams: ['identifier', 'value'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteDocument',
		group: 'documents',
		name: 'deleteDocument',
		method: 'DELETE',
		path: '/documents/{identifier}',
		description:
			'Tool to delete a specific document by its ID. Use when you need to remove a document that is incorrect or no longer needed, after confirming the document ID.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteDocumentType',
		group: 'documentTypes',
		name: 'deleteDocumentType',
		method: 'DELETE',
		path: '/document_types/{identifier}',
		description:
			'Tool to permanently delete a document type by its identifier. Use when you need to remove a document type that is no longer needed. This is a destructive operation that cannot be undone.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteExtractor',
		group: 'extractors',
		name: 'deleteExtractor',
		method: 'DELETE',
		path: '/extractors/{identifier}',
		description:
			'Permanently delete an extractor from Affinda by its identifier. This is a destructive operation that cannot be undone. Use Get Extractors first to verify the extractor ID before deletion. Note: This action is deprecated by the API.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteIndex',
		group: 'indexes',
		name: 'deleteIndex',
		method: 'DELETE',
		path: '/index/{name}',
		description:
			'Tool to permanently delete an index from Affinda by its name. Use when you need to remove an index that is no longer needed. This is a destructive operation that cannot be undone.',
		pathParams: ['name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteInvitation',
		group: 'invitations',
		name: 'deleteInvitation',
		method: 'DELETE',
		path: '/invitations/{identifier}',
		description:
			'Tool to delete an invitation by its identifier. Use when you need to remove or revoke an invitation after confirming the invitation identifier.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteMapping',
		group: 'mappings',
		name: 'deleteMapping',
		method: 'DELETE',
		path: '/mappings/{identifier}',
		description:
			'Tool to delete a specific mapping by its identifier. Use when you need to remove an unused or incorrect mapping from the database. Note: This endpoint is deprecated.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteOrganization',
		group: 'organizations',
		name: 'deleteOrganization',
		method: 'DELETE',
		path: '/organizations/{identifier}',
		description:
			'Permanently deletes an organization from Affinda. This action is destructive and cannot be undone. All workspaces, collections, and documents associated with the organization will also be deleted. Use the get_organizations action first to confirm the organization identifier before deletion.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteResthookSubscription',
		group: 'resthooks',
		name: 'deleteResthookSubscription',
		method: 'DELETE',
		path: '/resthook_subscriptions/{id}',
		description:
			'Tool to delete a specific resthook subscription by ID. Use after confirming the subscription identifier when the webhook is no longer needed.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteTag',
		group: 'tags',
		name: 'deleteTag',
		method: 'DELETE',
		path: '/tags/{id}',
		description:
			'Permanently delete a tag from Affinda by its ID. This is a destructive operation that cannot be undone. Use Get Tags first to verify the tag ID before deletion.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteValidationResults',
		group: 'validationResults',
		name: 'deleteValidationResults',
		method: 'POST',
		path: '/validation_results/batch_delete',
		description:
			"Delete multiple validation results in a single API call. Use this action to efficiently remove multiple validation results at once rather than making individual delete requests for each validation result. Prerequisites: - Obtain validation result IDs using the 'Get All Validation Results' action Common use cases: - Removing obsolete validation results in bulk - Cleaning up validation results after reprocessing documents - Deleting validation results for specific documents programmatically",
		pathParams: [],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteWorkspace',
		group: 'workspaces',
		name: 'deleteWorkspace',
		method: 'DELETE',
		path: '/workspaces/{identifier}',
		description:
			'Tool to delete a specific workspace by its ID. Use when you need to remove an unused workspace after confirming the workspace ID.',
		pathParams: ['workspace_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteWorkspaceMembership',
		group: 'workspaceMemberships',
		name: 'deleteWorkspaceMembership',
		method: 'DELETE',
		path: '/workspace_memberships/{identifier}',
		description:
			'Tool to remove a user from a workspace by membership ID. Use after confirming the workspace membership ID to revoke access.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'getAllApiUsers',
		group: 'apiUsers',
		name: 'getAllApiUsers',
		method: 'GET',
		path: '/api_users',
		description:
			'Tool to retrieve a list of all API users. Use when you need to list API users, optionally filtered by organization.',
		pathParams: [],
		queryParams: ['limit', 'offset', 'organization'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllDocumentSplitters',
		group: 'documentSplitters',
		name: 'getAllDocumentSplitters',
		method: 'GET',
		path: '/document_splitters',
		description:
			'Tool to get a list of all document splitters. Use when you need to retrieve document splitters, optionally filtered by organization.',
		pathParams: [],
		queryParams: ['limit', 'offset', 'organization', 'includePublic'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllInvitations',
		group: 'invitations',
		name: 'getAllInvitations',
		method: 'GET',
		path: '/invitations',
		description:
			'Tool to retrieve all invitations you created or sent to you. Use when you need to list organization invitations with optional filtering by status, role, or organization.',
		pathParams: [],
		queryParams: ['role', 'limit', 'offset', 'status', 'organization'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllOrganizationMemberships',
		group: 'organizationMemberships',
		name: 'getAllOrganizationMemberships',
		method: 'GET',
		path: '/organization_memberships',
		description:
			'Retrieve all organization memberships across the account. Returns paginated results showing which users belong to which organizations. Use to audit organization access or find specific user memberships.',
		pathParams: [],
		queryParams: ['role', 'limit', 'offset', 'organization'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllTags',
		group: 'tags',
		name: 'getAllTags',
		method: 'GET',
		path: '/tags',
		description:
			'Tool to list all tags. Use after confirming authentication to fetch tags across workspaces.',
		pathParams: [],
		queryParams: ['name', 'limit', 'offset', 'workspace'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllValidationResults',
		group: 'validationResults',
		name: 'getAllValidationResults',
		method: 'GET',
		path: '/validation_results',
		description:
			'Tool to list validation results for documents. Use after processing documents to inspect validation outcomes.',
		pathParams: [],
		queryParams: ['limit', 'offset', 'document'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllWorkspaceMemberships',
		group: 'workspaceMemberships',
		name: 'getAllWorkspaceMemberships',
		method: 'GET',
		path: '/workspace_memberships',
		description:
			'Retrieve all workspace memberships across the account. Returns paginated results showing which users belong to which workspaces. Use to audit workspace access or find specific user memberships.',
		pathParams: [],
		queryParams: ['user', 'limit', 'offset', 'workspace'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAnnotations',
		group: 'annotations',
		name: 'getAnnotations',
		method: 'GET',
		path: '/annotations',
		description:
			'Retrieves all annotations for a specific document. Annotations are extracted data fields (text, dates, numbers, tables, etc.) from parsed documents. Use this after a document has been processed to access the extracted data.',
		pathParams: [],
		queryParams: ['document'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCollection',
		group: 'collections',
		name: 'getCollection',
		method: 'GET',
		path: '/collections/{identifier}',
		description:
			'Tool to retrieve details of a specific collection by its ID. Use when you need full metadata about a collection after confirming its identifier.',
		pathParams: ['collection_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCollectionFields',
		group: 'collections',
		name: 'getCollectionFields',
		method: 'GET',
		path: '/collections/{identifier}/fields/{datapoint_identifier}',
		description:
			'Tool to retrieve data field configuration for a collection associated with a data point. Use when you need to understand the structure and validation rules of a specific field in a collection. Note: This endpoint is deprecated.',
		pathParams: ['identifier', 'datapoint_identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCollections',
		group: 'collections',
		name: 'getCollections',
		method: 'GET',
		path: '/collections',
		description:
			'Tool to retrieve a list of all collections. Use when you need to list collections in your Affinda workspace after authentication.',
		pathParams: [],
		queryParams: ['limit', 'offset', 'workspace'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCollectionUsage',
		group: 'collections',
		name: 'getCollectionUsage',
		method: 'GET',
		path: '/collections/{identifier}/usage',
		description:
			'Retrieves monthly credits consumption statistics for a specific collection. Returns a list of usage records showing how many credits were consumed each month. Use this to track collection activity, monitor consumption trends, or generate usage reports. Note: This endpoint is deprecated.',
		pathParams: ['identifier'],
		queryParams: ['end', 'start'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDataPoint',
		group: 'dataPoints',
		name: 'getDataPoint',
		method: 'GET',
		path: '/data_points/{identifier}',
		description:
			"Tool to retrieve details of a specific data point by its identifier. Use when you need to inspect a data point's configuration, type, or structure. Data points represent individual fields that can be extracted from documents (e.g., 'name', 'email', 'date'). This endpoint is deprecated but still functional for retrieving data point metadata.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDataPointChoice',
		group: 'dataPointChoices',
		name: 'getDataPointChoice',
		method: 'GET',
		path: '/data_point_choices/{id}',
		description:
			'Tool to return a specific data point choice by its ID. Use when you need details about a particular data point choice option. Note: This endpoint is deprecated but still functional.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDataSource',
		group: 'dataSources',
		name: 'getDataSource',
		method: 'GET',
		path: '/mapping_data_sources/{identifier}',
		description:
			'Tool to retrieve details of a specific mapping data source by its identifier. Use when you need to fetch mapping data source metadata and schema configuration.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDataSourceValue',
		group: 'dataSources',
		name: 'getDataSourceValue',
		method: 'GET',
		path: '/mapping_data_sources/{identifier}/values/{value}',
		description:
			'Tool to retrieve a specific value from a mapping data source. Use when you need to get details about a particular value in a data source.',
		pathParams: ['identifier', 'value'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDataSourceValues',
		group: 'dataSources',
		name: 'getDataSourceValues',
		method: 'GET',
		path: '/mapping_data_sources/{identifier}/values',
		description:
			'Tool to retrieve all values from a mapping data source. Use when you need to list or search values in a specific data source after authentication.',
		pathParams: ['identifier'],
		queryParams: ['limit', 'offset', 'search', 'document', 'annotation'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocument',
		group: 'documents',
		name: 'getDocument',
		method: 'GET',
		path: '/documents/{identifier}',
		description:
			'Retrieve full details and parsed data for a specific document by its identifier. Use this tool to get comprehensive information about a document including: - Processing status (ready/failed) - Document metadata (file name, page count, language) - Parsed/extracted data results - URLs for PDF, original file, and review page - Collection and workspace information The document identifier can be either a system-generated ID or a custom identifier set during document upload.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocumentRedacted',
		group: 'documents',
		name: 'getDocumentRedacted',
		method: 'GET',
		path: '/documents/{identifier}/redacted',
		description:
			'Tool to retrieve the redacted version of a document as a PDF file. Use when you need to get a document with sensitive information removed. The original document is not modified by this operation.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocuments',
		group: 'documents',
		name: 'getDocuments',
		method: 'GET',
		path: '/documents',
		description:
			'Tool to retrieve a list of all documents. Use when you need to list documents in your Affinda workspace after authentication.',
		pathParams: [],
		queryParams: [
			'count',
			'limit',
			'ready',
			'state',
			'failed',
			'offset',
			'search',
			'compact',
			'ordering',
			'workspace',
			'collection',
			'include_data',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocumentSplitter',
		group: 'documentSplitters',
		name: 'getDocumentSplitter',
		method: 'GET',
		path: '/document_splitters/{identifier}',
		description:
			'Tool to retrieve details of a specific document splitter by its identifier. Use when you need to fetch metadata about a document splitter configuration.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocumentType',
		group: 'documentTypes',
		name: 'getDocumentType',
		method: 'GET',
		path: '/document_types/{identifier}',
		description:
			'Tool to retrieve details of a specific document type by its ID. Use when you need to confirm the configuration or metadata of a document type before processing documents.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocumentTypeJsonSchema',
		group: 'documentTypes',
		name: 'getDocumentTypeJsonSchema',
		method: 'GET',
		path: '/document_types/{identifier}/json_schema',
		description:
			'Tool to generate a JSON schema from a document type by its identifier. Use when you need the structured schema definition for a document type to understand its field structure and validation rules.',
		pathParams: ['identifier'],
		queryParams: ['title'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocumentTypePydanticModels',
		group: 'documentTypes',
		name: 'getDocumentTypePydanticModels',
		method: 'GET',
		path: '/document_types/{identifier}/pydantic_models',
		description:
			"Tool to generate Pydantic model code from a document type's schema. Use when you need type-safe Python models for parsing documents of a specific type.",
		pathParams: ['identifier'],
		queryParams: ['model_name'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDocumentTypes',
		group: 'documentTypes',
		name: 'getDocumentTypes',
		method: 'GET',
		path: '/document_types',
		description:
			"Retrieve all document types accessible to the authenticated user. Returns a list containing each document type's identifier, name, description, ingest email, and organization. Use this to discover available document types before uploading or processing documents. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getExtractor',
		group: 'extractors',
		name: 'getExtractor',
		method: 'GET',
		path: '/extractors/{identifier}',
		description:
			"Tool to retrieve detailed information about a specific extractor by its identifier. Use when you need complete metadata about an extractor's configuration, fields, and capabilities.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getExtractors',
		group: 'extractors',
		name: 'getExtractors',
		method: 'GET',
		path: '/extractors',
		description:
			"Retrieve all extractors available for an organization. Extractors are document parsing configurations that define what data to extract from documents. This includes both Affinda's built-in extractors (resumes, invoices, etc.) and any custom extractors created for the organization. Use this action to: - List available extractors before creating a collection - Find the identifier of a specific extractor type - Check if custom extractors exist for the organization",
		pathParams: [],
		queryParams: [
			'organization',
			'include_public_extractors',
			'name',
			'validatable',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getIndexDocuments',
		group: 'indexes',
		name: 'getIndexDocuments',
		method: 'GET',
		path: '/index/{name}/documents',
		description:
			'Tool to retrieve all indexed documents for a specific index. Use when you need to list documents in a search index after creating or accessing an index.',
		pathParams: ['name'],
		queryParams: ['limit', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getInvitation',
		group: 'invitations',
		name: 'getInvitation',
		method: 'GET',
		path: '/invitations/{identifier}',
		description:
			'Tool to retrieve details of a specific organization invitation by its identifier. Use when you need to check invitation status or get invitation metadata.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobDescriptionSearchConfig',
		group: 'jobDescriptionSearch',
		name: 'getJobDescriptionSearchConfig',
		method: 'GET',
		path: '/job_description_search/config',
		description:
			"Tool to get the configuration for the logged in user's embeddable job description search tool. Returns display settings, field weights, and maximum results limits. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getMapping',
		group: 'mappings',
		name: 'getMapping',
		method: 'GET',
		path: '/mappings/{identifier}',
		description:
			'Tool to retrieve a specific mapping by its identifier. Use when you need to fetch mapping configuration details for a lookup against a MappingDataSource.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganization',
		group: 'organizations',
		name: 'getOrganization',
		method: 'GET',
		path: '/organizations/{identifier}',
		description:
			"Tool to retrieve details of a specific organization by its ID. Use when you need to fetch an organization's metadata after confirming its identifier.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizationMembership',
		group: 'organizationMemberships',
		name: 'getOrganizationMembership',
		method: 'GET',
		path: '/organization_memberships/{identifier}',
		description:
			"Tool to retrieve details of a specific organization membership by its ID. Use when you need to confirm a user's role and details within an organization.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizations',
		group: 'organizations',
		name: 'getOrganizations',
		method: 'GET',
		path: '/organizations',
		description:
			"Retrieves all organizations accessible to the authenticated user. Returns a list of organizations with details including identifier, name, user role, trial status, and configuration settings. Use the 'identifier' field from the response when calling other organization-related endpoints. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getResthookSubscription',
		group: 'resthooks',
		name: 'getResthookSubscription',
		method: 'GET',
		path: '/resthook_subscriptions/{id}',
		description:
			'Tool to retrieve details of a specific resthook subscription by its ID. Use after confirming its creation to verify its settings.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getResthookSubscriptions',
		group: 'resthooks',
		name: 'getResthookSubscriptions',
		method: 'GET',
		path: '/resthook_subscriptions',
		description:
			'Tool to retrieve a list of all RESTHook subscriptions. Use after authenticating to list all webhook subscriptions associated with your account.',
		pathParams: [],
		queryParams: ['limit', 'offset'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTag',
		group: 'tags',
		name: 'getTag',
		method: 'GET',
		path: '/tags/{id}',
		description:
			'Tool to retrieve details of a specific tag by its ID. Use when you need to fetch information about a particular tag.',
		pathParams: ['tag_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUsageByWorkspace',
		group: 'workspaces',
		name: 'getUsageByWorkspace',
		method: 'GET',
		path: '/workspaces/{identifier}/usage',
		description:
			'Retrieves monthly document processing usage statistics for a specific workspace. Returns a list of usage records showing how many documents were processed each month. Use this to track workspace activity, monitor consumption trends, or generate usage reports.',
		pathParams: ['workspace_id'],
		queryParams: ['end', 'start'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkspace',
		group: 'workspaces',
		name: 'getWorkspace',
		method: 'GET',
		path: '/workspaces/{identifier}',
		description:
			'Tool to retrieve details of a specific workspace by its ID. Use when you need full workspace metadata after confirming its identifier.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkspaceMembership',
		group: 'workspaceMemberships',
		name: 'getWorkspaceMembership',
		method: 'GET',
		path: '/workspace_memberships/{identifier}',
		description:
			"Tool to retrieve details of a specific workspace membership by its ID. Use when you need to confirm a user's role and details within a workspace after obtaining the membership identifier.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkspaces',
		group: 'workspaces',
		name: 'getWorkspaces',
		method: 'GET',
		path: '/workspaces',
		description:
			'Tool to retrieve a list of all workspaces. Use when you need to list workspaces filtered by organization and optional name.',
		pathParams: [],
		queryParams: ['name', 'organization'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listDataPointChoices',
		group: 'dataPointChoices',
		name: 'listDataPointChoices',
		method: 'GET',
		path: '/data_point_choices',
		description:
			"Tool to retrieve available choices for a specific enum data point. Use when you need to discover valid options for dropdown/enum fields in a collection's data schema. Note: This endpoint is deprecated but still functional for accessing data point choice metadata.",
		pathParams: [],
		queryParams: ['limit', 'offset', 'search', 'collection', 'data_point'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listDataPoints',
		group: 'dataPoints',
		name: 'listDataPoints',
		method: 'GET',
		path: '/data_points',
		description:
			"Tool to retrieve all data points. Returns both custom data points and Affinda's off-the-shelf data points. Use when you need to list available data points for extractors.",
		pathParams: [],
		queryParams: [
			'slug',
			'limit',
			'offset',
			'extractor',
			'identifier',
			'description',
			'organization',
			'include_public',
			'annotation_content_type',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listDataSources',
		group: 'dataSources',
		name: 'listDataSources',
		method: 'GET',
		path: '/mapping_data_sources',
		description:
			'Tool to retrieve the list of all custom mapping data sources. Use when you need to list or search for mapping data sources in your Affinda workspace.',
		pathParams: [],
		queryParams: [
			'name',
			'limit',
			'offset',
			'workspace',
			'identifier',
			'organization',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listIndexes',
		group: 'indexes',
		name: 'listIndexes',
		method: 'GET',
		path: '/index',
		description:
			'Tool to retrieve a list of all search indexes. Use when you need to view available indexes for searching and matching documents in Affinda.',
		pathParams: [],
		queryParams: ['name', 'limit', 'offset', 'document_type'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listMappings',
		group: 'mappings',
		name: 'listMappings',
		method: 'GET',
		path: '/mappings',
		description:
			'Tool to retrieve the list of all custom data mappings. Use when you need to list mappings for a specific data source.',
		pathParams: [],
		queryParams: ['limit', 'offset', 'mappingDataSource'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listOccupationGroups',
		group: 'occupationGroups',
		name: 'listOccupationGroups',
		method: 'GET',
		path: '/occupation_groups',
		description:
			'Tool to retrieve the list of searchable occupation groups. Use when you need to get available occupation categories for job matching or classification. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listResumeSearchConfig',
		group: 'resumeSearch',
		name: 'listResumeSearchConfig',
		method: 'GET',
		path: '/resume_search/config',
		description:
			"Tool to get the configuration for the logged in user's embeddable resume search tool. Use this to retrieve display field settings, search weights, maximum results, and theme customization options for the resume search interface. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listResumeSearchJobTitleSuggestions',
		group: 'resumeSearch',
		name: 'listResumeSearchJobTitleSuggestions',
		method: 'GET',
		path: '/resume_search/suggestion_job_title',
		description:
			'Tool to get job title suggestions based on provided job title(s). Use when you need to find related job titles for resume search.',
		pathParams: [],
		queryParams: ['job_titles'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listResumeSearchSkillSuggestions',
		group: 'resumeSearch',
		name: 'listResumeSearchSkillSuggestions',
		method: 'GET',
		path: '/resume_search/suggestion_skill',
		description:
			'Tool to get skill suggestions based on provided skills. Use when you need to find related skills to expand or refine resume search queries.',
		pathParams: [],
		queryParams: ['skills'],
		riskLevel: 'read' as const,
	},
	{
		key: 'removeTagFromDocuments',
		group: 'documents',
		name: 'removeTagFromDocuments',
		method: 'POST',
		path: '/documents/batch_remove_tag',
		description:
			"Remove a tag from multiple documents in a single batch operation. Use this action to efficiently untag many documents at once rather than making individual remove requests. The operation is idempotent - removing a tag that isn't present on a document will not cause an error.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'replaceDataPointChoices',
		group: 'dataPointChoices',
		name: 'replaceDataPointChoices',
		method: 'POST',
		path: '/data_point_choices/replace',
		description:
			'Tool to completely replace all choices for a data point. Use when you need to bulk update enum options - existing choices are matched by value, new values are created, updated values are modified, and values not in the incoming list are deleted. Note: This is a deprecated endpoint but still functional. Either collection or organization must be specified to scope the replacement.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'replaceDataSourceValues',
		group: 'dataSources',
		name: 'replaceDataSourceValues',
		method: 'PUT',
		path: '/mapping_data_sources/{identifier}/values',
		description:
			"Tool to completely replace all values in a mapping data source. Use when you need to bulk update or refresh an entire data source's value list. Note: For large data sources (>1000 values), new values may take a few minutes to become searchable after the operation completes.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'splitDocumentPages',
		group: 'validation',
		name: 'splitDocumentPages',
		method: 'POST',
		path: '/validate/{identifier}/split',
		description:
			'Split a document into multiple documents by dividing its pages. Use when you need to separate a multi-page document into distinct documents based on page groupings. Prerequisites: - Obtain the document identifier from create_document or get_document actions - Use get_document to retrieve page IDs for the pages you want to split Important notes: - Each page can only be assigned to one split - All pages should be accounted for across all splits - One split can optionally use the original document identifier to maintain the root document',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateAnnotation',
		group: 'annotations',
		name: 'updateAnnotation',
		method: 'PATCH',
		path: '/annotations/{id}',
		description:
			"Tool to update data of a single annotation in Affinda. Use when you need to correct extracted values, verify annotations, or modify annotation metadata after document processing. Prerequisites: - Obtain the annotation ID using the 'Get Annotations' action with a document filter - Annotations must exist in documents that have been processed by Affinda Common use cases: - Correcting OCR or extraction errors in individual fields - Marking annotations as verified after manual review (set isClientVerified=true) - Updating parsed values to fix incorrect data extraction - Modifying annotation coordinates or page references Note: For bulk updates across multiple annotations, use the 'Batch Update Annotations' action instead for better efficiency.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateCollection',
		group: 'collections',
		name: 'updateCollection',
		method: 'PATCH',
		path: '/collections/{identifier}',
		description:
			'Tool to update specific fields of a collection. Use when you need to rename or reassign a collection after creation.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDataFieldForCollection',
		group: 'collections',
		name: 'updateDataFieldForCollection',
		method: 'PATCH',
		path: '/collections/{identifier}/fields/{datapoint_identifier}',
		description:
			"Tool to update a data field configuration for a collection's data point. Use when you need to modify field properties such as label, type, mandatory status, or validation settings after the field has been created.",
		pathParams: ['identifier', 'datapoint_identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDataPoint',
		group: 'dataPoints',
		name: 'updateDataPoint',
		method: 'PATCH',
		path: '/data_points/{identifier}',
		description:
			"Tool to update data of a data point by its identifier. Use when you need to modify a data point's name, description, slug, parent, or mapping data source. Note: This endpoint is deprecated but still functional.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDataPointChoice',
		group: 'dataPointChoices',
		name: 'updateDataPointChoice',
		method: 'PATCH',
		path: '/data_point_choices/{id}',
		description:
			'Tool to update data of a data point choice by its ID. Use when you need to modify label, value, description, synonyms, or associated collection/organization for an existing data point choice. Note: This endpoint is deprecated but still functional.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDataSourceValue',
		group: 'dataSources',
		name: 'updateDataSourceValue',
		method: 'PUT',
		path: '/mapping_data_sources/{identifier}/values/{value}',
		description:
			'Tool to update an existing value in a mapping data source. Use when you need to modify the label or description of an existing data source value. The value identifier itself cannot be changed.',
		pathParams: ['identifier', 'value'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDocument',
		group: 'documents',
		name: 'updateDocument',
		method: 'PATCH',
		path: '/documents/{identifier}',
		description:
			'Tool to update specific fields of a document. Use when you need to rename, reassign, or adjust expiry and storage settings after document creation.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDocumentData',
		group: 'documents',
		name: 'updateDocumentData',
		method: 'POST',
		path: '/documents/{identifier}/update_data',
		description:
			"Update parsed data for a resume or job description document in Affinda. This endpoint is ONLY applicable for documents that have been processed with 'resume' or 'job-description' extractors. For other document types, use the batch_update_annotations endpoint instead. Use this tool when you need to correct or add parsed fields to an existing resume or job description document after it has been uploaded and processed.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDocumentType',
		group: 'documentTypes',
		name: 'updateDocumentType',
		method: 'PATCH',
		path: '/document_types/{identifier}',
		description:
			'Tool to update a document type by its identifier. Use when you need to modify the name or description of an existing document type.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateExtractor',
		group: 'extractors',
		name: 'updateExtractor',
		method: 'PATCH',
		path: '/extractors/{identifier}',
		description:
			"Tool to update specific fields of an extractor. Use when you need to modify an extractor's name, category, validation settings, or field groups after creation.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateIndex',
		group: 'indexes',
		name: 'updateIndex',
		method: 'PATCH',
		path: '/index/{name}',
		description:
			'Tool to update the name of an existing search index. Use when you need to rename an index after creation.',
		pathParams: ['name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateInvitation',
		group: 'invitations',
		name: 'updateInvitation',
		method: 'PATCH',
		path: '/invitations/{identifier}',
		description:
			"Tool to update an organization invitation's role. Use when you need to change the role assigned to an invitation before it is accepted.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateJobDescriptionSearchConfig',
		group: 'jobDescriptionSearch',
		name: 'updateJobDescriptionSearchConfig',
		method: 'PATCH',
		path: '/job_description_search/config',
		description:
			"Tool to update the configuration for the logged in user's embeddable job description search tool. Use to configure display fields, field weights, maximum results, and UI customization options.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateMapping',
		group: 'mappings',
		name: 'updateMapping',
		method: 'PATCH',
		path: '/mappings/{identifier}',
		description:
			"Tool to update a specific mapping's settings. Use when you need to adjust score cutoff or ordering for a lookup against a MappingDataSource.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateOrganization',
		group: 'organizations',
		name: 'updateOrganization',
		method: 'PATCH',
		path: '/organizations/{identifier}',
		description:
			"Tool to update specific fields of an organization. Use when you need to modify an organization's name, avatar, or webhook and validation settings after creation.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateOrganizationMembership',
		group: 'organizationMemberships',
		name: 'updateOrganizationMembership',
		method: 'PATCH',
		path: '/organization_memberships/{identifier}',
		description:
			"Tool to update an organization membership's role. Use when you need to change a user's role within an organization.",
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateResthookSubscription',
		group: 'resthooks',
		name: 'updateResthookSubscription',
		method: 'PATCH',
		path: '/resthook_subscriptions/{id}',
		description:
			'Tool to update an existing RESTHook subscription. Use after confirming the subscription identifier to modify its URL, event, or activation status.',
		pathParams: ['identifier'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateResumeSearchConfig',
		group: 'resumeSearch',
		name: 'updateResumeSearchConfig',
		method: 'PATCH',
		path: '/resume_search/config',
		description:
			"Tool to update the configuration for the logged in user's embeddable resume search tool. Use this to modify which fields are displayed, their search weights, maximum results limit, distance units, custom actions, and theme settings.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTag',
		group: 'tags',
		name: 'updateTag',
		method: 'PATCH',
		path: '/tags/{id}',
		description:
			"Tool to update data of a tag. Use when you need to modify a tag's name or reassign it to a different workspace. Only provide the fields you want to change; other fields will remain unchanged.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateWorkspace',
		group: 'workspaces',
		name: 'updateWorkspace',
		method: 'PATCH',
		path: '/workspaces/{identifier}',
		description:
			"Tool to update specific fields of a workspace. Use when you need to modify a workspace's name, visibility, document rejection policy, or other settings. Only provide the fields you want to change; other fields will remain unchanged.",
		pathParams: ['workspace_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
] as const;

export type AffindaRoutes = typeof affindaRoutes;
