import type { PrismaOperation } from '../endpoints/operation-types';

export const databasesOperations = [
	{
		key: 'createDatabase',
		group: 'databases',
		name: 'create',
		method: 'POST',
		path: '/projects/{projectId}/databases',
		pathParams: ['projectId'],
		riskLevel: 'write',
		description: 'Create a database in a project',
	},
	{
		key: 'getDatabase',
		group: 'databases',
		name: 'get',
		method: 'GET',
		path: '/databases/{databaseId}',
		pathParams: ['databaseId'],
		riskLevel: 'read',
		description: 'Retrieve database details',
	},
	{
		key: 'listDatabases',
		group: 'databases',
		name: 'list',
		method: 'GET',
		path: '/projects/{projectId}/databases',
		pathParams: ['projectId'],
		riskLevel: 'read',
		description: 'List databases for a project',
	},
	{
		key: 'deleteDatabase',
		group: 'databases',
		name: 'delete',
		method: 'DELETE',
		path: '/databases/{databaseId}',
		pathParams: ['databaseId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a database and all of its data',
	},
	{
		key: 'getDatabaseUsage',
		group: 'databases',
		name: 'getUsage',
		method: 'GET',
		path: '/databases/{databaseId}/usage',
		pathParams: ['databaseId'],
		riskLevel: 'read',
		description: 'Retrieve database usage metrics for a time period',
	},
	{
		key: 'inspectDatabaseSchema',
		group: 'databases',
		name: 'inspectSchema',
		method: 'POST',
		path: '/schema',
		pathParams: [],
		riskLevel: 'read',
		kind: 'schema',
		description:
			'Inspect a database schema (tables, columns, types, constraints)',
	},
] as const satisfies readonly PrismaOperation[];
