import { logEventFromContext } from 'corsair/core';
import type { BigmailerEndpoints } from '../index';
import { BigmailerSuppressionListEntity } from '../schema/database';
import { auditPayload } from './logging';
import { cacheEntities, cacheEntity } from './persist';
import { bigmailerCall, compact, seg } from './shared';
import type { BigmailerEndpointOutputs } from './types';

const LABEL = 'suppression list';

/** A suppression list's `id` is only unique *within* its brand. Composite `brand:id` key. */
const entityId = (s: { brandId?: string; id: string }) =>
	`${s.brandId}:${s.id}`;

/** Lists campaign suppression lists within a brand. */
export const list: BigmailerEndpoints['suppressionListsList'] = async (
	ctx,
	input,
) => {
	const result = await bigmailerCall<
		BigmailerEndpointOutputs['suppressionListsList']
	>(ctx, `brands/${seg(input.brandId)}/suppression-lists`, {
		query: compact({ limit: input.limit, cursor: input.cursor }),
	});

	await cacheEntities(
		ctx.db.suppressionLists,
		BigmailerSuppressionListEntity,
		result.data.map((s) => ({ ...s, brandId: input.brandId })),
		{ label: LABEL, entityId },
	);
	await logEventFromContext(
		ctx,
		'bigmailer.suppressionLists.list',
		{ ...auditPayload(input, ['brandId']), returned: result.data.length },
		'completed',
	);
	return result;
};

/**
 * Uploads a campaign suppression list. Confirmed live from
 * `createsuppressionlist.md`'s own OpenAPI `requestBody`:
 * `multipart/form-data` with a single required `file` field
 * (`type: string, format: binary`) - not a JSON body, contrary to an
 * earlier, unverified version of this file that guessed a base64 JSON
 * field by analogy to brands' `logo`. There is also no `file_name` request
 * field; `file_name` on the response is derived server-side. `input.file`
 * is still a base64 string at the endpoint boundary (this repo's convention
 * for binary input, e.g. Loyverse's item-image upload) and is decoded to a
 * `Blob` here, which is what actually goes out as the multipart part -
 * `client.ts`'s `formData` option leaves `Content-Type` to be generated by
 * `fetch` itself from the `FormData` instance.
 */
export const create: BigmailerEndpoints['suppressionListsCreate'] = async (
	ctx,
	input,
) => {
	const result = await bigmailerCall<
		BigmailerEndpointOutputs['suppressionListsCreate']
	>(ctx, `brands/${seg(input.brandId)}/suppression-lists`, {
		method: 'POST',
		formData: {
			file: new Blob([Buffer.from(input.file, 'base64')], {
				type: 'text/csv',
			}),
		},
	});

	await cacheEntity(
		ctx.db.suppressionLists,
		BigmailerSuppressionListEntity,
		{ ...result, brandId: input.brandId },
		{ label: LABEL, entityId },
	);
	await logEventFromContext(
		ctx,
		'bigmailer.suppressionLists.create',
		auditPayload(input, ['brandId']),
		'completed',
	);
	return result;
};

/**
 * Retrieves a single suppression list. `.../suppression-lists/{id}` -
 * confirmed live from `getsuppressionlist.md`'s own OpenAPI path template
 * (an earlier, unverified version of this file used the underscore
 * `suppression_lists`, which does not exist - every path on this resource
 * uses a hyphen).
 */
export const get: BigmailerEndpoints['suppressionListsGet'] = async (
	ctx,
	input,
) => {
	const result = await bigmailerCall<
		BigmailerEndpointOutputs['suppressionListsGet']
	>(
		ctx,
		`brands/${seg(input.brandId)}/suppression-lists/${seg(input.suppressionListId)}`,
	);

	await cacheEntity(
		ctx.db.suppressionLists,
		BigmailerSuppressionListEntity,
		{ ...result, brandId: input.brandId },
		{ label: LABEL, entityId },
	);
	await logEventFromContext(
		ctx,
		'bigmailer.suppressionLists.get',
		auditPayload(input, ['brandId', 'suppressionListId']),
		'completed',
	);
	return result;
};
