import { logEventFromContext } from 'corsair/core';
import type { z } from 'zod';
import { getClientaryCredentials, makeClientaryRequest } from '../client';
import type { ClientaryEndpoints } from '../index';
import { cacheRecord, cacheRecords, evictEntity } from './persist';
import type { ClientaryInvoice } from './types';
import {
	ClientaryDeleteResponseSchema,
	ClientaryEndpointOutputSchemas,
	ClientaryInvoiceSchema,
	ClientarySendResponseSchema,
} from './types';

/**
 * List all invoices, optionally filtered by `updated_since`.
 *
 * API: GET /api/v2/invoices
 * Docs: https://www.clientary.com/api/invoices
 */
export const list: ClientaryEndpoints['invoicesList'] = async (ctx, input) => {
	const { apiKey, domain } = await getClientaryCredentials(ctx);

	const response = await makeClientaryRequest<
		z.infer<typeof ClientaryEndpointOutputSchemas.invoicesList>
	>('invoices', apiKey, domain, {
		query: {
			page: input.page,
			page_size: input.page_size,
			updated_since: input.updated_since,
		},
	});

	const parsed = ClientaryEndpointOutputSchemas.invoicesList.parse(response);

	await cacheRecords(ctx.db.invoices, parsed.invoices, 'invoice');

	await logEventFromContext(
		ctx,
		'clientary.invoices.list',
		{ ...input },
		'completed',
	);
	return parsed;
};

/**
 * List invoices belonging to a single client.
 *
 * API: GET /api/v2/clients/:client_id/invoices
 * Docs: https://www.clientary.com/api/invoices
 */
export const listForClient: ClientaryEndpoints['invoicesListForClient'] =
	async (ctx, input) => {
		const { apiKey, domain } = await getClientaryCredentials(ctx);

		const response = await makeClientaryRequest<
			z.infer<typeof ClientaryEndpointOutputSchemas.invoicesListForClient>
		>(`clients/${input.client_id}/invoices`, apiKey, domain, {
			query: {
				page: input.page,
				page_size: input.page_size,
			},
		});

		const parsed =
			ClientaryEndpointOutputSchemas.invoicesListForClient.parse(response);

		await cacheRecords(ctx.db.invoices, parsed.invoices, 'invoice');

		await logEventFromContext(
			ctx,
			'clientary.invoices.listForClient',
			{ client_id: input.client_id },
			'completed',
		);
		return parsed;
	};

/**
 * List invoices belonging to a single project.
 *
 * API: GET /api/v2/projects/:project_id/invoices
 * Docs: https://www.clientary.com/api/invoices
 */
export const listForProject: ClientaryEndpoints['invoicesListForProject'] =
	async (ctx, input) => {
		const { apiKey, domain } = await getClientaryCredentials(ctx);

		const response = await makeClientaryRequest<
			z.infer<typeof ClientaryEndpointOutputSchemas.invoicesListForProject>
		>(`projects/${input.project_id}/invoices`, apiKey, domain, {
			query: {
				page: input.page,
				page_size: input.page_size,
			},
		});

		const parsed =
			ClientaryEndpointOutputSchemas.invoicesListForProject.parse(response);

		await cacheRecords(ctx.db.invoices, parsed.invoices, 'invoice');

		await logEventFromContext(
			ctx,
			'clientary.invoices.listForProject',
			{ project_id: input.project_id },
			'completed',
		);
		return parsed;
	};

/**
 * List invoices generated by a recurring schedule.
 *
 * API: GET /api/v2/recurring/:recurring_id/invoices
 * Docs: https://www.clientary.com/api/invoices
 */
export const listForRecurring: ClientaryEndpoints['invoicesListForRecurring'] =
	async (ctx, input) => {
		const { apiKey, domain } = await getClientaryCredentials(ctx);

		const response = await makeClientaryRequest<
			z.infer<typeof ClientaryEndpointOutputSchemas.invoicesListForRecurring>
		>(`recurring/${input.recurring_id}/invoices`, apiKey, domain, {
			query: {
				page: input.page,
				page_size: input.page_size,
			},
		});

		const parsed =
			ClientaryEndpointOutputSchemas.invoicesListForRecurring.parse(response);

		await cacheRecords(ctx.db.invoices, parsed.invoices, 'invoice');

		await logEventFromContext(
			ctx,
			'clientary.invoices.listForRecurring',
			{ recurring_id: input.recurring_id },
			'completed',
		);
		return parsed;
	};

/**
 * Get a single invoice by ID.
 *
 * API: GET /api/v2/invoices/:id
 * Docs: https://www.clientary.com/api/invoices
 */
export const get: ClientaryEndpoints['invoicesGet'] = async (ctx, input) => {
	const { apiKey, domain } = await getClientaryCredentials(ctx);

	const response = await makeClientaryRequest<ClientaryInvoice>(
		`invoices/${input.id}`,
		apiKey,
		domain,
	);

	const parsed = ClientaryInvoiceSchema.parse(response);

	await cacheRecord(ctx.db.invoices, parsed, 'invoice');

	await logEventFromContext(
		ctx,
		'clientary.invoices.get',
		{ id: input.id },
		'completed',
	);
	return parsed;
};

/**
 * Create a new invoice.
 *
 * API: POST /api/v2/invoices
 * Docs: https://www.clientary.com/api/invoices
 */
export const create: ClientaryEndpoints['invoicesCreate'] = async (
	ctx,
	input,
) => {
	const { apiKey, domain } = await getClientaryCredentials(ctx);

	const response = await makeClientaryRequest<ClientaryInvoice>(
		'invoices',
		apiKey,
		domain,
		{ method: 'POST', body: { invoice: { ...input } } },
	);

	const parsed = ClientaryInvoiceSchema.parse(response);

	await cacheRecord(ctx.db.invoices, parsed, 'invoice');

	await logEventFromContext(
		ctx,
		'clientary.invoices.create',
		{ id: parsed.id, client_id: parsed.client_id },
		'completed',
	);
	return parsed;
};

/**
 * Update an existing invoice.
 *
 * API: PUT /api/v2/invoice/:id
 * Docs: https://www.clientary.com/api/invoices
 */
export const update: ClientaryEndpoints['invoicesUpdate'] = async (
	ctx,
	input,
) => {
	const { apiKey, domain } = await getClientaryCredentials(ctx);
	const { id, ...fields } = input;

	const response = await makeClientaryRequest<ClientaryInvoice>(
		`invoice/${id}`,
		apiKey,
		domain,
		{ method: 'PUT', body: { invoice: { ...fields } } },
	);

	const parsed = ClientaryInvoiceSchema.parse(response);

	await cacheRecord(ctx.db.invoices, parsed, 'invoice');

	await logEventFromContext(
		ctx,
		'clientary.invoices.update',
		{ id },
		'completed',
	);
	return parsed;
};

/**
 * Delete an invoice.
 *
 * API: DELETE /api/v2/invoices/:id
 * Docs: https://www.clientary.com/api/invoices
 */
export const remove: ClientaryEndpoints['invoicesDelete'] = async (
	ctx,
	input,
) => {
	const { apiKey, domain } = await getClientaryCredentials(ctx);

	await makeClientaryRequest<unknown>(`invoices/${input.id}`, apiKey, domain, {
		method: 'DELETE',
	});

	await evictEntity(ctx.db.invoices, input.id, 'invoice');

	const result = ClientaryDeleteResponseSchema.parse({
		success: true,
		id: input.id,
	});

	await logEventFromContext(
		ctx,
		'clientary.invoices.delete',
		{ id: input.id },
		'completed',
	);
	return result;
};

/**
 * Send an invoice via email to one or more recipients.
 *
 * API: POST /api/v2/invoices/:id/messages
 * Docs: https://www.clientary.com/api/invoices
 */
export const send: ClientaryEndpoints['invoicesSend'] = async (ctx, input) => {
	const { apiKey, domain } = await getClientaryCredentials(ctx);
	const { id, ...message } = input;

	await makeClientaryRequest<unknown>(
		`invoices/${id}/messages`,
		apiKey,
		domain,
		{
			method: 'POST',
			body: { ...message },
		},
	);

	const result = ClientarySendResponseSchema.parse({
		sent: true,
		id,
	});

	await logEventFromContext(
		ctx,
		'clientary.invoices.send',
		{ id },
		'completed',
	);
	return result;
};
