import { z } from 'zod';

/**
 * Image variant metadata (original, thumb, medium) generated by ImgBB.
 */
export const ImgBBImageVariant = z
	.object({
		filename: z.string().optional(),
		name: z.string().optional(),
		mime: z.string().optional(),
		extension: z.string().optional(),
		url: z.string(),
	})
	.loose();

export type ImgBBImageVariant = z.infer<typeof ImgBBImageVariant>;

/**
 * ImgBB Image entity representing an uploaded image resource.
 * Transcribed from the official ImgBB API v1 response specification.
 */
export const ImgBBImage = z
	.object({
		id: z.string(),
		title: z.string().optional(),
		url_viewer: z.string().optional(),
		url: z.string(),
		display_url: z.string().optional(),
		width: z.coerce.number().optional(),
		height: z.coerce.number().optional(),
		size: z.coerce.number().optional(),
		time: z.coerce.number().optional(),
		expiration: z.coerce.number().optional(),
		image: ImgBBImageVariant.optional(),
		thumb: ImgBBImageVariant.optional(),
		medium: ImgBBImageVariant.optional(),
		delete_url: z.string().optional(),
	})
	.loose();

export type ImgBBImage = z.infer<typeof ImgBBImage>;
