import type { EndpointRiskLevel } from 'corsair/core';

export type FlutterwaveMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type FlutterwaveRoute = {
	key: string;
	group: string;
	name: string;
	method: FlutterwaveMethod;
	path: string;
	description: string;
	riskLevel: EndpointRiskLevel;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	// unknown is necessary because fixtures are request examples rather than contracts; a closed example union is infeasible because each of the 53 operations uses a different sample bag
	testInput?: Record<string, unknown>;
};

export const flutterwaveRoutes = [
	{
		key: 'cancelPaymentPlan',
		group: 'paymentPlans',
		name: 'cancel',
		method: 'PUT',
		path: '/payment-plans/{id}/cancel',
		description: 'Cancel a Flutterwave payment plan by ID.',
		riskLevel: 'write' as const,
		pathParams: ['id'],
		testInput: { id: 3874 },
	},
	{
		key: 'createBeneficiary',
		group: 'beneficiaries',
		name: 'create',
		method: 'POST',
		path: '/beneficiaries',
		description: 'Create a transfer beneficiary.',
		riskLevel: 'write' as const,
		testInput: {
			account_number: '0690000040',
			account_bank: '044',
			beneficiary_name: 'Alexis Sanchez',
		},
	},
	{
		key: 'createBulkTokenizedCharge',
		group: 'bulkTokenizedCharges',
		name: 'create',
		method: 'POST',
		path: '/bulk-tokenized-charges',
		description: 'Create a bulk tokenized charge batch.',
		riskLevel: 'write' as const,
		testInput: {
			title: 'Subscriptions',
			retry_strategy: 'none',
			bulk_data: [
				{
					token: 'tok_test',
					currency: 'NGN',
					amount: 1000,
					email: 'user@example.com',
					tx_ref: 'tx-ref-1',
				},
			],
		},
	},
	{
		key: 'createBulkVirtualAccountNumbers',
		group: 'bulkVirtualAccounts',
		name: 'create',
		method: 'POST',
		path: '/bulk-virtual-account-numbers',
		description: 'Create bulk virtual account numbers.',
		riskLevel: 'write' as const,
		testInput: {
			batch_ref: 'batch-ref-1',
			bulk_data: [
				{
					firstname: 'Alexis',
					lastname: 'Sanchez',
					email: 'user@example.com',
					bvn: '12345678901',
				},
			],
			is_permanent: true,
		},
	},
	{
		key: 'createPaymentLink',
		group: 'paymentLinks',
		name: 'create',
		method: 'POST',
		path: '/payments',
		description: 'Create a hosted payment link.',
		riskLevel: 'write' as const,
		testInput: {
			tx_ref: 'tx-ref-1',
			amount: 1000,
			currency: 'NGN',
			redirect_url: 'https://example.com/redirect',
			customer: { email: 'user@example.com' },
		},
	},
	{
		key: 'createPaymentPlan',
		group: 'paymentPlans',
		name: 'create',
		method: 'POST',
		path: '/payment-plans',
		description: 'Create a payment plan.',
		riskLevel: 'write' as const,
		testInput: { amount: 2000, name: 'Basic', interval: 'monthly' },
	},
	{
		key: 'createRefund',
		group: 'refunds',
		name: 'create',
		method: 'POST',
		path: '/transactions/{id}/refund',
		description: 'Create a refund for a transaction.',
		riskLevel: 'write' as const,
		pathParams: ['id'],
		testInput: { id: 1190701, amount: 1000 },
	},
	{
		key: 'createSubaccount',
		group: 'subaccounts',
		name: 'create',
		method: 'POST',
		path: '/subaccounts',
		description: 'Create a subaccount.',
		riskLevel: 'write' as const,
		testInput: {
			account_bank: '044',
			account_number: '0690000040',
			business_name: 'Demo',
			split_value: 0.2,
			country: 'NG',
			business_mobile: '08012345678',
		},
	},
	{
		key: 'createVirtualAccount',
		group: 'virtualAccounts',
		name: 'create',
		method: 'POST',
		path: '/virtual-account-numbers',
		description: 'Create a virtual account number.',
		riskLevel: 'write' as const,
		testInput: {
			email: 'user@example.com',
			firstname: 'Alexis',
			lastname: 'Sanchez',
			tx_ref: 'tx-ref-1',
			amount: 1000,
			narration: 'Payment',
		},
	},
	{
		key: 'deleteBeneficiary',
		group: 'beneficiaries',
		name: 'delete',
		method: 'DELETE',
		path: '/beneficiaries/{id}',
		description: 'Delete a beneficiary by ID.',
		riskLevel: 'destructive' as const,
		pathParams: ['id'],
		testInput: { id: 3768 },
	},
	{
		key: 'deleteSubaccount',
		group: 'subaccounts',
		name: 'delete',
		method: 'DELETE',
		path: '/subaccounts/{id}',
		description: 'Delete a subaccount by ID.',
		riskLevel: 'destructive' as const,
		pathParams: ['id'],
		testInput: { id: 3319 },
	},
	{
		key: 'disablePaymentLink',
		group: 'paymentLinks',
		name: 'disable',
		method: 'PUT',
		path: '/payments/{id}/disable',
		description: 'Disable an existing payment link.',
		riskLevel: 'write' as const,
		pathParams: ['id'],
		testInput: { id: 12345 },
	},
	{
		key: 'fetchBeneficiary',
		group: 'beneficiaries',
		name: 'get',
		method: 'GET',
		path: '/beneficiaries/{id}',
		description: 'Fetch a beneficiary by ID.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 3768 },
	},
	{
		key: 'fetchSubaccount',
		group: 'subaccounts',
		name: 'get',
		method: 'GET',
		path: '/subaccounts/{id}',
		description: 'Fetch a subaccount by ID.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 3319 },
	},
	{
		key: 'generateTransactionReference',
		group: 'transactions',
		name: 'generateReference',
		method: 'GET',
		path: '/transactions/reference',
		description: 'Generate a unique transaction reference.',
		riskLevel: 'read' as const,
		queryParams: ['prefix', 'length'],
		testInput: { prefix: 'tx', length: 16 },
	},
	{
		key: 'getAllSubscriptions',
		group: 'subscriptions',
		name: 'list',
		method: 'GET',
		path: '/subscriptions',
		description: 'Get all subscriptions, including cancelled.',
		riskLevel: 'read' as const,
		queryParams: [
			'email',
			'transaction_id',
			'plan',
			'subscribed_from',
			'subscribed_to',
			'next_due_from',
			'next_due_to',
			'page',
			'status',
		],
		testInput: { page: 1 },
	},
	{
		key: 'getAllWalletBalances',
		group: 'wallets',
		name: 'listBalances',
		method: 'GET',
		path: '/balances',
		description: 'Get wallet balances across currencies.',
		riskLevel: 'read' as const,
		testInput: {},
	},
	{
		key: 'getBalancesPerCurrency',
		group: 'wallets',
		name: 'getBalanceByCurrency',
		method: 'GET',
		path: '/balances/{currency}',
		description: 'Get wallet balance by currency.',
		riskLevel: 'read' as const,
		pathParams: ['currency'],
		testInput: { currency: 'NGN' },
	},
	{
		key: 'getBankBranches',
		group: 'banks',
		name: 'getBranches',
		method: 'GET',
		path: '/banks/{id}/branches',
		description: 'Get branches for a bank.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 173 },
	},
	{
		key: 'getBanksByCountry',
		group: 'banks',
		name: 'getByCountry',
		method: 'GET',
		path: '/banks/{country}',
		description: 'Get banks by country.',
		riskLevel: 'read' as const,
		pathParams: ['country'],
		queryParams: ['include_provider_type'],
		testInput: { country: 'NG' },
	},
	{
		key: 'getBillCategories',
		group: 'bills',
		name: 'getCategories',
		method: 'GET',
		path: '/top-bill-categories',
		description: 'Get bill categories.',
		riskLevel: 'read' as const,
		queryParams: ['country'],
		testInput: { country: 'NG' },
	},
	{
		key: 'getBulkTokenizedCharge',
		group: 'bulkTokenizedCharges',
		name: 'get',
		method: 'GET',
		path: '/bulk-tokenized-charges/{bulk_id}',
		description: 'Get status of bulk tokenized charges.',
		riskLevel: 'read' as const,
		pathParams: ['bulk_id'],
		testInput: { bulk_id: 1001 },
	},
	{
		key: 'getBulkVirtualAccount',
		group: 'bulkVirtualAccounts',
		name: 'get',
		method: 'GET',
		path: '/bulk-virtual-account-numbers/{batch_id}',
		description: 'Get details for a bulk virtual account batch.',
		riskLevel: 'read' as const,
		pathParams: ['batch_id'],
		testInput: { batch_id: 'batch-ref-1' },
	},
	{
		key: 'getMultipleRefundTransactions',
		group: 'refunds',
		name: 'list',
		method: 'GET',
		path: '/refunds',
		description: 'List refund transactions with filters.',
		riskLevel: 'read' as const,
		queryParams: ['from', 'to', 'status', 'currency', 'flw_ref', 'id'],
		testInput: { status: 'successful' },
	},
	{
		key: 'getPaymentPlan',
		group: 'paymentPlans',
		name: 'get',
		method: 'GET',
		path: '/payment-plans/{id}',
		description: 'Get a payment plan by ID.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 3874 },
	},
	{
		key: 'getPaymentPlans',
		group: 'paymentPlans',
		name: 'list',
		method: 'GET',
		path: '/payment-plans',
		description: 'List payment plans.',
		riskLevel: 'read' as const,
		queryParams: [
			'from',
			'to',
			'page',
			'amount',
			'currency',
			'interval',
			'status',
		],
		testInput: { page: 1 },
	},
	{
		key: 'getRefund',
		group: 'refunds',
		name: 'get',
		method: 'GET',
		path: '/refunds/{id}',
		description: 'Get refund details by ID.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 2032 },
	},
	{
		key: 'getTransaction',
		group: 'transactions',
		name: 'get',
		method: 'GET',
		path: '/transactions/{id}/verify',
		description: 'Get a transaction by ID.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 1190701 },
	},
	{
		key: 'getTransactionFee',
		group: 'transactions',
		name: 'getFee',
		method: 'GET',
		path: '/transactions/fee',
		description: 'Get transaction fee estimate.',
		riskLevel: 'read' as const,
		queryParams: ['amount', 'currency', 'payment_type', 'card_first6digits'],
		testInput: { amount: 2000, currency: 'NGN' },
	},
	{
		key: 'getTransferFee',
		group: 'transfers',
		name: 'getFee',
		method: 'GET',
		path: '/transfers/fee',
		description: 'Get transfer fee estimate.',
		riskLevel: 'read' as const,
		queryParams: ['amount', 'currency', 'type'],
		testInput: { amount: 5000, currency: 'NGN' },
	},
	{
		key: 'getTransferRates',
		group: 'transfers',
		name: 'getRates',
		method: 'GET',
		path: '/transfers/rates',
		description: 'Get transfer exchange rates.',
		riskLevel: 'read' as const,
		queryParams: ['amount', 'destination_currency', 'source_currency'],
		testInput: {
			amount: 100,
			destination_currency: 'KES',
			source_currency: 'NGN',
		},
	},
	{
		key: 'getVirtualAccountNumber',
		group: 'virtualAccounts',
		name: 'get',
		method: 'GET',
		path: '/virtual-account-numbers/{order_ref}',
		description: 'Get virtual account number details by order reference.',
		riskLevel: 'read' as const,
		pathParams: ['order_ref'],
		testInput: { order_ref: 'tx-ref-1' },
	},
	{
		key: 'getWalletStatement',
		group: 'wallets',
		name: 'getStatement',
		method: 'GET',
		path: '/wallet/statement',
		description: 'Get wallet statement.',
		riskLevel: 'read' as const,
		queryParams: ['from', 'to', 'currency', 'type', 'page'],
		testInput: { from: '2020-01-01', to: '2020-01-31', currency: 'NGN' },
	},
	{
		key: 'initiateBvnVerification',
		group: 'verification',
		name: 'initiateBvn',
		method: 'POST',
		path: '/bvn/verifications',
		description: 'Initiate BVN verification.',
		riskLevel: 'write' as const,
		testInput: {
			bvn: '12345678901',
			firstname: 'John',
			lastname: 'Doe',
			redirect_url: 'https://example.com/callback',
		},
	},
	{
		key: 'initiateMobileMoneyTanzania',
		group: 'charges',
		name: 'initiateMobileMoneyTanzania',
		method: 'POST',
		path: '/charges',
		description: 'Initiate mobile money charge in Tanzania.',
		riskLevel: 'write' as const,
		queryParams: ['type'],
		testInput: {
			type: 'mobile_money_tanzania',
			tx_ref: 'tx-ref-1',
			amount: 1000,
			currency: 'TZS',
			email: 'user@example.com',
			phone_number: '255700000001',
		},
	},
	{
		key: 'listAllBeneficiaries',
		group: 'beneficiaries',
		name: 'list',
		method: 'GET',
		path: '/beneficiaries',
		description: 'List all beneficiaries.',
		riskLevel: 'read' as const,
		queryParams: ['page'],
		testInput: { page: 1 },
	},
	{
		key: 'listSubaccounts',
		group: 'subaccounts',
		name: 'list',
		method: 'GET',
		path: '/subaccounts',
		description: 'List all subaccounts.',
		riskLevel: 'read' as const,
		queryParams: ['account_bank', 'account_number', 'bank_name', 'page'],
		testInput: { page: 1 },
	},
	{
		key: 'listBillerProducts',
		group: 'bills',
		name: 'listProducts',
		method: 'GET',
		path: '/billers/{biller_code}/items',
		description: 'List biller products.',
		riskLevel: 'read' as const,
		pathParams: ['biller_code'],
		testInput: { biller_code: 'BIL103' },
	},
	{
		key: 'listBillers',
		group: 'bills',
		name: 'listBillers',
		method: 'GET',
		path: '/bills/{category}/billers',
		description: 'List billers in a category.',
		riskLevel: 'read' as const,
		pathParams: ['category'],
		queryParams: ['country'],
		testInput: { category: 'AIRTIME', country: 'NG' },
	},
	{
		key: 'listChargebacks',
		group: 'chargebacks',
		name: 'list',
		method: 'GET',
		path: '/chargebacks',
		description: 'List chargebacks.',
		riskLevel: 'read' as const,
		queryParams: ['page', 'status', 'from', 'to', 'flw_ref'],
		testInput: { page: 1 },
	},
	{
		key: 'listPayoutSubaccountRefunds',
		group: 'payoutSubaccounts',
		name: 'listRefunds',
		method: 'GET',
		path: '/payout-subaccounts/refunds',
		description: 'List payout subaccount refunds.',
		riskLevel: 'read' as const,
		queryParams: ['status', 'from', 'to', 'reference'],
		testInput: { status: 'successful' },
	},
	{
		key: 'listPayoutSubaccounts',
		group: 'payoutSubaccounts',
		name: 'list',
		method: 'GET',
		path: '/payout-subaccounts',
		description: 'List payout subaccounts.',
		riskLevel: 'read' as const,
		queryParams: ['limit', 'next_cursor'],
		testInput: { limit: 20 },
	},
	{
		key: 'listRecurringBills',
		group: 'bills',
		name: 'listRecurring',
		method: 'GET',
		path: '/bills/history',
		description: 'List recurring bill payments.',
		riskLevel: 'read' as const,
		queryParams: [
			'status',
			'from',
			'to',
			'page',
			'limit',
			'reference',
			'category',
			'country',
		],
		testInput: { page: 1, limit: 20 },
	},
	{
		key: 'listTransfers',
		group: 'transfers',
		name: 'list',
		method: 'GET',
		path: '/transfers',
		description: 'List transfers.',
		riskLevel: 'read' as const,
		queryParams: ['reference', 'page', 'status', 'from', 'to'],
		testInput: { page: 1 },
	},
	{
		key: 'listSettlements',
		group: 'settlements',
		name: 'list',
		method: 'GET',
		path: '/settlements',
		description: 'List settlements.',
		riskLevel: 'read' as const,
		queryParams: ['page', 'from', 'to', 'subaccount_id', 'disburse_ref'],
		testInput: { page: 1 },
	},
	{
		key: 'resolveBankAccount',
		group: 'banks',
		name: 'resolveAccount',
		method: 'POST',
		path: '/accounts/resolve',
		description: 'Resolve bank account details.',
		riskLevel: 'read' as const,
		testInput: { account_number: '0690000040', account_bank: '044' },
	},
	{
		key: 'resolveCardBin',
		group: 'cards',
		name: 'resolveBin',
		method: 'GET',
		path: '/card-bins/{bin}',
		description: 'Resolve card BIN details.',
		riskLevel: 'read' as const,
		pathParams: ['bin'],
		testInput: { bin: '553188' },
	},
	{
		key: 'getAllTransactions',
		group: 'transactions',
		name: 'list',
		method: 'GET',
		path: '/transactions',
		description: 'Retrieve all transactions.',
		riskLevel: 'read' as const,
		queryParams: [
			'from',
			'to',
			'page',
			'status',
			'tx_ref',
			'customer_email',
			'currency',
		],
		testInput: { from: '2020-01-01', to: '2020-01-31', page: 1 },
	},
	{
		key: 'updatePaymentPlan',
		group: 'paymentPlans',
		name: 'update',
		method: 'PUT',
		path: '/payment-plans/{id}',
		description: 'Update a payment plan.',
		riskLevel: 'write' as const,
		pathParams: ['id'],
		testInput: { id: 3874, name: 'Updated', status: 'active' },
	},
	{
		key: 'updateSubaccount',
		group: 'subaccounts',
		name: 'update',
		method: 'PUT',
		path: '/subaccounts/{id}',
		description: 'Update a subaccount.',
		riskLevel: 'write' as const,
		pathParams: ['id'],
		testInput: { id: 3319, business_name: 'Updated', split_value: 0.15 },
	},
	{
		key: 'validateBillItem',
		group: 'bills',
		name: 'validateItem',
		method: 'GET',
		path: '/bill-items/{item_code}/validate',
		description: 'Validate a bill item before payment.',
		riskLevel: 'read' as const,
		pathParams: ['item_code'],
		queryParams: ['customer'],
		testInput: { item_code: 'AT099', customer: '08012345678' },
	},
	{
		key: 'verifyTransactionByReference',
		group: 'transactions',
		name: 'verifyByReference',
		method: 'GET',
		path: '/transactions/verify_by_reference',
		description: 'Verify a transaction by tx_ref.',
		riskLevel: 'read' as const,
		queryParams: ['tx_ref'],
		testInput: { tx_ref: 'tx-ref-1' },
	},
	{
		key: 'viewTransactionTimeline',
		group: 'transactions',
		name: 'viewTimeline',
		method: 'GET',
		path: '/transactions/{id}/events',
		description: 'View transaction timeline.',
		riskLevel: 'read' as const,
		pathParams: ['id'],
		testInput: { id: 1190701 },
	},
] as const satisfies readonly FlutterwaveRoute[];

export type FlutterwaveRoutes = typeof flutterwaveRoutes;
