import { logEventFromContext } from 'corsair/core';
import type { DopplerEndpoints } from '../index';
import { auditPayload } from './logging';
import { compact, dopplerShareCall } from './shared';
import type { DopplerEndpointOutputs } from './types';

/**
 * Not mirrored, never logged. A plain-flow response's `password` is the
 * link's decryption key, in plaintext, generated by Doppler and handed back
 * exactly once - confirmed live. `auditPayload` below never receives it,
 * and the field never reaches `logEventFromContext`'s payload.
 */

/**
 * Creates a Doppler Share link from a plaintext secret. Doppler's own
 * description is explicit that the send half is not end-to-end encrypted -
 * the secret is transmitted in plain text to create the link, even though
 * Doppler does not store it in plain text at rest.
 */
export const createPlain: DopplerEndpoints['shareCreatePlain'] = async (
	ctx,
	input,
) => {
	const result = await dopplerShareCall<
		DopplerEndpointOutputs['shareCreatePlain']
	>(ctx, 'secrets/plain', {
		method: 'POST',
		body: compact({
			secret: input.secret,
			expire_views: input.expireViews,
			expire_days: input.expireDays,
		}),
	});

	await logEventFromContext(
		ctx,
		'doppler.share.createPlain',
		auditPayload(input, []),
		'completed',
	);
	return result;
};

/**
 * Creates a Doppler Share link from an already-encrypted payload. This
 * plugin does not perform the encryption itself - the caller supplies
 * ciphertext produced with their own AES-256-GCM key, derived via
 * PBKDF2-SHA256 at 1,000,000 salt rounds from a random passphrase, per
 * Doppler's own spec. That keeps the passphrase - the actual decryption
 * key - off this plugin and off Doppler's servers entirely; genuinely
 * zero-knowledge, unlike the plain flow above.
 */
export const createEncrypted: DopplerEndpoints['shareCreateEncrypted'] = async (
	ctx,
	input,
) => {
	const result = await dopplerShareCall<
		DopplerEndpointOutputs['shareCreateEncrypted']
	>(ctx, 'secrets/encrypted', {
		method: 'POST',
		body: compact({
			encrypted_secret: input.encryptedSecret,
			hashed_password: input.hashedPassword,
			encryption_kdf: input.encryptionKdf ?? 'pbkdf2',
			encryption_salt_rounds: input.encryptionSaltRounds ?? 1_000_000,
			expire_views: input.expireViews,
			expire_days: input.expireDays,
		}),
	});

	await logEventFromContext(
		ctx,
		'doppler.share.createEncrypted',
		auditPayload(input, []),
		'completed',
	);
	return result;
};
