import {
	BaseLinkerCategory,
	BaseLinkerConnectIntegration,
	BaseLinkerCourier,
	BaseLinkerExternalStorage,
	BaseLinkerInventory,
	BaseLinkerInventoryExtraField,
	BaseLinkerManufacturer,
	BaseLinkerOrderStatus,
	BaseLinkerPayer,
	BaseLinkerPriceGroup,
	BaseLinkerReturnProductStatus,
	BaseLinkerReturnReason,
	BaseLinkerReturnStatus,
	BaseLinkerSupplier,
	BaseLinkerTag,
	BaseLinkerWarehouse,
} from './database';

export const BaseLinkerSchema = {
	version: '1.0.0',
	entities: {
		inventories: BaseLinkerInventory,
		categories: BaseLinkerCategory,
		manufacturers: BaseLinkerManufacturer,
		priceGroups: BaseLinkerPriceGroup,
		warehouses: BaseLinkerWarehouse,
		suppliers: BaseLinkerSupplier,
		payers: BaseLinkerPayer,
		tags: BaseLinkerTag,
		inventoryExtraFields: BaseLinkerInventoryExtraField,
		orderStatuses: BaseLinkerOrderStatus,
		returnStatuses: BaseLinkerReturnStatus,
		returnReasons: BaseLinkerReturnReason,
		returnProductStatuses: BaseLinkerReturnProductStatus,
		couriers: BaseLinkerCourier,
		externalStorages: BaseLinkerExternalStorage,
		connectIntegrations: BaseLinkerConnectIntegration,
	},
} as const;
