import { z } from 'zod';

/**
 * Official Cody AI REST API v1 Bot Schema
 * Reference: https://getcody.ai/api/v1/bots
 */
export const CodyBot = z.object({
	id: z.string().describe('Unique identifier of the bot'),
	name: z.string().describe('Name of the bot'),
	description: z
		.string()
		.optional()
		.describe('Description of the bot and its intended use case'),
	model: z
		.string()
		.optional()
		.describe('LLM model used for all messages generated by this bot'),
	created_at: z
		.number()
		.optional()
		.describe('Unix timestamp in seconds when the bot was created'),
});

/**
 * Official Cody AI REST API v1 Conversation Schema
 * Reference: https://getcody.ai/api/v1/conversations
 */
export const CodyConversation = z.object({
	id: z.string().describe('Unique identifier of the conversation'),
	name: z.string().describe('Name/title of the conversation thread'),
	bot_id: z
		.string()
		.describe('Identifier of the bot associated with this conversation'),
	created_at: z
		.number()
		.optional()
		.describe('Unix timestamp in seconds when the conversation was created'),
});

/**
 * Official Cody AI REST API v1 Document Schema
 * Reference: https://getcody.ai/api/v1/documents
 */
export const CodyDocument = z.object({
	id: z.string().describe('Unique identifier of the document'),
	name: z.string().describe('Name of the document'),
	status: z
		.string()
		.optional()
		.describe('Learning status of the document (syncing, synced, sync_failed)'),
	content_url: z
		.string()
		.optional()
		.describe('URL to download document content HTML'),
	folder_id: z
		.string()
		.nullable()
		.optional()
		.describe('Identifier of the folder containing this document'),
	created_at: z
		.number()
		.optional()
		.describe('Unix timestamp in seconds when the document was created'),
});

/**
 * Official Cody AI REST API v1 Folder Schema
 * Reference: https://getcody.ai/api/v1/folders
 */
export const CodyFolder = z.object({
	id: z.string().describe('Unique identifier of the folder'),
	name: z.string().describe('Name of the folder'),
	created_at: z
		.number()
		.optional()
		.describe('Unix timestamp in seconds when the folder was created'),
});

/**
 * Official Cody AI REST API v1 Message Schema
 * Reference: https://getcody.ai/api/v1/messages
 */
export const CodyMessage = z.object({
	id: z.string().describe('Unique identifier of the message'),
	content: z.string().describe('Text content of the message'),
	conversation_id: z
		.string()
		.describe('Identifier of the conversation thread containing this message'),
	machine: z
		.boolean()
		.optional()
		.describe('True if message was generated by the AI bot'),
	failed_responding: z
		.boolean()
		.optional()
		.describe('True if response generation failed'),
	flagged: z
		.boolean()
		.optional()
		.describe('True if message violates OpenAI usage policies'),
	created_at: z
		.number()
		.optional()
		.describe('Unix timestamp in seconds when the message was sent'),
});

/**
 * Official Cody AI REST API v1 Usage Metric Schema
 * Reference: https://getcody.ai/api/v1/messages
 */
export const CodyUsage = z.object({
	tokens: z
		.number()
		.optional()
		.describe('Token usage calculated using a tiered step model'),
	credits: z.number().optional().describe('Cost of the message in credits'),
});

export type CodyBot = z.infer<typeof CodyBot>;
export type CodyConversation = z.infer<typeof CodyConversation>;
export type CodyDocument = z.infer<typeof CodyDocument>;
export type CodyFolder = z.infer<typeof CodyFolder>;
export type CodyMessage = z.infer<typeof CodyMessage>;
export type CodyUsage = z.infer<typeof CodyUsage>;
