import type { EndpointRiskLevel } from 'corsair/core';

export type ApifyOperationMethod =
	| 'GET'
	| 'POST'
	| 'PUT'
	| 'DELETE'
	| 'PATCH'
	| 'HEAD';

export type ApifyOperationDefinition = {
	method: ApifyOperationMethod;
	path: string;
	pathParams: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
	description: string;
	slug: string;
};

export type ApifyOperationTree = {
	readonly [key: string]: ApifyOperationDefinition | ApifyOperationTree;
};

export const apifyOperations = {
	actorBuilds: {
		abortActorBuild: {
			method: 'POST',
			path: '/v2/actor-builds/{buildId}/abort',
			pathParams: ['buildId'],
			riskLevel: 'write',
			description:
				'Tool to abort an Actor build that is starting or running. Use when you need to cancel a build in progress. Builds in terminal states (FINISHED, FAILED, ABORTING, TIMED-OUT) are not affected.',
			slug: 'APIFY_ACTOR_BUILD_ABORT_POST',
		},
		deleteActorBuild: {
			method: 'DELETE',
			path: '/v2/actor-builds/{buildId}',
			pathParams: ['buildId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete an Actor build permanently. Use when you need to remove a specific build by its ID. The default build for an Actor cannot be deleted. Only users with build permissions can delete builds.',
			slug: 'APIFY_ACTOR_BUILD_DELETE',
		},
		getActorBuild: {
			method: 'GET',
			path: '/v2/actor-builds/{buildId}',
			pathParams: ['buildId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description:
				'Tool to get detailed information about a specific Actor build. Use when you need to retrieve complete build details by build ID. Optionally wait for the build to finish using the waitForFinish parameter to avoid polling.',
			slug: 'APIFY_ACTOR_BUILD_GET',
		},
		getActorBuildLog: {
			method: 'GET',
			path: '/v2/actor-builds/{buildId}/log',
			pathParams: ['buildId'],
			queryParams: ['stream', 'download'],
			riskLevel: 'read',
			description:
				'Tool to retrieve the log file for a specific Actor build. Use when you need to inspect logs generated during an Actor build process. Only the trailing 5 million characters of the log are stored.',
			slug: 'APIFY_ACTOR_BUILD_LOG_GET',
		},
		getUserBuildsList: {
			method: 'GET',
			path: '/v2/actor-builds',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get a paginated list of all builds for a user. Use when you need to retrieve build history across all actors. Supports pagination up to 1000 records.',
			slug: 'APIFY_ACTOR_BUILDS_GET',
		},
	},
	actorRuns: {
		abortActorRun: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/abort',
			pathParams: ['runId'],
			queryParams: ['gracefully'],
			riskLevel: 'write',
			description:
				'Tool to abort a running or starting Actor run. Use when you need to stop an Actor run that is currently in STARTING or RUNNING status. For runs with status FINISHED, FAILED, ABORTING, and TIMED-OUT this call does nothing.',
			slug: 'APIFY_ACTOR_RUN_ABORT_POST',
		},
		deleteActorRun: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}',
			pathParams: ['runId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a finished Actor run. Use when you need to permanently remove a completed run. Only finished runs can be deleted by the initiating user or organization.',
			slug: 'APIFY_ACTOR_RUN_DELETE',
		},
		getActorRun: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}',
			pathParams: ['runId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description:
				'Tool to get details about a specific Actor run. Use when you need to retrieve comprehensive information about a run including its execution status, resource usage, storage IDs, and metadata.',
			slug: 'APIFY_ACTOR_RUN_GET',
		},
		getRunDatasetItems: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/dataset/items',
			pathParams: ['runId'],
			queryParams: [
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description:
				'Tool to get dataset items from a specific Actor run. Use when you need to retrieve the output data from a completed or running Actor run.',
			slug: 'APIFY_GET_RUN_DATASET_ITEMS',
		},
		listUserActorRuns: {
			method: 'GET',
			path: '/v2/actor-runs',
			pathParams: [],
			queryParams: [
				'offset',
				'limit',
				'desc',
				'status',
				'startedAfter',
				'startedBefore',
			],
			riskLevel: 'read',
			description:
				'Tool to get a paginated list of all Actor runs for the authenticated user. Use when you need to browse all runs across all actors, optionally filtered by status or date range.',
			slug: 'APIFY_LIST_USER_RUNS',
		},
		resurrectRun: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/resurrect',
			pathParams: ['runId'],
			queryParams: [
				'build',
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
			],
			riskLevel: 'write',
			description:
				'Tool to resurrect a finished Actor run. Use when you need to restart a completed or failed run. Deprecated endpoint; may be removed in future.',
			slug: 'APIFY_RESURRECT_RUN',
		},
		updateActorRunStatusMessage: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}',
			pathParams: ['runId'],
			riskLevel: 'write',
			description:
				'Tool to update the status message of an Actor run. Use when you need to set progress information or status updates that will be displayed in the Apify Console UI during Actor execution.',
			slug: 'APIFY_ACTOR_RUN_PUT',
		},
	},
	actorTasks: {
		createActorTask: {
			method: 'POST',
			path: '/v2/actor-tasks',
			pathParams: [],
			riskLevel: 'write',
			description:
				'Tool to create a new Actor task with specified settings. Use when you need to configure or schedule recurring Actor runs programmatically.',
			slug: 'APIFY_CREATE_TASK',
		},
		deleteActorTask: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}',
			pathParams: ['actorTaskId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete an Actor task permanently. Use when you need to remove a task by its ID or username~taskName. Confirm before calling.',
			slug: 'APIFY_ACTOR_TASK_DELETE',
		},
		getActorTask: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}',
			pathParams: ['actorTaskId'],
			riskLevel: 'read',
			description:
				'Tool to get complete details about an Actor task. Use when you need to retrieve task configuration, input settings, or metadata by task ID or username~task-name.',
			slug: 'APIFY_ACTOR_TASK_GET',
		},
		getTaskInput: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/input',
			pathParams: ['actorTaskId'],
			riskLevel: 'read',
			description:
				'Tool to retrieve the input configuration of a specific task. Use when you need to inspect stored task input before execution or debugging.',
			slug: 'APIFY_GET_TASK_INPUT',
		},
		getTaskLastRunDatasetItems: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset/items',
			pathParams: ['actorTaskId'],
			queryParams: [
				'status',
				'origin',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description:
				"Tool to get dataset items from the last run of an Actor task. Use when you need to retrieve data from the most recent task execution. Filter by status (e.g., 'SUCCEEDED') to get items from the last successful run only.",
			slug: 'APIFY_GET_TASK_LAST_RUN_DATASET_ITEMS',
		},
		getLastActorTaskRun: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'waitForFinish'],
			riskLevel: 'read',
			description:
				"Tool to get the most recent run of a specific Actor task. Use when you need to retrieve the last execution details. You can filter by status to get only successful runs using status='SUCCEEDED'.",
			slug: 'APIFY_ACTOR_TASK_RUNS_LAST_GET',
		},
		getListOfTaskRuns: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs',
			pathParams: ['actorTaskId'],
			queryParams: ['offset', 'limit', 'desc', 'status'],
			riskLevel: 'read',
			description:
				'Tool to get a list of runs for a specific Actor task. Use when you need to paginate through task runs and optionally filter by status.',
			slug: 'APIFY_GET_LIST_OF_TASK_RUNS',
		},
		getListOfTaskWebhooks: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/webhooks',
			pathParams: ['actorTaskId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get a list of webhooks for a specific Actor task. Use when you need to review or paginate webhooks after creating or updating a task.',
			slug: 'APIFY_GET_LIST_OF_TASK_WEBHOOKS',
		},
		getListOfTasks: {
			method: 'GET',
			path: '/v2/actor-tasks',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to fetch a paginated list of tasks belonging to the authenticated user. Use when you need to browse or sort tasks created by the user.',
			slug: 'APIFY_GET_LIST_OF_TASKS',
		},
		runTaskAsynchronously: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'waitForFinish',
				'webhooks',
			],
			riskLevel: 'write',
			description:
				'Tool to run a specific Actor task asynchronously. Use when you need to trigger a task run without waiting for completion and immediately retrieve its run details.',
			slug: 'APIFY_RUN_TASK',
		},
		runTaskSyncGetDatasetItems: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description:
				'Tool to run an actor task synchronously and retrieve its dataset items. Use when immediate access to task run results is needed. The run must finish within 300 seconds otherwise the request times out. For large datasets exceeding the timeout, use `limit`/`offset` pagination to retrieve results in smaller batches or switch to an async run pattern with a separate dataset retrieval call.',
			slug: 'APIFY_ACTOR_TASK_RUN_SYNC_GET_DATASET_ITEMS_GET',
		},
		runTaskSyncGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'build',
				'outputRecordKey',
				'webhooks',
			],
			riskLevel: 'write',
			description:
				'Tool to run a specific task synchronously and return its output. Use when immediate task results are needed with pre-configured settings. The run must finish within 300 seconds otherwise the HTTP request fails with a timeout error.',
			slug: 'APIFY_ACTOR_TASK_RUN_SYNC_GET',
		},
		runTaskSyncPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'outputRecordKey',
				'webhooks',
			],
			riskLevel: 'write',
			description:
				'Tool to run an Actor task synchronously with input override and return its output. Use when immediate task results are needed with custom input parameters. The run must finish within 300 seconds otherwise the HTTP request fails with a timeout error (though the run continues server-side).',
			slug: 'APIFY_ACTOR_TASK_RUN_SYNC_POST',
		},
		runTaskSyncWithInputOverrideGetDatasetItems: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description:
				'Tool to run an actor task synchronously with input overrides and retrieve its dataset items. Use when you need to override task input configuration and get immediate results. The run must finish within 300 seconds otherwise the request times out.',
			slug: 'APIFY_ACTOR_TASK_RUN_SYNC_GET_DATASET_ITEMS_POST',
		},
		updateActorTask: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}',
			pathParams: ['actorTaskId'],
			riskLevel: 'write',
			description:
				'Tool to update Actor task settings using JSON payload. Only specified properties are updated; others remain unchanged. Use when you need to modify task configuration, input, or execution options.',
			slug: 'APIFY_ACTOR_TASK_PUT',
		},
		updateTaskInput: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/input',
			pathParams: ['actorTaskId'],
			riskLevel: 'write',
			description:
				'Tool to update the input configuration of a specific Actor task. Use when you need to modify a scheduled task input before execution.',
			slug: 'APIFY_UPDATE_TASK_INPUT',
		},
	},
	// REST actor CRUD. MCP already owns the `actors` namespace.
	acts: {
		buildActor: {
			method: 'POST',
			path: '/v2/actors/{actorId}/builds',
			pathParams: ['actorId'],
			queryParams: [
				'version',
				'useCache',
				'betaPackages',
				'tag',
				'waitForFinish',
			],
			riskLevel: 'write',
			description:
				"Tool to build an Actor with specified configuration. Use when you need to create a new build of an Actor with a specific version. The build process compiles the Actor's source code into a Docker image.",
			slug: 'APIFY_ACT_BUILDS_POST',
		},
		createActor: {
			method: 'POST',
			path: '/v2/actors',
			pathParams: [],
			riskLevel: 'write',
			description:
				'Tool to create a new Actor with specified configuration. Use when you need to initialize a fresh Actor programmatically before publishing or running it.',
			slug: 'APIFY_CREATE_ACTOR',
		},
		createActorVersion: {
			method: 'POST',
			path: '/v2/actors/{actorId}/versions',
			pathParams: ['actorId'],
			riskLevel: 'write',
			description:
				'Tool to create a new version of an Actor. Use when you need to add a new version with specific source code location and configuration. Requires versionNumber and sourceType parameters, plus conditional parameters based on the sourceType.',
			slug: 'APIFY_ACT_VERSIONS_POST',
		},
		createActorVersionEnvironmentVariable: {
			method: 'POST',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'write',
			description:
				'Tool to create an environment variable for a specific Actor version. Use when adding new environment variables to Actor versions. Requires name and value parameters.',
			slug: 'APIFY_ACT_VERSION_ENV_VARS_POST',
		},
		deleteActor: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}',
			pathParams: ['actorId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete an Actor permanently. Use when you need to remove an Actor by its ID or username~actorName. Confirm before calling.',
			slug: 'APIFY_DELETE_ACTOR',
		},
		deleteActorVersion: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				"Tool to delete a specific version of an Actor's source code. Use when you need to remove an Actor version by actor ID and version number. Confirm before calling.",
			slug: 'APIFY_ACT_VERSION_DELETE',
		},
		deleteActorVersionEnvironmentVariable: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete an environment variable from a specific Actor version. Use when removing environment variables from Actor versions.',
			slug: 'APIFY_ACT_VERSION_ENV_VAR_DELETE',
		},
		getActorDetails: {
			method: 'GET',
			path: '/v2/actors/{actorId}',
			pathParams: ['actorId'],
			riskLevel: 'read',
			description:
				'Tool to get details of a specific Actor. Use when you need actor metadata by ID or username/actorName. Response includes `isDeprecated` and `notice` fields indicating deprecation status, and `pricingInfos` for per-unit cost details — review both before scheduling runs.',
			slug: 'APIFY_GET_ACTOR',
		},
		getActorLastRunDatasetItems: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/dataset/items',
			pathParams: ['actorId'],
			queryParams: [
				'status',
				'origin',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description:
				"Tool to get dataset items from the last run of an Actor. Use when you need to retrieve output data from the most recent Actor execution, optionally filtered by run status (e.g., status='SUCCEEDED' to get items only from the last successful run).",
			slug: 'APIFY_GET_ACTOR_LAST_RUN_DATASET_ITEMS',
		},
		getActorVersionEnvironmentVariable: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'read',
			description:
				'Tool to get environment variable details for a specific Actor version. Use when retrieving environment variable information from an Actor version. Returns name, value (if not secret), and secret status.',
			slug: 'APIFY_ACT_VERSION_ENV_VAR_GET',
		},
		getActorVersion: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'read',
			description:
				'Tool to get details about a specific version of an Actor. Use when you need version metadata including source type, build tag, and configuration details.',
			slug: 'APIFY_ACT_VERSION_GET',
		},
		getDefaultBuild: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds/default',
			pathParams: ['actorId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description:
				'Tool to get the default build for an Actor. Use after specifying the Actor ID; optionally wait for the build to finish before returning.',
			slug: 'APIFY_GET_DEFAULT_BUILD',
		},
		getOpenapiDefinition: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds/{buildId}/openapi.json',
			pathParams: ['actorId', 'buildId'],
			riskLevel: 'read',
			description:
				'Tool to get the OpenAPI definition for a specific Actor build. Use when you need the API schema for code generation or analysis.',
			slug: 'APIFY_GET_OPEN_API_DEFINITION',
		},
		getLastActorRun: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'waitForFinish'],
			riskLevel: 'read',
			description:
				"Tool to get the most recent run of a specific Actor. Use when you need to retrieve the last execution details of an Actor and optionally filter by status (e.g., status='SUCCEEDED' to get only the last successful run).",
			slug: 'APIFY_ACT_RUNS_LAST_GET',
		},
		getListOfActorVersionEnvironmentVariables: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'read',
			description:
				'Tool to get the list of environment variables for a specific Actor version. Use when you need to retrieve environment variable configurations for an Actor version.',
			slug: 'APIFY_ACT_VERSION_ENV_VARS_GET',
		},
		getListOfActorVersions: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions',
			pathParams: ['actorId'],
			riskLevel: 'read',
			description:
				'Tool to get the list of versions of a specific Actor. Use when you need to retrieve version metadata including source type, version number, and configuration details.',
			slug: 'APIFY_ACT_VERSIONS_GET',
		},
		getListOfActorWebhooks: {
			method: 'GET',
			path: '/v2/actors/{actorId}/webhooks',
			pathParams: ['actorId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get a list of webhooks for a specific Actor. Use when you need to review or manage webhooks configured for an Actor.',
			slug: 'APIFY_ACT_WEBHOOKS_GET',
		},
		getListOfActors: {
			method: 'GET',
			path: '/v2/actors',
			pathParams: [],
			queryParams: ['my', 'offset', 'limit', 'desc', 'sortBy'],
			riskLevel: 'read',
			description:
				'Tool to get the list of all Actors that the user created or used. Use when you need to enumerate or browse Actors. Add my=1 to get only user-created Actors.',
			slug: 'APIFY_ACTS_GET',
		},
		getListOfBuilds: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds',
			pathParams: ['actorId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get a list of builds for a specific Actor. Use when you need paginated access to an Actor’s build (version) history.',
			slug: 'APIFY_GET_LIST_OF_BUILDS',
		},
		getListOfRuns: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs',
			pathParams: ['actorId'],
			queryParams: [
				'offset',
				'limit',
				'desc',
				'status',
				'startedAfter',
				'startedBefore',
			],
			riskLevel: 'read',
			description:
				'Tool to get a list of runs for a specific Actor. Use when you need to paginate through runs and optionally filter by status before processing run data.',
			slug: 'APIFY_GET_LIST_OF_RUNS',
		},
		runActorAsynchronously: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs',
			pathParams: ['actorId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'waitForFinish',
				'webhooks',
				'forcePermissionLevel',
			],
			riskLevel: 'write',
			description:
				'Tool to run a specific Actor asynchronously. Use when you need to trigger an Actor run without waiting for completion and retrieve its run details immediately.',
			slug: 'APIFY_RUN_ACTOR',
		},
		runActorSync: {
			method: 'POST',
			path: '/v2/actors/{actorId}/run-sync',
			pathParams: ['actorId'],
			queryParams: [
				'outputRecordKey',
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
			],
			riskLevel: 'write',
			description:
				'Tool to run a specific Actor synchronously with input and return its output record. Use when immediate Actor results are needed; runs may timeout after 300 seconds. To avoid timeouts, scope inputs to specific URLs rather than broad crawls and request only necessary fields (e.g., text or markdown).',
			slug: 'APIFY_RUN_ACTOR_SYNC',
		},
		runActorSyncGetDatasetItems: {
			method: 'GET',
			path: '/v2/actors/{actorId}/run-sync-get-dataset-items',
			pathParams: ['actorId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description:
				"Tool to run Actor synchronously and get dataset items. Supports both actors that require input and those that don't. Use when immediate access to Actor results is needed. The run must finish within 300 seconds otherwise the request times out.",
			slug: 'APIFY_ACT_RUN_SYNC_GET_DATASET_ITEMS_GET',
		},
		runActorSyncGetDatasetItemsItems: {
			method: 'POST',
			path: '/v2/actors/{actorId}/run-sync-get-dataset-items',
			pathParams: ['actorId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description:
				'Tool to run an Actor synchronously and retrieve its dataset items. Use when immediate access to run results is needed.',
			slug: 'APIFY_RUN_ACTOR_SYNC_GET_DATASET_ITEMS',
		},
		runActorSyncWithoutInputGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/run-sync',
			pathParams: ['actorId'],
			queryParams: [
				'outputRecordKey',
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
			],
			riskLevel: 'write',
			description:
				'Tool to run a specific Actor synchronously without input and return its output. Use when immediate Actor results are needed without providing input data; the run must finish within 300 seconds otherwise the HTTP request fails with a timeout error.',
			slug: 'APIFY_ACT_RUN_SYNC_GET',
		},
		updateActor: {
			method: 'PUT',
			path: '/v2/actors/{actorId}',
			pathParams: ['actorId'],
			riskLevel: 'write',
			description:
				'Tool to update Actor settings using JSON payload. Only specified fields will be updated. Use when you need to modify Actor configuration, make an Actor public, or update version settings.',
			slug: 'APIFY_ACT_PUT',
		},
		updateActorVersion: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'write',
			description:
				"Tool to update an Actor version's configuration and source code. Use when modifying version properties such as buildTag, sourceType, or environment variables. Only specified properties will be updated.",
			slug: 'APIFY_ACT_VERSION_PUT',
		},
		updateActorVersionEnvironmentVariable: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'write',
			description:
				'Tool to update environment variable for a specific Actor version using JSON payload. Only specified fields will be updated. Use when modifying existing environment variables in Actor versions.',
			slug: 'APIFY_ACT_VERSION_ENV_VAR_PUT',
		},
	},
	datasets: {
		createDataset: {
			method: 'POST',
			path: '/v2/datasets',
			pathParams: [],
			queryParams: ['name'],
			riskLevel: 'write',
			description:
				'Tool to create a new dataset. Use when you need to initialize or retrieve a dataset by name.',
			slug: 'APIFY_CREATE_DATASET',
		},
		deleteDataset: {
			method: 'DELETE',
			path: '/v2/datasets/{datasetId}',
			pathParams: ['datasetId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a dataset permanently. Use when you need to remove a dataset by its ID or username~dataset-name. Confirm before calling.',
			slug: 'APIFY_DATASET_DELETE',
		},
		getDataset: {
			method: 'GET',
			path: '/v2/datasets/{datasetId}',
			pathParams: ['datasetId'],
			riskLevel: 'read',
			description:
				"Tool to retrieve dataset metadata by dataset ID. Use when you need information about a dataset's structure, item counts, or access URLs. This does not return dataset items themselves.",
			slug: 'APIFY_DATASET_GET',
		},
		getDatasetStatistics: {
			method: 'GET',
			path: '/v2/datasets/{datasetId}/statistics',
			pathParams: ['datasetId'],
			riskLevel: 'read',
			description:
				'Tool to get dataset field statistics by dataset ID. Use when you need statistical information about dataset fields including min, max, null count, and empty count. Only provides field statistics when dataset schema is configured.',
			slug: 'APIFY_DATASET_STATISTICS_GET',
		},
		getDatasetItems: {
			method: 'GET',
			path: '/v2/datasets/{datasetId}/items',
			pathParams: ['datasetId'],
			queryParams: [
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description:
				'Tool to retrieve items from a dataset. Use when you need to fetch data from a specified dataset by pagination or filtering. Only JSON format is fully supported. For datasets larger than 1000 items, issue multiple calls incrementing `offset` by `limit` until the response returns fewer items than `limit`.',
			slug: 'APIFY_GET_DATASET_ITEMS',
		},
		getListOfDatasets: {
			method: 'GET',
			path: '/v2/datasets',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc', 'unnamed', 'ownership'],
			riskLevel: 'read',
			description:
				"Tool to get list of datasets for a user. Use when you need to enumerate or browse user's datasets. Supports pagination with up to 1000 items per page.",
			slug: 'APIFY_DATASETS_GET',
		},
		storeDataInDataset: {
			method: 'POST',
			path: '/v2/datasets/{datasetId}/items',
			pathParams: ['datasetId'],
			riskLevel: 'write',
			description:
				'Tool to store data items in a dataset. Use after collecting data when you want to batch-append or update items in an existing dataset.',
			slug: 'APIFY_STORE_DATA_IN_DATASET',
		},
		updateDataset: {
			method: 'PUT',
			path: '/v2/datasets/{datasetId}',
			pathParams: ['datasetId'],
			riskLevel: 'write',
			description:
				"Tool to update a dataset's name via JSON payload. Use when you need to rename an existing dataset.",
			slug: 'APIFY_DATASET_PUT',
		},
	},
	keyValueStores: {
		checkKeyValueStoreRecordExists: {
			method: 'HEAD',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'read',
			description:
				'Tool to check if a record exists in a key-value store. Use when you need to verify whether a specific key exists in an Apify Key-Value Store without retrieving its content.',
			slug: 'APIFY_KEY_VALUE_STORE_RECORD_HEAD',
		},
		createKeyValueStore: {
			method: 'POST',
			path: '/v2/key-value-stores',
			pathParams: [],
			queryParams: ['name'],
			riskLevel: 'write',
			description:
				'Tool to create a new key-value store or retrieve an existing one by name. Use when you need to initialize a store for saving data records or files. If a store with the given name already exists, returns that store instead of creating a duplicate.',
			slug: 'APIFY_KEY_VALUE_STORES_POST',
		},
		deleteKeyValueStore: {
			method: 'DELETE',
			path: '/v2/key-value-stores/{storeId}',
			pathParams: ['storeId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a key-value store permanently. Use when you need to remove a key-value store by its ID. Confirm before calling.',
			slug: 'APIFY_KEY_VALUE_STORE_DELETE',
		},
		deleteKeyValueStoreRecord: {
			method: 'DELETE',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a record from a key-value store. Use when you need to remove a specific record by its key from an Apify Key-Value Store.',
			slug: 'APIFY_KEY_VALUE_STORE_RECORD_DELETE',
		},
		getKeyValueRecord: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			queryParams: ['attachment', 'signature'],
			riskLevel: 'read',
			description:
				'Tool to retrieve a record from a key-value store. Use when you need to fetch a specific value by key from an Apify Key-Value Store.',
			slug: 'APIFY_GET_KEY_VALUE_RECORD',
		},
		getKeyValueStore: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}',
			pathParams: ['storeId'],
			riskLevel: 'read',
			description:
				'Tool to retrieve key-value store metadata by store ID. Use when you need detailed information about a specific key-value store including stats and access URLs.',
			slug: 'APIFY_KEY_VALUE_STORE_GET',
		},
		getKeyValueStoreKeys: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}/keys',
			pathParams: ['storeId'],
			queryParams: [
				'exclusiveStartKey',
				'limit',
				'collection',
				'prefix',
				'signature',
			],
			riskLevel: 'read',
			description:
				'Tool to retrieve a list of keys from a key-value store. Use when you need to list keys in a store with optional filtering and pagination support.',
			slug: 'APIFY_KEY_VALUE_STORE_KEYS_GET',
		},
		getListOfKeyValueStores: {
			method: 'GET',
			path: '/v2/key-value-stores',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc', 'unnamed', 'ownership'],
			riskLevel: 'read',
			description:
				'Tool to get the list of key-value stores owned by the user. Use when you need to enumerate or browse available stores. Supports pagination up to 1000 records per request.',
			slug: 'APIFY_KEY_VALUE_STORES_GET',
		},
		storeDataInKeyValueStore: {
			method: 'PUT',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'write',
			description:
				'Tool to create or update a record in a key-value store. Use after you have the store ID and record key to persist JSON data.',
			slug: 'APIFY_STORE_DATA_IN_KEY_VALUE_STORE',
		},
		updateKeyValueStore: {
			method: 'PUT',
			path: '/v2/key-value-stores/{storeId}',
			pathParams: ['storeId'],
			riskLevel: 'write',
			description:
				"Tool to update a key-value store's properties. Use when renaming or changing access or schema version of the store after confirming the store ID.",
			slug: 'APIFY_UPDATE_KEY_VALUE_STORE',
		},
	},
	logs: {
		getLog: {
			method: 'GET',
			path: '/v2/logs/{buildOrRunId}',
			pathParams: ['buildOrRunId'],
			queryParams: ['stream', 'download', 'raw'],
			riskLevel: 'read',
			description:
				'Tool to retrieve logs for a specific Actor run or build. Use after a run completes or fails — a run may report success status yet contain only informational messages, making log inspection the only way to confirm actual outcomes. For long runs, log responses can be very large; prioritize error-level entries and recent timestamps to diagnose issues efficiently.',
			slug: 'APIFY_GET_LOG',
		},
	},
	requestQueues: {
		addRequestToQueue: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/requests',
			pathParams: ['queueId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				'Tool to add a request to the queue. Use when you need to add a web page URL to a request queue for crawling. If a request with the same uniqueKey was already present in the queue, returns the ID of the existing request.',
			slug: 'APIFY_REQUEST_QUEUE_REQUESTS_POST',
		},
		batchAddRequestsToQueue: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/requests/batch',
			pathParams: ['queueId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				'Tool to batch-add up to 25 requests to a request queue. Use when you need to add multiple requests efficiently. Failed requests due to rate limits should be retried with exponential backoff.',
			slug: 'APIFY_REQUEST_QUEUE_REQUESTS_BATCH_POST',
		},
		batchDeleteRequestsFromQueue: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}/requests/batch',
			pathParams: ['queueId'],
			queryParams: ['clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to batch-delete up to 25 requests from a queue. Use when you need to remove multiple requests efficiently. Failed requests due to rate limits should be retried with exponential backoff.',
			slug: 'APIFY_REQUEST_QUEUE_REQUESTS_BATCH_DELETE',
		},
		createRequestQueue: {
			method: 'POST',
			path: '/v2/request-queues',
			pathParams: [],
			queryParams: ['name'],
			riskLevel: 'write',
			description:
				'Tool to create a new request queue or retrieve an existing one by name. Use when you need to initialize a queue for storing and managing web scraping requests. If a queue with the given name already exists, returns that queue instead of creating a duplicate. Unnamed queues follow data retention period policies.',
			slug: 'APIFY_REQUEST_QUEUES_POST',
		},
		deleteRequestLock: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}/requests/{requestId}/lock',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				'Tool to delete a request lock from a request queue. Use when you need to unlock a previously locked request. Only the client that locked the request can delete its lock.',
			slug: 'APIFY_REQUEST_QUEUE_REQUEST_LOCK_DELETE',
		},
		deleteRequestQueue: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}',
			pathParams: ['queueId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a request queue permanently. Use when you need to remove a request queue by its ID.',
			slug: 'APIFY_REQUEST_QUEUE_DELETE',
		},
		deleteRequestFromQueue: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}/requests/{requestId}',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a specific request from a request queue. Use when you need to remove a request by its ID from an Apify request queue.',
			slug: 'APIFY_REQUEST_QUEUE_REQUEST_DELETE',
		},
		getHeadAndLockQueueRequests: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/head/lock',
			pathParams: ['queueId'],
			queryParams: ['lockSecs', 'limit', 'clientKey'],
			riskLevel: 'write',
			description:
				'Tool to get and lock head requests from the queue. Returns the given number of first requests from the queue and locks them for the given time, preventing other clients from accessing them during the lock period. Use when you need to process requests exclusively without concurrent access by other clients.',
			slug: 'APIFY_REQUEST_QUEUE_HEAD_LOCK_POST',
		},
		getRequestQueue: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}',
			pathParams: ['queueId'],
			riskLevel: 'read',
			description:
				'Tool to retrieve request queue metadata by queue ID. Use when you need information about a specific request queue including its statistics and request counts.',
			slug: 'APIFY_REQUEST_QUEUE_GET',
		},
		getRequestQueueHead: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}/head',
			pathParams: ['queueId'],
			queryParams: ['limit', 'clientKey'],
			riskLevel: 'read',
			description:
				'Tool to retrieve first requests from the queue for inspection. Use when you need to examine pending requests without locking them.',
			slug: 'APIFY_REQUEST_QUEUE_HEAD_GET',
		},
		getRequestFromQueue: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}/requests/{requestId}',
			pathParams: ['queueId', 'requestId'],
			riskLevel: 'read',
			description:
				'Tool to retrieve a specific request from a request queue by its ID. Use when you need to get detailed information about a request in an Apify request queue.',
			slug: 'APIFY_REQUEST_QUEUE_REQUEST_GET',
		},
		getListOfRequestQueues: {
			method: 'GET',
			path: '/v2/request-queues',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc', 'unnamed', 'ownership'],
			riskLevel: 'read',
			description:
				"Tool to get list of request queues for a user. Use when you need to enumerate or browse user's request queues. Supports pagination with up to 1000 items per page.",
			slug: 'APIFY_REQUEST_QUEUES_GET',
		},
		listRequestQueueRequests: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}/requests',
			pathParams: ['queueId'],
			queryParams: [
				'clientKey',
				'exclusiveStartId',
				'limit',
				'cursor',
				'filter',
			],
			riskLevel: 'read',
			description:
				'Tool to list requests in a request queue with pagination support. Use when you need to retrieve multiple requests from an Apify request queue.',
			slug: 'APIFY_REQUEST_QUEUE_REQUESTS_GET',
		},
		prolongRequestLock: {
			method: 'PUT',
			path: '/v2/request-queues/{queueId}/requests/{requestId}/lock',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['lockSecs', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				'Tool to prolong request lock in a request queue. Use when you need to extend the lock duration on a previously locked request. Only the client that locked the request can prolong its lock.',
			slug: 'APIFY_REQUEST_QUEUE_REQUEST_LOCK_PUT',
		},
		unlockQueueRequests: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/requests/unlock',
			pathParams: ['queueId'],
			queryParams: ['clientKey'],
			riskLevel: 'write',
			description:
				'Tool to unlock requests in a request queue that are currently locked by the client. If the client is within an Actor run, unlocks all requests locked by that specific run plus all requests locked by the same clientKey. If the client is outside of an Actor run, unlocks all requests locked using the same clientKey.',
			slug: 'APIFY_REQUEST_QUEUE_REQUESTS_UNLOCK_POST',
		},
		updateRequestQueue: {
			method: 'PUT',
			path: '/v2/request-queues/{queueId}',
			pathParams: ['queueId'],
			riskLevel: 'write',
			description:
				'Tool to update request queue name using JSON payload. Use when you need to rename an existing request queue.',
			slug: 'APIFY_REQUEST_QUEUE_PUT',
		},
		updateRequestInQueue: {
			method: 'PUT',
			path: '/v2/request-queues/{queueId}/requests/{requestId}',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['forefront', 'clientKey'],
			riskLevel: 'write',
			description:
				'Tool to update a request in a request queue. Use when you need to modify request properties or mark a request as handled by setting handledAt to the current date/time. If handledAt is set, the request will be removed from the head of the queue and unlocked if applicable.',
			slug: 'APIFY_REQUEST_QUEUE_REQUEST_PUT',
		},
	},
	schedules: {
		createSchedule: {
			method: 'POST',
			path: '/v2/schedules',
			pathParams: [],
			riskLevel: 'write',
			description:
				'Tool to create a new schedule with specified settings. Use when you need to automate Actor or Actor task execution at specific times using cron expressions.',
			slug: 'APIFY_SCHEDULES_POST',
		},
		deleteSchedule: {
			method: 'DELETE',
			path: '/v2/schedules/{scheduleId}',
			pathParams: ['scheduleId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a schedule by its ID. Use when you need to remove a schedule from the Apify system.',
			slug: 'APIFY_SCHEDULE_DELETE',
		},
		getSchedule: {
			method: 'GET',
			path: '/v2/schedules/{scheduleId}',
			pathParams: ['scheduleId'],
			riskLevel: 'read',
			description:
				'Tool to get schedule details by ID. Use when you need to retrieve comprehensive information about a schedule including cron expression, timezone, actions, and execution times.',
			slug: 'APIFY_SCHEDULE_GET',
		},
		getScheduleLog: {
			method: 'GET',
			path: '/v2/schedules/{scheduleId}/log',
			pathParams: ['scheduleId'],
			riskLevel: 'read',
			description:
				'Tool to get schedule log by ID. Use when you need to retrieve execution history for a schedule, including invocation timestamps and status messages. Returns up to 1000 invocations.',
			slug: 'APIFY_SCHEDULE_LOG_GET',
		},
		getListOfSchedules: {
			method: 'GET',
			path: '/v2/schedules',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				"Tool to get list of schedules created by the user. Use when you need to browse or enumerate user's schedules. Supports pagination with up to 1000 items per page.",
			slug: 'APIFY_SCHEDULES_GET',
		},
		updateSchedule: {
			method: 'PUT',
			path: '/v2/schedules/{scheduleId}',
			pathParams: ['scheduleId'],
			riskLevel: 'write',
			description:
				'Tool to update an existing schedule with new settings. Use when you need to modify schedule properties like cron expression, timezone, enabled status, or actions. Only specified fields are updated; others remain unchanged.',
			slug: 'APIFY_SCHEDULE_PUT',
		},
	},
	store: {
		getListOfActorsInStore: {
			method: 'GET',
			path: '/v2/store',
			pathParams: [],
			queryParams: [
				'limit',
				'offset',
				'search',
				'sortBy',
				'category',
				'username',
				'pricingModel',
				'allowsAgenticUsers',
				'responseFormat',
				'includeUnrunnableActors',
			],
			riskLevel: 'read',
			description:
				'Tool to get list of public Actors from Apify Store. Use when you need to browse or search public Actors available in the store. Supports searching by title, name, description, username, and readme.',
			slug: 'APIFY_STORE_GET',
		},
	},
	users: {
		getAccountLimits: {
			method: 'GET',
			path: '/v2/users/me/limits',
			pathParams: [],
			riskLevel: 'read',
			description:
				'Tool to get a complete summary of account limits and usage. Use when you need to retrieve information about usage cycles, spending caps, compute resources, data transfer quotas, and other account limits. This shows the same information as the Limits page in Apify console.',
			slug: 'APIFY_USERS_ME_LIMITS_GET',
		},
		getCurrentUserAccountData: {
			method: 'GET',
			path: '/v2/users/me',
			pathParams: [],
			riskLevel: 'read',
			description:
				"Tool to get private user account information. Use when you need to retrieve comprehensive data about the current user identified by the authentication token, including profile, subscription plan, and proxy settings. Note: 'plan', 'email', and 'profile' fields are omitted when accessed from Actor run.",
			slug: 'APIFY_USERS_ME_GET',
		},
		getMonthlyUsage: {
			method: 'GET',
			path: '/v2/users/me/usage/monthly',
			pathParams: [],
			queryParams: ['date'],
			riskLevel: 'read',
			description:
				'Tool to get monthly usage summary with daily breakdown. Use when you need detailed usage information including storage, data transfer, and request queue metrics for the current or a specific billing cycle. This shows the same information as the Billing page in Apify console.',
			slug: 'APIFY_USERS_ME_USAGE_MONTHLY_GET',
		},
		getPublicUserData: {
			method: 'GET',
			path: '/v2/users/{userId}',
			pathParams: ['userId'],
			riskLevel: 'read',
			description:
				'Tool to get public user data. Use when you need to retrieve publicly accessible information about a specific Apify user account, similar to what can be seen on public profile pages. This operation requires no authentication token.',
			slug: 'APIFY_USER_GET',
		},
		updateAccountLimits: {
			method: 'PUT',
			path: '/v2/users/me/limits',
			pathParams: [],
			riskLevel: 'write',
			description:
				'Tool to update account limits manageable on the Limits page. Use when you need to set or modify the monthly spending cap (maxMonthlyUsageUsd) or data retention period (dataRetentionDays). At least one limit parameter must be provided.',
			slug: 'APIFY_USERS_ME_LIMITS_PUT',
		},
	},
	webhookDispatches: {
		getWebhookDispatch: {
			method: 'GET',
			path: '/v2/webhook-dispatches/{dispatchId}',
			pathParams: ['dispatchId'],
			riskLevel: 'read',
			description:
				'Tool to get webhook dispatch object with all details. Use when you need to retrieve information about a specific webhook dispatch including its status, event data, and call history.',
			slug: 'APIFY_WEBHOOK_DISPATCH_GET',
		},
		getListOfWebhookDispatches: {
			method: 'GET',
			path: '/v2/webhook-dispatches',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get list of webhook dispatches for the user. Use when you need to retrieve webhook execution history with pagination support.',
			slug: 'APIFY_WEBHOOK_DISPATCHES_GET',
		},
	},
	webhooks: {
		createTaskWebhook: {
			method: 'POST',
			path: '/v2/webhooks',
			pathParams: [],
			riskLevel: 'write',
			description:
				'Tool to create a webhook for an Actor task. Use when you need external notifications about task run events (e.g., completion or failure) in downstream systems.',
			slug: 'APIFY_CREATE_TASK_WEBHOOK',
		},
		deleteWebhook: {
			method: 'DELETE',
			path: '/v2/webhooks/{webhookId}',
			pathParams: ['webhookId'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				'Tool to delete a webhook by its ID. Use when removing a webhook after confirming the webhook ID.',
			slug: 'APIFY_DELETE_WEBHOOK',
		},
		getAllWebhooks: {
			method: 'GET',
			path: '/v2/webhooks',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get a list of all webhooks created by the user. Use when you need to enumerate webhooks before filtering or maintenance.',
			slug: 'APIFY_GET_ALL_WEBHOOKS',
		},
		getWebhook: {
			method: 'GET',
			path: '/v2/webhooks/{webhookId}',
			pathParams: ['webhookId'],
			riskLevel: 'read',
			description:
				'Tool to get webhook object with all details. Use when you need to retrieve complete information about a specific webhook by its ID.',
			slug: 'APIFY_WEBHOOK_GET',
		},
		getWebhookDispatches: {
			method: 'GET',
			path: '/v2/webhooks/{webhookId}/dispatches',
			pathParams: ['webhookId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description:
				'Tool to get list of webhook dispatches for a specific webhook. Use when you need to retrieve dispatch history for a particular webhook with pagination support.',
			slug: 'APIFY_WEBHOOK_WEBHOOK_DISPATCHES_GET',
		},
		testWebhook: {
			method: 'POST',
			path: '/v2/webhooks/{webhookId}/test',
			pathParams: ['webhookId'],
			riskLevel: 'write',
			description:
				'Tool to test a webhook by creating a test dispatch with a dummy payload. Use when you need to verify webhook configuration before production use.',
			slug: 'APIFY_WEBHOOK_TEST_POST',
		},
		updateWebhook: {
			method: 'PUT',
			path: '/v2/webhooks/{webhookId}',
			pathParams: ['webhookId'],
			riskLevel: 'write',
			description:
				'Tool to update webhook using JSON payload. Only specified properties are updated; others remain unchanged. Use when you need to modify webhook settings like event types, target URL, or other configuration.',
			slug: 'APIFY_WEBHOOK_PUT',
		},
	},
} as const satisfies ApifyOperationTree;
